// Code generated by ent, DO NOT EDIT.

package uxprojectprompt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the uxprojectprompt type in the database.
	Label = "ux_project_prompt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "prompt_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldPromptKey holds the string denoting the prompt_key field in the database.
	FieldPromptKey = "prompt_key"
	// FieldPromptContent holds the string denoting the prompt_content field in the database.
	FieldPromptContent = "prompt_content"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the uxprojectprompt in the database.
	Table = "ux_project_prompt"
)

// Columns holds all SQL columns for uxprojectprompt fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldPromptKey,
	FieldPromptContent,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PromptKeyValidator is a validator for the "prompt_key" field. It is called by the builders before save.
	PromptKeyValidator func(string) error
	// PromptContentValidator is a validator for the "prompt_content" field. It is called by the builders before save.
	PromptContentValidator func(string) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the UxProjectPrompt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByPromptKey orders the results by the prompt_key field.
func ByPromptKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptKey, opts...).ToFunc()
}

// ByPromptContent orders the results by the prompt_content field.
func ByPromptContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptContent, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
