// Code generated by ent, DO NOT EDIT.

package uxprojectprompt

import (
	"evalux-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEQ(FieldProjectID, v))
}

// PromptKey applies equality check predicate on the "prompt_key" field. It's identical to PromptKeyEQ.
func PromptKey(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEQ(FieldPromptKey, v))
}

// PromptContent applies equality check predicate on the "prompt_content" field. It's identical to PromptContentEQ.
func PromptContent(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEQ(FieldPromptContent, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v uuid.UUID) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldLTE(FieldProjectID, v))
}

// PromptKeyEQ applies the EQ predicate on the "prompt_key" field.
func PromptKeyEQ(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEQ(FieldPromptKey, v))
}

// PromptKeyNEQ applies the NEQ predicate on the "prompt_key" field.
func PromptKeyNEQ(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldNEQ(FieldPromptKey, v))
}

// PromptKeyIn applies the In predicate on the "prompt_key" field.
func PromptKeyIn(vs ...string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldIn(FieldPromptKey, vs...))
}

// PromptKeyNotIn applies the NotIn predicate on the "prompt_key" field.
func PromptKeyNotIn(vs ...string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldNotIn(FieldPromptKey, vs...))
}

// PromptKeyGT applies the GT predicate on the "prompt_key" field.
func PromptKeyGT(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldGT(FieldPromptKey, v))
}

// PromptKeyGTE applies the GTE predicate on the "prompt_key" field.
func PromptKeyGTE(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldGTE(FieldPromptKey, v))
}

// PromptKeyLT applies the LT predicate on the "prompt_key" field.
func PromptKeyLT(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldLT(FieldPromptKey, v))
}

// PromptKeyLTE applies the LTE predicate on the "prompt_key" field.
func PromptKeyLTE(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldLTE(FieldPromptKey, v))
}

// PromptKeyContains applies the Contains predicate on the "prompt_key" field.
func PromptKeyContains(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldContains(FieldPromptKey, v))
}

// PromptKeyHasPrefix applies the HasPrefix predicate on the "prompt_key" field.
func PromptKeyHasPrefix(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldHasPrefix(FieldPromptKey, v))
}

// PromptKeyHasSuffix applies the HasSuffix predicate on the "prompt_key" field.
func PromptKeyHasSuffix(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldHasSuffix(FieldPromptKey, v))
}

// PromptKeyEqualFold applies the EqualFold predicate on the "prompt_key" field.
func PromptKeyEqualFold(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEqualFold(FieldPromptKey, v))
}

// PromptKeyContainsFold applies the ContainsFold predicate on the "prompt_key" field.
func PromptKeyContainsFold(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldContainsFold(FieldPromptKey, v))
}

// PromptContentEQ applies the EQ predicate on the "prompt_content" field.
func PromptContentEQ(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEQ(FieldPromptContent, v))
}

// PromptContentNEQ applies the NEQ predicate on the "prompt_content" field.
func PromptContentNEQ(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldNEQ(FieldPromptContent, v))
}

// PromptContentIn applies the In predicate on the "prompt_content" field.
func PromptContentIn(vs ...string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldIn(FieldPromptContent, vs...))
}

// PromptContentNotIn applies the NotIn predicate on the "prompt_content" field.
func PromptContentNotIn(vs ...string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldNotIn(FieldPromptContent, vs...))
}

// PromptContentGT applies the GT predicate on the "prompt_content" field.
func PromptContentGT(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldGT(FieldPromptContent, v))
}

// PromptContentGTE applies the GTE predicate on the "prompt_content" field.
func PromptContentGTE(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldGTE(FieldPromptContent, v))
}

// PromptContentLT applies the LT predicate on the "prompt_content" field.
func PromptContentLT(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldLT(FieldPromptContent, v))
}

// PromptContentLTE applies the LTE predicate on the "prompt_content" field.
func PromptContentLTE(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldLTE(FieldPromptContent, v))
}

// PromptContentContains applies the Contains predicate on the "prompt_content" field.
func PromptContentContains(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldContains(FieldPromptContent, v))
}

// PromptContentHasPrefix applies the HasPrefix predicate on the "prompt_content" field.
func PromptContentHasPrefix(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldHasPrefix(FieldPromptContent, v))
}

// PromptContentHasSuffix applies the HasSuffix predicate on the "prompt_content" field.
func PromptContentHasSuffix(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldHasSuffix(FieldPromptContent, v))
}

// PromptContentEqualFold applies the EqualFold predicate on the "prompt_content" field.
func PromptContentEqualFold(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEqualFold(FieldPromptContent, v))
}

// PromptContentContainsFold applies the ContainsFold predicate on the "prompt_content" field.
func PromptContentContainsFold(v string) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldContainsFold(FieldPromptContent, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UxProjectPrompt) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UxProjectPrompt) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UxProjectPrompt) predicate.UxProjectPrompt {
	return predicate.UxProjectPrompt(sql.NotPredicates(p))
}
