// Code generated by ent, DO NOT EDIT.

package uxquestionnairetemplate

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the uxquestionnairetemplate type in the database.
	Label = "ux_questionnaire_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "template_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldTemplateName holds the string denoting the template_name field in the database.
	FieldTemplateName = "template_name"
	// FieldDimensionSchema holds the string denoting the dimension_schema field in the database.
	FieldDimensionSchema = "dimension_schema"
	// FieldTemplateDesc holds the string denoting the template_desc field in the database.
	FieldTemplateDesc = "template_desc"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeQuestions holds the string denoting the questions edge name in mutations.
	EdgeQuestions = "questions"
	// UxProjectFieldID holds the string denoting the ID field of the UxProject.
	UxProjectFieldID = "project_id"
	// UxQuestionnaireQuestionFieldID holds the string denoting the ID field of the UxQuestionnaireQuestion.
	UxQuestionnaireQuestionFieldID = "question_id"
	// Table holds the table name of the uxquestionnairetemplate in the database.
	Table = "ux_questionnaire_template"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "ux_questionnaire_template"
	// ProjectInverseTable is the table name for the UxProject entity.
	// It exists in this package in order to avoid circular dependency with the "uxproject" package.
	ProjectInverseTable = "ux_project"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// QuestionsTable is the table that holds the questions relation/edge.
	QuestionsTable = "ux_questionnaire_question"
	// QuestionsInverseTable is the table name for the UxQuestionnaireQuestion entity.
	// It exists in this package in order to avoid circular dependency with the "uxquestionnairequestion" package.
	QuestionsInverseTable = "ux_questionnaire_question"
	// QuestionsColumn is the table column denoting the questions relation/edge.
	QuestionsColumn = "template_id"
)

// Columns holds all SQL columns for uxquestionnairetemplate fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldTemplateName,
	FieldDimensionSchema,
	FieldTemplateDesc,
	FieldStatus,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TemplateNameValidator is a validator for the "template_name" field. It is called by the builders before save.
	TemplateNameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusACTIVE is the default value of the Status enum.
const DefaultStatus = StatusACTIVE

// Status values.
const (
	StatusACTIVE   Status = "ACTIVE"
	StatusDISABLED Status = "DISABLED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusACTIVE, StatusDISABLED:
		return nil
	default:
		return fmt.Errorf("uxquestionnairetemplate: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the UxQuestionnaireTemplate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByTemplateName orders the results by the template_name field.
func ByTemplateName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateName, opts...).ToFunc()
}

// ByTemplateDesc orders the results by the template_desc field.
func ByTemplateDesc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateDesc, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByQuestionsCount orders the results by questions count.
func ByQuestionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQuestionsStep(), opts...)
	}
}

// ByQuestions orders the results by questions terms.
func ByQuestions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuestionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, UxProjectFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newQuestionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuestionsInverseTable, UxQuestionnaireQuestionFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, QuestionsTable, QuestionsColumn),
	)
}
