// Code generated by ent, DO NOT EDIT.

package syspermission

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the syspermission type in the database.
	Label = "sys_permission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "permission_id"
	// FieldPermissionCode holds the string denoting the permission_code field in the database.
	FieldPermissionCode = "permission_code"
	// FieldPermissionName holds the string denoting the permission_name field in the database.
	FieldPermissionName = "permission_name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeRolePermissions holds the string denoting the role_permissions edge name in mutations.
	EdgeRolePermissions = "role_permissions"
	// EdgeUserModulePermissions holds the string denoting the user_module_permissions edge name in mutations.
	EdgeUserModulePermissions = "user_module_permissions"
	// SysRolePermissionFieldID holds the string denoting the ID field of the SysRolePermission.
	SysRolePermissionFieldID = "role_permission_id"
	// SysUserModulePermissionFieldID holds the string denoting the ID field of the SysUserModulePermission.
	SysUserModulePermissionFieldID = "user_module_permission_id"
	// Table holds the table name of the syspermission in the database.
	Table = "sys_permission"
	// RolePermissionsTable is the table that holds the role_permissions relation/edge.
	RolePermissionsTable = "sys_role_permission"
	// RolePermissionsInverseTable is the table name for the SysRolePermission entity.
	// It exists in this package in order to avoid circular dependency with the "sysrolepermission" package.
	RolePermissionsInverseTable = "sys_role_permission"
	// RolePermissionsColumn is the table column denoting the role_permissions relation/edge.
	RolePermissionsColumn = "permission_id"
	// UserModulePermissionsTable is the table that holds the user_module_permissions relation/edge.
	UserModulePermissionsTable = "sys_user_module_permission"
	// UserModulePermissionsInverseTable is the table name for the SysUserModulePermission entity.
	// It exists in this package in order to avoid circular dependency with the "sysusermodulepermission" package.
	UserModulePermissionsInverseTable = "sys_user_module_permission"
	// UserModulePermissionsColumn is the table column denoting the user_module_permissions relation/edge.
	UserModulePermissionsColumn = "permission_id"
)

// Columns holds all SQL columns for syspermission fields.
var Columns = []string{
	FieldID,
	FieldPermissionCode,
	FieldPermissionName,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PermissionCodeValidator is a validator for the "permission_code" field. It is called by the builders before save.
	PermissionCodeValidator func(string) error
	// PermissionNameValidator is a validator for the "permission_name" field. It is called by the builders before save.
	PermissionNameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the SysPermission queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPermissionCode orders the results by the permission_code field.
func ByPermissionCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermissionCode, opts...).ToFunc()
}

// ByPermissionName orders the results by the permission_name field.
func ByPermissionName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermissionName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByRolePermissionsCount orders the results by role_permissions count.
func ByRolePermissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRolePermissionsStep(), opts...)
	}
}

// ByRolePermissions orders the results by role_permissions terms.
func ByRolePermissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRolePermissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserModulePermissionsCount orders the results by user_module_permissions count.
func ByUserModulePermissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserModulePermissionsStep(), opts...)
	}
}

// ByUserModulePermissions orders the results by user_module_permissions terms.
func ByUserModulePermissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserModulePermissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRolePermissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RolePermissionsInverseTable, SysRolePermissionFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RolePermissionsTable, RolePermissionsColumn),
	)
}
func newUserModulePermissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserModulePermissionsInverseTable, SysUserModulePermissionFieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserModulePermissionsTable, UserModulePermissionsColumn),
	)
}
