// Code generated by ent, DO NOT EDIT.

package uxresultsnapshot

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the uxresultsnapshot type in the database.
	Label = "ux_result_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "snapshot_id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldBatchID holds the string denoting the batch_id field in the database.
	FieldBatchID = "batch_id"
	// FieldScopeType holds the string denoting the scope_type field in the database.
	FieldScopeType = "scope_type"
	// FieldScopeKey holds the string denoting the scope_key field in the database.
	FieldScopeKey = "scope_key"
	// FieldTotalSessions holds the string denoting the total_sessions field in the database.
	FieldTotalSessions = "total_sessions"
	// FieldCompletedSessions holds the string denoting the completed_sessions field in the database.
	FieldCompletedSessions = "completed_sessions"
	// FieldFailedSessions holds the string denoting the failed_sessions field in the database.
	FieldFailedSessions = "failed_sessions"
	// FieldCompletionRate holds the string denoting the completion_rate field in the database.
	FieldCompletionRate = "completion_rate"
	// FieldAvgDurationMs holds the string denoting the avg_duration_ms field in the database.
	FieldAvgDurationMs = "avg_duration_ms"
	// FieldAvgErrorCount holds the string denoting the avg_error_count field in the database.
	FieldAvgErrorCount = "avg_error_count"
	// FieldAvgScore holds the string denoting the avg_score field in the database.
	FieldAvgScore = "avg_score"
	// FieldMetricPayload holds the string denoting the metric_payload field in the database.
	FieldMetricPayload = "metric_payload"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeRun holds the string denoting the run edge name in mutations.
	EdgeRun = "run"
	// UxExecutionRunFieldID holds the string denoting the ID field of the UxExecutionRun.
	UxExecutionRunFieldID = "run_id"
	// Table holds the table name of the uxresultsnapshot in the database.
	Table = "ux_result_snapshot"
	// RunTable is the table that holds the run relation/edge.
	RunTable = "ux_result_snapshot"
	// RunInverseTable is the table name for the UxExecutionRun entity.
	// It exists in this package in order to avoid circular dependency with the "uxexecutionrun" package.
	RunInverseTable = "ux_execution_run"
	// RunColumn is the table column denoting the run relation/edge.
	RunColumn = "run_id"
)

// Columns holds all SQL columns for uxresultsnapshot fields.
var Columns = []string{
	FieldID,
	FieldRunID,
	FieldBatchID,
	FieldScopeType,
	FieldScopeKey,
	FieldTotalSessions,
	FieldCompletedSessions,
	FieldFailedSessions,
	FieldCompletionRate,
	FieldAvgDurationMs,
	FieldAvgErrorCount,
	FieldAvgScore,
	FieldMetricPayload,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BatchIDValidator is a validator for the "batch_id" field. It is called by the builders before save.
	BatchIDValidator func(string) error
	// DefaultTotalSessions holds the default value on creation for the "total_sessions" field.
	DefaultTotalSessions int
	// DefaultCompletedSessions holds the default value on creation for the "completed_sessions" field.
	DefaultCompletedSessions int
	// DefaultFailedSessions holds the default value on creation for the "failed_sessions" field.
	DefaultFailedSessions int
	// DefaultCompletionRate holds the default value on creation for the "completion_rate" field.
	DefaultCompletionRate float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ScopeType defines the type for the "scope_type" enum field.
type ScopeType string

// ScopeType values.
const (
	ScopeTypeTASK    ScopeType = "TASK"
	ScopeTypePROFILE ScopeType = "PROFILE"
	ScopeTypeOVERALL ScopeType = "OVERALL"
)

func (st ScopeType) String() string {
	return string(st)
}

// ScopeTypeValidator is a validator for the "scope_type" field enum values. It is called by the builders before save.
func ScopeTypeValidator(st ScopeType) error {
	switch st {
	case ScopeTypeTASK, ScopeTypePROFILE, ScopeTypeOVERALL:
		return nil
	default:
		return fmt.Errorf("uxresultsnapshot: invalid enum value for scope_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the UxResultSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByBatchID orders the results by the batch_id field.
func ByBatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchID, opts...).ToFunc()
}

// ByScopeType orders the results by the scope_type field.
func ByScopeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeType, opts...).ToFunc()
}

// ByScopeKey orders the results by the scope_key field.
func ByScopeKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeKey, opts...).ToFunc()
}

// ByTotalSessions orders the results by the total_sessions field.
func ByTotalSessions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalSessions, opts...).ToFunc()
}

// ByCompletedSessions orders the results by the completed_sessions field.
func ByCompletedSessions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedSessions, opts...).ToFunc()
}

// ByFailedSessions orders the results by the failed_sessions field.
func ByFailedSessions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedSessions, opts...).ToFunc()
}

// ByCompletionRate orders the results by the completion_rate field.
func ByCompletionRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionRate, opts...).ToFunc()
}

// ByAvgDurationMs orders the results by the avg_duration_ms field.
func ByAvgDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvgDurationMs, opts...).ToFunc()
}

// ByAvgErrorCount orders the results by the avg_error_count field.
func ByAvgErrorCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvgErrorCount, opts...).ToFunc()
}

// ByAvgScore orders the results by the avg_score field.
func ByAvgScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvgScore, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRunField orders the results by run field.
func ByRunField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRunStep(), sql.OrderByField(field, opts...))
	}
}
func newRunStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RunInverseTable, UxExecutionRunFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RunTable, RunColumn),
	)
}
