// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"evalux-server/ent/predicate"
	"evalux-server/ent/syspermission"
	"evalux-server/ent/sysrolepermission"
	"evalux-server/ent/sysusermodulepermission"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SysPermissionUpdate is the builder for updating SysPermission entities.
type SysPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *SysPermissionMutation
}

// Where appends a list predicates to the SysPermissionUpdate builder.
func (_u *SysPermissionUpdate) Where(ps ...predicate.SysPermission) *SysPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPermissionCode sets the "permission_code" field.
func (_u *SysPermissionUpdate) SetPermissionCode(v string) *SysPermissionUpdate {
	_u.mutation.SetPermissionCode(v)
	return _u
}

// SetNillablePermissionCode sets the "permission_code" field if the given value is not nil.
func (_u *SysPermissionUpdate) SetNillablePermissionCode(v *string) *SysPermissionUpdate {
	if v != nil {
		_u.SetPermissionCode(*v)
	}
	return _u
}

// SetPermissionName sets the "permission_name" field.
func (_u *SysPermissionUpdate) SetPermissionName(v string) *SysPermissionUpdate {
	_u.mutation.SetPermissionName(v)
	return _u
}

// SetNillablePermissionName sets the "permission_name" field if the given value is not nil.
func (_u *SysPermissionUpdate) SetNillablePermissionName(v *string) *SysPermissionUpdate {
	if v != nil {
		_u.SetPermissionName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SysPermissionUpdate) SetDescription(v string) *SysPermissionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SysPermissionUpdate) SetNillableDescription(v *string) *SysPermissionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SysPermissionUpdate) ClearDescription() *SysPermissionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// AddRolePermissionIDs adds the "role_permissions" edge to the SysRolePermission entity by IDs.
func (_u *SysPermissionUpdate) AddRolePermissionIDs(ids ...uuid.UUID) *SysPermissionUpdate {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the SysRolePermission entity.
func (_u *SysPermissionUpdate) AddRolePermissions(v ...*SysRolePermission) *SysPermissionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// AddUserModulePermissionIDs adds the "user_module_permissions" edge to the SysUserModulePermission entity by IDs.
func (_u *SysPermissionUpdate) AddUserModulePermissionIDs(ids ...uuid.UUID) *SysPermissionUpdate {
	_u.mutation.AddUserModulePermissionIDs(ids...)
	return _u
}

// AddUserModulePermissions adds the "user_module_permissions" edges to the SysUserModulePermission entity.
func (_u *SysPermissionUpdate) AddUserModulePermissions(v ...*SysUserModulePermission) *SysPermissionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserModulePermissionIDs(ids...)
}

// Mutation returns the SysPermissionMutation object of the builder.
func (_u *SysPermissionUpdate) Mutation() *SysPermissionMutation {
	return _u.mutation
}

// ClearRolePermissions clears all "role_permissions" edges to the SysRolePermission entity.
func (_u *SysPermissionUpdate) ClearRolePermissions() *SysPermissionUpdate {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to SysRolePermission entities by IDs.
func (_u *SysPermissionUpdate) RemoveRolePermissionIDs(ids ...uuid.UUID) *SysPermissionUpdate {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to SysRolePermission entities.
func (_u *SysPermissionUpdate) RemoveRolePermissions(v ...*SysRolePermission) *SysPermissionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// ClearUserModulePermissions clears all "user_module_permissions" edges to the SysUserModulePermission entity.
func (_u *SysPermissionUpdate) ClearUserModulePermissions() *SysPermissionUpdate {
	_u.mutation.ClearUserModulePermissions()
	return _u
}

// RemoveUserModulePermissionIDs removes the "user_module_permissions" edge to SysUserModulePermission entities by IDs.
func (_u *SysPermissionUpdate) RemoveUserModulePermissionIDs(ids ...uuid.UUID) *SysPermissionUpdate {
	_u.mutation.RemoveUserModulePermissionIDs(ids...)
	return _u
}

// RemoveUserModulePermissions removes "user_module_permissions" edges to SysUserModulePermission entities.
func (_u *SysPermissionUpdate) RemoveUserModulePermissions(v ...*SysUserModulePermission) *SysPermissionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserModulePermissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SysPermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SysPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysPermissionUpdate) check() error {
	if v, ok := _u.mutation.PermissionCode(); ok {
		if err := syspermission.PermissionCodeValidator(v); err != nil {
			return &ValidationError{Name: "permission_code", err: fmt.Errorf(`ent: validator failed for field "SysPermission.permission_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PermissionName(); ok {
		if err := syspermission.PermissionNameValidator(v); err != nil {
			return &ValidationError{Name: "permission_name", err: fmt.Errorf(`ent: validator failed for field "SysPermission.permission_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SysPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syspermission.Table, syspermission.Columns, sqlgraph.NewFieldSpec(syspermission.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PermissionCode(); ok {
		_spec.SetField(syspermission.FieldPermissionCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionName(); ok {
		_spec.SetField(syspermission.FieldPermissionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(syspermission.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(syspermission.FieldDescription, field.TypeString)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.RolePermissionsTable,
			Columns: []string{syspermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrolepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.RolePermissionsTable,
			Columns: []string{syspermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.RolePermissionsTable,
			Columns: []string{syspermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserModulePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.UserModulePermissionsTable,
			Columns: []string{syspermission.UserModulePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysusermodulepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserModulePermissionsIDs(); len(nodes) > 0 && !_u.mutation.UserModulePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.UserModulePermissionsTable,
			Columns: []string{syspermission.UserModulePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysusermodulepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserModulePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.UserModulePermissionsTable,
			Columns: []string{syspermission.UserModulePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysusermodulepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syspermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SysPermissionUpdateOne is the builder for updating a single SysPermission entity.
type SysPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysPermissionMutation
}

// SetPermissionCode sets the "permission_code" field.
func (_u *SysPermissionUpdateOne) SetPermissionCode(v string) *SysPermissionUpdateOne {
	_u.mutation.SetPermissionCode(v)
	return _u
}

// SetNillablePermissionCode sets the "permission_code" field if the given value is not nil.
func (_u *SysPermissionUpdateOne) SetNillablePermissionCode(v *string) *SysPermissionUpdateOne {
	if v != nil {
		_u.SetPermissionCode(*v)
	}
	return _u
}

// SetPermissionName sets the "permission_name" field.
func (_u *SysPermissionUpdateOne) SetPermissionName(v string) *SysPermissionUpdateOne {
	_u.mutation.SetPermissionName(v)
	return _u
}

// SetNillablePermissionName sets the "permission_name" field if the given value is not nil.
func (_u *SysPermissionUpdateOne) SetNillablePermissionName(v *string) *SysPermissionUpdateOne {
	if v != nil {
		_u.SetPermissionName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SysPermissionUpdateOne) SetDescription(v string) *SysPermissionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SysPermissionUpdateOne) SetNillableDescription(v *string) *SysPermissionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SysPermissionUpdateOne) ClearDescription() *SysPermissionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// AddRolePermissionIDs adds the "role_permissions" edge to the SysRolePermission entity by IDs.
func (_u *SysPermissionUpdateOne) AddRolePermissionIDs(ids ...uuid.UUID) *SysPermissionUpdateOne {
	_u.mutation.AddRolePermissionIDs(ids...)
	return _u
}

// AddRolePermissions adds the "role_permissions" edges to the SysRolePermission entity.
func (_u *SysPermissionUpdateOne) AddRolePermissions(v ...*SysRolePermission) *SysPermissionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRolePermissionIDs(ids...)
}

// AddUserModulePermissionIDs adds the "user_module_permissions" edge to the SysUserModulePermission entity by IDs.
func (_u *SysPermissionUpdateOne) AddUserModulePermissionIDs(ids ...uuid.UUID) *SysPermissionUpdateOne {
	_u.mutation.AddUserModulePermissionIDs(ids...)
	return _u
}

// AddUserModulePermissions adds the "user_module_permissions" edges to the SysUserModulePermission entity.
func (_u *SysPermissionUpdateOne) AddUserModulePermissions(v ...*SysUserModulePermission) *SysPermissionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserModulePermissionIDs(ids...)
}

// Mutation returns the SysPermissionMutation object of the builder.
func (_u *SysPermissionUpdateOne) Mutation() *SysPermissionMutation {
	return _u.mutation
}

// ClearRolePermissions clears all "role_permissions" edges to the SysRolePermission entity.
func (_u *SysPermissionUpdateOne) ClearRolePermissions() *SysPermissionUpdateOne {
	_u.mutation.ClearRolePermissions()
	return _u
}

// RemoveRolePermissionIDs removes the "role_permissions" edge to SysRolePermission entities by IDs.
func (_u *SysPermissionUpdateOne) RemoveRolePermissionIDs(ids ...uuid.UUID) *SysPermissionUpdateOne {
	_u.mutation.RemoveRolePermissionIDs(ids...)
	return _u
}

// RemoveRolePermissions removes "role_permissions" edges to SysRolePermission entities.
func (_u *SysPermissionUpdateOne) RemoveRolePermissions(v ...*SysRolePermission) *SysPermissionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRolePermissionIDs(ids...)
}

// ClearUserModulePermissions clears all "user_module_permissions" edges to the SysUserModulePermission entity.
func (_u *SysPermissionUpdateOne) ClearUserModulePermissions() *SysPermissionUpdateOne {
	_u.mutation.ClearUserModulePermissions()
	return _u
}

// RemoveUserModulePermissionIDs removes the "user_module_permissions" edge to SysUserModulePermission entities by IDs.
func (_u *SysPermissionUpdateOne) RemoveUserModulePermissionIDs(ids ...uuid.UUID) *SysPermissionUpdateOne {
	_u.mutation.RemoveUserModulePermissionIDs(ids...)
	return _u
}

// RemoveUserModulePermissions removes "user_module_permissions" edges to SysUserModulePermission entities.
func (_u *SysPermissionUpdateOne) RemoveUserModulePermissions(v ...*SysUserModulePermission) *SysPermissionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserModulePermissionIDs(ids...)
}

// Where appends a list predicates to the SysPermissionUpdate builder.
func (_u *SysPermissionUpdateOne) Where(ps ...predicate.SysPermission) *SysPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SysPermissionUpdateOne) Select(field string, fields ...string) *SysPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SysPermission entity.
func (_u *SysPermissionUpdateOne) Save(ctx context.Context) (*SysPermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysPermissionUpdateOne) SaveX(ctx context.Context) *SysPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SysPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.PermissionCode(); ok {
		if err := syspermission.PermissionCodeValidator(v); err != nil {
			return &ValidationError{Name: "permission_code", err: fmt.Errorf(`ent: validator failed for field "SysPermission.permission_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PermissionName(); ok {
		if err := syspermission.PermissionNameValidator(v); err != nil {
			return &ValidationError{Name: "permission_name", err: fmt.Errorf(`ent: validator failed for field "SysPermission.permission_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SysPermissionUpdateOne) sqlSave(ctx context.Context) (_node *SysPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syspermission.Table, syspermission.Columns, sqlgraph.NewFieldSpec(syspermission.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syspermission.FieldID)
		for _, f := range fields {
			if !syspermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != syspermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PermissionCode(); ok {
		_spec.SetField(syspermission.FieldPermissionCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionName(); ok {
		_spec.SetField(syspermission.FieldPermissionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(syspermission.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(syspermission.FieldDescription, field.TypeString)
	}
	if _u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.RolePermissionsTable,
			Columns: []string{syspermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrolepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolePermissionsIDs(); len(nodes) > 0 && !_u.mutation.RolePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.RolePermissionsTable,
			Columns: []string{syspermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.RolePermissionsTable,
			Columns: []string{syspermission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrolepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserModulePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.UserModulePermissionsTable,
			Columns: []string{syspermission.UserModulePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysusermodulepermission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserModulePermissionsIDs(); len(nodes) > 0 && !_u.mutation.UserModulePermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.UserModulePermissionsTable,
			Columns: []string{syspermission.UserModulePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysusermodulepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserModulePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syspermission.UserModulePermissionsTable,
			Columns: []string{syspermission.UserModulePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysusermodulepermission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SysPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syspermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
