// Code generated by ent, DO NOT EDIT.

package ent

import (
	"evalux-server/ent/sysmodule"
	"evalux-server/ent/syspermission"
	"evalux-server/ent/sysrole"
	"evalux-server/ent/sysrolepermission"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// SysRolePermission is the model entity for the SysRolePermission schema.
type SysRolePermission struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID uuid.UUID `json:"role_id,omitempty"`
	// ModuleID holds the value of the "module_id" field.
	ModuleID uuid.UUID `json:"module_id,omitempty"`
	// PermissionID holds the value of the "permission_id" field.
	PermissionID uuid.UUID `json:"permission_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SysRolePermissionQuery when eager-loading is set.
	Edges        SysRolePermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SysRolePermissionEdges holds the relations/edges for other nodes in the graph.
type SysRolePermissionEdges struct {
	// Role holds the value of the role edge.
	Role *SysRole `json:"role,omitempty"`
	// Module holds the value of the module edge.
	Module *SysModule `json:"module,omitempty"`
	// Permission holds the value of the permission edge.
	Permission *SysPermission `json:"permission,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysRolePermissionEdges) RoleOrErr() (*SysRole, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sysrole.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// ModuleOrErr returns the Module value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysRolePermissionEdges) ModuleOrErr() (*SysModule, error) {
	if e.Module != nil {
		return e.Module, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: sysmodule.Label}
	}
	return nil, &NotLoadedError{edge: "module"}
}

// PermissionOrErr returns the Permission value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysRolePermissionEdges) PermissionOrErr() (*SysPermission, error) {
	if e.Permission != nil {
		return e.Permission, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: syspermission.Label}
	}
	return nil, &NotLoadedError{edge: "permission"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysRolePermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysrolepermission.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case sysrolepermission.FieldID, sysrolepermission.FieldRoleID, sysrolepermission.FieldModuleID, sysrolepermission.FieldPermissionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysRolePermission fields.
func (_m *SysRolePermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysrolepermission.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case sysrolepermission.FieldRoleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value != nil {
				_m.RoleID = *value
			}
		case sysrolepermission.FieldModuleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field module_id", values[i])
			} else if value != nil {
				_m.ModuleID = *value
			}
		case sysrolepermission.FieldPermissionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value != nil {
				_m.PermissionID = *value
			}
		case sysrolepermission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysRolePermission.
// This includes values selected through modifiers, order, etc.
func (_m *SysRolePermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the SysRolePermission entity.
func (_m *SysRolePermission) QueryRole() *SysRoleQuery {
	return NewSysRolePermissionClient(_m.config).QueryRole(_m)
}

// QueryModule queries the "module" edge of the SysRolePermission entity.
func (_m *SysRolePermission) QueryModule() *SysModuleQuery {
	return NewSysRolePermissionClient(_m.config).QueryModule(_m)
}

// QueryPermission queries the "permission" edge of the SysRolePermission entity.
func (_m *SysRolePermission) QueryPermission() *SysPermissionQuery {
	return NewSysRolePermissionClient(_m.config).QueryPermission(_m)
}

// Update returns a builder for updating this SysRolePermission.
// Note that you need to call SysRolePermission.Unwrap() before calling this method if this SysRolePermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysRolePermission) Update() *SysRolePermissionUpdateOne {
	return NewSysRolePermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysRolePermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysRolePermission) Unwrap() *SysRolePermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysRolePermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysRolePermission) String() string {
	var builder strings.Builder
	builder.WriteString("SysRolePermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("module_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModuleID))
	builder.WriteString(", ")
	builder.WriteString("permission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermissionID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SysRolePermissions is a parsable slice of SysRolePermission.
type SysRolePermissions []*SysRolePermission
