// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"evalux-server/ent/sysrole"
	"evalux-server/ent/sysuser"
	"evalux-server/ent/sysuserrole"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SysUserRoleCreate is the builder for creating a SysUserRole entity.
type SysUserRoleCreate struct {
	config
	mutation *SysUserRoleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *SysUserRoleCreate) SetUserID(v uuid.UUID) *SysUserRoleCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *SysUserRoleCreate) SetRoleID(v uuid.UUID) *SysUserRoleCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SysUserRoleCreate) SetCreatedAt(v time.Time) *SysUserRoleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SysUserRoleCreate) SetNillableCreatedAt(v *time.Time) *SysUserRoleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SysUserRoleCreate) SetID(v uuid.UUID) *SysUserRoleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SysUserRoleCreate) SetNillableID(v *uuid.UUID) *SysUserRoleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the SysUser entity.
func (_c *SysUserRoleCreate) SetUser(v *SysUser) *SysUserRoleCreate {
	return _c.SetUserID(v.ID)
}

// SetRole sets the "role" edge to the SysRole entity.
func (_c *SysUserRoleCreate) SetRole(v *SysRole) *SysUserRoleCreate {
	return _c.SetRoleID(v.ID)
}

// Mutation returns the SysUserRoleMutation object of the builder.
func (_c *SysUserRoleCreate) Mutation() *SysUserRoleMutation {
	return _c.mutation
}

// Save creates the SysUserRole in the database.
func (_c *SysUserRoleCreate) Save(ctx context.Context) (*SysUserRole, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SysUserRoleCreate) SaveX(ctx context.Context) *SysUserRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysUserRoleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysUserRoleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SysUserRoleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sysuserrole.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := sysuserrole.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SysUserRoleCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SysUserRole.user_id"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "SysUserRole.role_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysUserRole.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SysUserRole.user"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "SysUserRole.role"`)}
	}
	return nil
}

func (_c *SysUserRoleCreate) sqlSave(ctx context.Context) (*SysUserRole, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SysUserRoleCreate) createSpec() (*SysUserRole, *sqlgraph.CreateSpec) {
	var (
		_node = &SysUserRole{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sysuserrole.Table, sqlgraph.NewFieldSpec(sysuserrole.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sysuserrole.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuserrole.UserTable,
			Columns: []string{sysuserrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuserrole.RoleTable,
			Columns: []string{sysuserrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SysUserRole.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SysUserRoleUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *SysUserRoleCreate) OnConflict(opts ...sql.ConflictOption) *SysUserRoleUpsertOne {
	_c.conflict = opts
	return &SysUserRoleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SysUserRole.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SysUserRoleCreate) OnConflictColumns(columns ...string) *SysUserRoleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SysUserRoleUpsertOne{
		create: _c,
	}
}

type (
	// SysUserRoleUpsertOne is the builder for "upsert"-ing
	//  one SysUserRole node.
	SysUserRoleUpsertOne struct {
		create *SysUserRoleCreate
	}

	// SysUserRoleUpsert is the "OnConflict" setter.
	SysUserRoleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *SysUserRoleUpsert) SetUserID(v uuid.UUID) *SysUserRoleUpsert {
	u.Set(sysuserrole.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SysUserRoleUpsert) UpdateUserID() *SysUserRoleUpsert {
	u.SetExcluded(sysuserrole.FieldUserID)
	return u
}

// SetRoleID sets the "role_id" field.
func (u *SysUserRoleUpsert) SetRoleID(v uuid.UUID) *SysUserRoleUpsert {
	u.Set(sysuserrole.FieldRoleID, v)
	return u
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *SysUserRoleUpsert) UpdateRoleID() *SysUserRoleUpsert {
	u.SetExcluded(sysuserrole.FieldRoleID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SysUserRole.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sysuserrole.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SysUserRoleUpsertOne) UpdateNewValues() *SysUserRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(sysuserrole.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sysuserrole.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SysUserRole.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SysUserRoleUpsertOne) Ignore() *SysUserRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SysUserRoleUpsertOne) DoNothing() *SysUserRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SysUserRoleCreate.OnConflict
// documentation for more info.
func (u *SysUserRoleUpsertOne) Update(set func(*SysUserRoleUpsert)) *SysUserRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SysUserRoleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SysUserRoleUpsertOne) SetUserID(v uuid.UUID) *SysUserRoleUpsertOne {
	return u.Update(func(s *SysUserRoleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SysUserRoleUpsertOne) UpdateUserID() *SysUserRoleUpsertOne {
	return u.Update(func(s *SysUserRoleUpsert) {
		s.UpdateUserID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *SysUserRoleUpsertOne) SetRoleID(v uuid.UUID) *SysUserRoleUpsertOne {
	return u.Update(func(s *SysUserRoleUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *SysUserRoleUpsertOne) UpdateRoleID() *SysUserRoleUpsertOne {
	return u.Update(func(s *SysUserRoleUpsert) {
		s.UpdateRoleID()
	})
}

// Exec executes the query.
func (u *SysUserRoleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SysUserRoleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SysUserRoleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SysUserRoleUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SysUserRoleUpsertOne.ID is not supported by MySQL driver. Use SysUserRoleUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SysUserRoleUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SysUserRoleCreateBulk is the builder for creating many SysUserRole entities in bulk.
type SysUserRoleCreateBulk struct {
	config
	err      error
	builders []*SysUserRoleCreate
	conflict []sql.ConflictOption
}

// Save creates the SysUserRole entities in the database.
func (_c *SysUserRoleCreateBulk) Save(ctx context.Context) ([]*SysUserRole, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SysUserRole, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysUserRoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SysUserRoleCreateBulk) SaveX(ctx context.Context) []*SysUserRole {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysUserRoleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysUserRoleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SysUserRole.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SysUserRoleUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *SysUserRoleCreateBulk) OnConflict(opts ...sql.ConflictOption) *SysUserRoleUpsertBulk {
	_c.conflict = opts
	return &SysUserRoleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SysUserRole.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SysUserRoleCreateBulk) OnConflictColumns(columns ...string) *SysUserRoleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SysUserRoleUpsertBulk{
		create: _c,
	}
}

// SysUserRoleUpsertBulk is the builder for "upsert"-ing
// a bulk of SysUserRole nodes.
type SysUserRoleUpsertBulk struct {
	create *SysUserRoleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SysUserRole.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sysuserrole.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SysUserRoleUpsertBulk) UpdateNewValues() *SysUserRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(sysuserrole.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sysuserrole.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SysUserRole.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SysUserRoleUpsertBulk) Ignore() *SysUserRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SysUserRoleUpsertBulk) DoNothing() *SysUserRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SysUserRoleCreateBulk.OnConflict
// documentation for more info.
func (u *SysUserRoleUpsertBulk) Update(set func(*SysUserRoleUpsert)) *SysUserRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SysUserRoleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SysUserRoleUpsertBulk) SetUserID(v uuid.UUID) *SysUserRoleUpsertBulk {
	return u.Update(func(s *SysUserRoleUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SysUserRoleUpsertBulk) UpdateUserID() *SysUserRoleUpsertBulk {
	return u.Update(func(s *SysUserRoleUpsert) {
		s.UpdateUserID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *SysUserRoleUpsertBulk) SetRoleID(v uuid.UUID) *SysUserRoleUpsertBulk {
	return u.Update(func(s *SysUserRoleUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *SysUserRoleUpsertBulk) UpdateRoleID() *SysUserRoleUpsertBulk {
	return u.Update(func(s *SysUserRoleUpsert) {
		s.UpdateRoleID()
	})
}

// Exec executes the query.
func (u *SysUserRoleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SysUserRoleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SysUserRoleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SysUserRoleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
