// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"evalux-server/ent/predicate"
	"evalux-server/ent/sysmodule"
	"evalux-server/ent/syspermission"
	"evalux-server/ent/sysuser"
	"evalux-server/ent/sysusermodulepermission"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SysUserModulePermissionQuery is the builder for querying SysUserModulePermission entities.
type SysUserModulePermissionQuery struct {
	config
	ctx            *QueryContext
	order          []sysusermodulepermission.OrderOption
	inters         []Interceptor
	predicates     []predicate.SysUserModulePermission
	withUser       *SysUserQuery
	withModule     *SysModuleQuery
	withPermission *SysPermissionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SysUserModulePermissionQuery builder.
func (_q *SysUserModulePermissionQuery) Where(ps ...predicate.SysUserModulePermission) *SysUserModulePermissionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SysUserModulePermissionQuery) Limit(limit int) *SysUserModulePermissionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SysUserModulePermissionQuery) Offset(offset int) *SysUserModulePermissionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SysUserModulePermissionQuery) Unique(unique bool) *SysUserModulePermissionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SysUserModulePermissionQuery) Order(o ...sysusermodulepermission.OrderOption) *SysUserModulePermissionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *SysUserModulePermissionQuery) QueryUser() *SysUserQuery {
	query := (&SysUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sysusermodulepermission.Table, sysusermodulepermission.FieldID, selector),
			sqlgraph.To(sysuser.Table, sysuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sysusermodulepermission.UserTable, sysusermodulepermission.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryModule chains the current query on the "module" edge.
func (_q *SysUserModulePermissionQuery) QueryModule() *SysModuleQuery {
	query := (&SysModuleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sysusermodulepermission.Table, sysusermodulepermission.FieldID, selector),
			sqlgraph.To(sysmodule.Table, sysmodule.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sysusermodulepermission.ModuleTable, sysusermodulepermission.ModuleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPermission chains the current query on the "permission" edge.
func (_q *SysUserModulePermissionQuery) QueryPermission() *SysPermissionQuery {
	query := (&SysPermissionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sysusermodulepermission.Table, sysusermodulepermission.FieldID, selector),
			sqlgraph.To(syspermission.Table, syspermission.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sysusermodulepermission.PermissionTable, sysusermodulepermission.PermissionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SysUserModulePermission entity from the query.
// Returns a *NotFoundError when no SysUserModulePermission was found.
func (_q *SysUserModulePermissionQuery) First(ctx context.Context) (*SysUserModulePermission, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sysusermodulepermission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SysUserModulePermissionQuery) FirstX(ctx context.Context) *SysUserModulePermission {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SysUserModulePermission ID from the query.
// Returns a *NotFoundError when no SysUserModulePermission ID was found.
func (_q *SysUserModulePermissionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sysusermodulepermission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SysUserModulePermissionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SysUserModulePermission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SysUserModulePermission entity is found.
// Returns a *NotFoundError when no SysUserModulePermission entities are found.
func (_q *SysUserModulePermissionQuery) Only(ctx context.Context) (*SysUserModulePermission, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sysusermodulepermission.Label}
	default:
		return nil, &NotSingularError{sysusermodulepermission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SysUserModulePermissionQuery) OnlyX(ctx context.Context) *SysUserModulePermission {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SysUserModulePermission ID in the query.
// Returns a *NotSingularError when more than one SysUserModulePermission ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SysUserModulePermissionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sysusermodulepermission.Label}
	default:
		err = &NotSingularError{sysusermodulepermission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SysUserModulePermissionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SysUserModulePermissions.
func (_q *SysUserModulePermissionQuery) All(ctx context.Context) ([]*SysUserModulePermission, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SysUserModulePermission, *SysUserModulePermissionQuery]()
	return withInterceptors[[]*SysUserModulePermission](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SysUserModulePermissionQuery) AllX(ctx context.Context) []*SysUserModulePermission {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SysUserModulePermission IDs.
func (_q *SysUserModulePermissionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(sysusermodulepermission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SysUserModulePermissionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SysUserModulePermissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SysUserModulePermissionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SysUserModulePermissionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SysUserModulePermissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SysUserModulePermissionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SysUserModulePermissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SysUserModulePermissionQuery) Clone() *SysUserModulePermissionQuery {
	if _q == nil {
		return nil
	}
	return &SysUserModulePermissionQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]sysusermodulepermission.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.SysUserModulePermission{}, _q.predicates...),
		withUser:       _q.withUser.Clone(),
		withModule:     _q.withModule.Clone(),
		withPermission: _q.withPermission.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SysUserModulePermissionQuery) WithUser(opts ...func(*SysUserQuery)) *SysUserModulePermissionQuery {
	query := (&SysUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithModule tells the query-builder to eager-load the nodes that are connected to
// the "module" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SysUserModulePermissionQuery) WithModule(opts ...func(*SysModuleQuery)) *SysUserModulePermissionQuery {
	query := (&SysModuleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withModule = query
	return _q
}

// WithPermission tells the query-builder to eager-load the nodes that are connected to
// the "permission" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SysUserModulePermissionQuery) WithPermission(opts ...func(*SysPermissionQuery)) *SysUserModulePermissionQuery {
	query := (&SysPermissionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPermission = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SysUserModulePermission.Query().
//		GroupBy(sysusermodulepermission.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SysUserModulePermissionQuery) GroupBy(field string, fields ...string) *SysUserModulePermissionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SysUserModulePermissionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = sysusermodulepermission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.SysUserModulePermission.Query().
//		Select(sysusermodulepermission.FieldUserID).
//		Scan(ctx, &v)
func (_q *SysUserModulePermissionQuery) Select(fields ...string) *SysUserModulePermissionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SysUserModulePermissionSelect{SysUserModulePermissionQuery: _q}
	sbuild.label = sysusermodulepermission.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SysUserModulePermissionSelect configured with the given aggregations.
func (_q *SysUserModulePermissionQuery) Aggregate(fns ...AggregateFunc) *SysUserModulePermissionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SysUserModulePermissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !sysusermodulepermission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SysUserModulePermissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SysUserModulePermission, error) {
	var (
		nodes       = []*SysUserModulePermission{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withUser != nil,
			_q.withModule != nil,
			_q.withPermission != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SysUserModulePermission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SysUserModulePermission{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *SysUserModulePermission, e *SysUser) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withModule; query != nil {
		if err := _q.loadModule(ctx, query, nodes, nil,
			func(n *SysUserModulePermission, e *SysModule) { n.Edges.Module = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPermission; query != nil {
		if err := _q.loadPermission(ctx, query, nodes, nil,
			func(n *SysUserModulePermission, e *SysPermission) { n.Edges.Permission = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SysUserModulePermissionQuery) loadUser(ctx context.Context, query *SysUserQuery, nodes []*SysUserModulePermission, init func(*SysUserModulePermission), assign func(*SysUserModulePermission, *SysUser)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*SysUserModulePermission)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sysuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SysUserModulePermissionQuery) loadModule(ctx context.Context, query *SysModuleQuery, nodes []*SysUserModulePermission, init func(*SysUserModulePermission), assign func(*SysUserModulePermission, *SysModule)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*SysUserModulePermission)
	for i := range nodes {
		fk := nodes[i].ModuleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sysmodule.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "module_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SysUserModulePermissionQuery) loadPermission(ctx context.Context, query *SysPermissionQuery, nodes []*SysUserModulePermission, init func(*SysUserModulePermission), assign func(*SysUserModulePermission, *SysPermission)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*SysUserModulePermission)
	for i := range nodes {
		fk := nodes[i].PermissionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(syspermission.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "permission_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SysUserModulePermissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SysUserModulePermissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sysusermodulepermission.Table, sysusermodulepermission.Columns, sqlgraph.NewFieldSpec(sysusermodulepermission.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysusermodulepermission.FieldID)
		for i := range fields {
			if fields[i] != sysusermodulepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(sysusermodulepermission.FieldUserID)
		}
		if _q.withModule != nil {
			_spec.Node.AddColumnOnce(sysusermodulepermission.FieldModuleID)
		}
		if _q.withPermission != nil {
			_spec.Node.AddColumnOnce(sysusermodulepermission.FieldPermissionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SysUserModulePermissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(sysusermodulepermission.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = sysusermodulepermission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SysUserModulePermissionGroupBy is the group-by builder for SysUserModulePermission entities.
type SysUserModulePermissionGroupBy struct {
	selector
	build *SysUserModulePermissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SysUserModulePermissionGroupBy) Aggregate(fns ...AggregateFunc) *SysUserModulePermissionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SysUserModulePermissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysUserModulePermissionQuery, *SysUserModulePermissionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SysUserModulePermissionGroupBy) sqlScan(ctx context.Context, root *SysUserModulePermissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SysUserModulePermissionSelect is the builder for selecting fields of SysUserModulePermission entities.
type SysUserModulePermissionSelect struct {
	*SysUserModulePermissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SysUserModulePermissionSelect) Aggregate(fns ...AggregateFunc) *SysUserModulePermissionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SysUserModulePermissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysUserModulePermissionQuery, *SysUserModulePermissionSelect](ctx, _s.SysUserModulePermissionQuery, _s, _s.inters, v)
}

func (_s *SysUserModulePermissionSelect) sqlScan(ctx context.Context, root *SysUserModulePermissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
