// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"evalux-server/ent/uxexecutionsession"
	"evalux-server/ent/uxexecutionstep"
	"evalux-server/ent/uxmodeldecisionrecord"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UxExecutionStep is the model entity for the UxExecutionStep schema.
type UxExecutionStep struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// StepNo holds the value of the "step_no" field.
	StepNo int `json:"step_no,omitempty"`
	// ScreenDesc holds the value of the "screen_desc" field.
	ScreenDesc *string `json:"screen_desc,omitempty"`
	// ActionType holds the value of the "action_type" field.
	ActionType *string `json:"action_type,omitempty"`
	// ActionParam holds the value of the "action_param" field.
	ActionParam map[string]interface{} `json:"action_param,omitempty"`
	// DecisionSummary holds the value of the "decision_summary" field.
	DecisionSummary *string `json:"decision_summary,omitempty"`
	// ExecutionResult holds the value of the "execution_result" field.
	ExecutionResult map[string]interface{} `json:"execution_result,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UxExecutionStepQuery when eager-loading is set.
	Edges        UxExecutionStepEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UxExecutionStepEdges holds the relations/edges for other nodes in the graph.
type UxExecutionStepEdges struct {
	// Session holds the value of the session edge.
	Session *UxExecutionSession `json:"session,omitempty"`
	// Screenshots holds the value of the screenshots edge.
	Screenshots []*UxScreenshotRecord `json:"screenshots,omitempty"`
	// Decision holds the value of the decision edge.
	Decision *UxModelDecisionRecord `json:"decision,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UxExecutionStepEdges) SessionOrErr() (*UxExecutionSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: uxexecutionsession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// ScreenshotsOrErr returns the Screenshots value or an error if the edge
// was not loaded in eager-loading.
func (e UxExecutionStepEdges) ScreenshotsOrErr() ([]*UxScreenshotRecord, error) {
	if e.loadedTypes[1] {
		return e.Screenshots, nil
	}
	return nil, &NotLoadedError{edge: "screenshots"}
}

// DecisionOrErr returns the Decision value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UxExecutionStepEdges) DecisionOrErr() (*UxModelDecisionRecord, error) {
	if e.Decision != nil {
		return e.Decision, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: uxmodeldecisionrecord.Label}
	}
	return nil, &NotLoadedError{edge: "decision"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UxExecutionStep) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uxexecutionstep.FieldActionParam, uxexecutionstep.FieldExecutionResult:
			values[i] = new([]byte)
		case uxexecutionstep.FieldStepNo, uxexecutionstep.FieldRetryCount:
			values[i] = new(sql.NullInt64)
		case uxexecutionstep.FieldScreenDesc, uxexecutionstep.FieldActionType, uxexecutionstep.FieldDecisionSummary, uxexecutionstep.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case uxexecutionstep.FieldStartedAt, uxexecutionstep.FieldEndedAt:
			values[i] = new(sql.NullTime)
		case uxexecutionstep.FieldID, uxexecutionstep.FieldSessionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UxExecutionStep fields.
func (_m *UxExecutionStep) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uxexecutionstep.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case uxexecutionstep.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				_m.SessionID = *value
			}
		case uxexecutionstep.FieldStepNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field step_no", values[i])
			} else if value.Valid {
				_m.StepNo = int(value.Int64)
			}
		case uxexecutionstep.FieldScreenDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field screen_desc", values[i])
			} else if value.Valid {
				_m.ScreenDesc = new(string)
				*_m.ScreenDesc = value.String
			}
		case uxexecutionstep.FieldActionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_type", values[i])
			} else if value.Valid {
				_m.ActionType = new(string)
				*_m.ActionType = value.String
			}
		case uxexecutionstep.FieldActionParam:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field action_param", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ActionParam); err != nil {
					return fmt.Errorf("unmarshal field action_param: %w", err)
				}
			}
		case uxexecutionstep.FieldDecisionSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field decision_summary", values[i])
			} else if value.Valid {
				_m.DecisionSummary = new(string)
				*_m.DecisionSummary = value.String
			}
		case uxexecutionstep.FieldExecutionResult:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field execution_result", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExecutionResult); err != nil {
					return fmt.Errorf("unmarshal field execution_result: %w", err)
				}
			}
		case uxexecutionstep.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case uxexecutionstep.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case uxexecutionstep.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case uxexecutionstep.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = new(time.Time)
				*_m.EndedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UxExecutionStep.
// This includes values selected through modifiers, order, etc.
func (_m *UxExecutionStep) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the UxExecutionStep entity.
func (_m *UxExecutionStep) QuerySession() *UxExecutionSessionQuery {
	return NewUxExecutionStepClient(_m.config).QuerySession(_m)
}

// QueryScreenshots queries the "screenshots" edge of the UxExecutionStep entity.
func (_m *UxExecutionStep) QueryScreenshots() *UxScreenshotRecordQuery {
	return NewUxExecutionStepClient(_m.config).QueryScreenshots(_m)
}

// QueryDecision queries the "decision" edge of the UxExecutionStep entity.
func (_m *UxExecutionStep) QueryDecision() *UxModelDecisionRecordQuery {
	return NewUxExecutionStepClient(_m.config).QueryDecision(_m)
}

// Update returns a builder for updating this UxExecutionStep.
// Note that you need to call UxExecutionStep.Unwrap() before calling this method if this UxExecutionStep
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UxExecutionStep) Update() *UxExecutionStepUpdateOne {
	return NewUxExecutionStepClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UxExecutionStep entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UxExecutionStep) Unwrap() *UxExecutionStep {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UxExecutionStep is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UxExecutionStep) String() string {
	var builder strings.Builder
	builder.WriteString("UxExecutionStep(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionID))
	builder.WriteString(", ")
	builder.WriteString("step_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.StepNo))
	builder.WriteString(", ")
	if v := _m.ScreenDesc; v != nil {
		builder.WriteString("screen_desc=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ActionType; v != nil {
		builder.WriteString("action_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("action_param=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionParam))
	builder.WriteString(", ")
	if v := _m.DecisionSummary; v != nil {
		builder.WriteString("decision_summary=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("execution_result=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExecutionResult))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UxExecutionSteps is a parsable slice of UxExecutionStep.
type UxExecutionSteps []*UxExecutionStep
