// Code generated by ent, DO NOT EDIT.

package ent

import (
	"evalux-server/ent/sysuser"
	"evalux-server/ent/uxexecutionplan"
	"evalux-server/ent/uxproject"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UxExecutionPlan is the model entity for the UxExecutionPlan schema.
type UxExecutionPlan struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// PlanName holds the value of the "plan_name" field.
	PlanName string `json:"plan_name,omitempty"`
	// PlanType holds the value of the "plan_type" field.
	PlanType uxexecutionplan.PlanType `json:"plan_type,omitempty"`
	// 设备并发上限
	MaxConcurrency int `json:"max_concurrency,omitempty"`
	// 单步超时
	StepTimeoutSec int `json:"step_timeout_sec,omitempty"`
	// 单会话超时
	SessionTimeoutSec int `json:"session_timeout_sec,omitempty"`
	// 单步重试上限
	RetryLimit int `json:"retry_limit,omitempty"`
	// 提示词覆盖 prompt 表 ID
	PromptOverrideID *uuid.UUID `json:"prompt_override_id,omitempty"`
	// A/B 测试假设说明
	Hypothesis *string `json:"hypothesis,omitempty"`
	// Status holds the value of the "status" field.
	Status uxexecutionplan.Status `json:"status,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UxExecutionPlanQuery when eager-loading is set.
	Edges        UxExecutionPlanEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UxExecutionPlanEdges holds the relations/edges for other nodes in the graph.
type UxExecutionPlanEdges struct {
	// Project holds the value of the project edge.
	Project *UxProject `json:"project,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *SysUser `json:"creator,omitempty"`
	// ModelConfigs holds the value of the model_configs edge.
	ModelConfigs []*UxPlanModelConfig `json:"model_configs,omitempty"`
	// TaskBindings holds the value of the task_bindings edge.
	TaskBindings []*UxPlanTaskBinding `json:"task_bindings,omitempty"`
	// ProfileBindings holds the value of the profile_bindings edge.
	ProfileBindings []*UxPlanProfileBinding `json:"profile_bindings,omitempty"`
	// TaskQuestionnaireBindings holds the value of the task_questionnaire_bindings edge.
	TaskQuestionnaireBindings []*UxPlanTaskQuestionnaireBinding `json:"task_questionnaire_bindings,omitempty"`
	// ProfileQuestionnaireBindings holds the value of the profile_questionnaire_bindings edge.
	ProfileQuestionnaireBindings []*UxPlanProfileQuestionnaireBinding `json:"profile_questionnaire_bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UxExecutionPlanEdges) ProjectOrErr() (*UxProject, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: uxproject.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UxExecutionPlanEdges) CreatorOrErr() (*SysUser, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// ModelConfigsOrErr returns the ModelConfigs value or an error if the edge
// was not loaded in eager-loading.
func (e UxExecutionPlanEdges) ModelConfigsOrErr() ([]*UxPlanModelConfig, error) {
	if e.loadedTypes[2] {
		return e.ModelConfigs, nil
	}
	return nil, &NotLoadedError{edge: "model_configs"}
}

// TaskBindingsOrErr returns the TaskBindings value or an error if the edge
// was not loaded in eager-loading.
func (e UxExecutionPlanEdges) TaskBindingsOrErr() ([]*UxPlanTaskBinding, error) {
	if e.loadedTypes[3] {
		return e.TaskBindings, nil
	}
	return nil, &NotLoadedError{edge: "task_bindings"}
}

// ProfileBindingsOrErr returns the ProfileBindings value or an error if the edge
// was not loaded in eager-loading.
func (e UxExecutionPlanEdges) ProfileBindingsOrErr() ([]*UxPlanProfileBinding, error) {
	if e.loadedTypes[4] {
		return e.ProfileBindings, nil
	}
	return nil, &NotLoadedError{edge: "profile_bindings"}
}

// TaskQuestionnaireBindingsOrErr returns the TaskQuestionnaireBindings value or an error if the edge
// was not loaded in eager-loading.
func (e UxExecutionPlanEdges) TaskQuestionnaireBindingsOrErr() ([]*UxPlanTaskQuestionnaireBinding, error) {
	if e.loadedTypes[5] {
		return e.TaskQuestionnaireBindings, nil
	}
	return nil, &NotLoadedError{edge: "task_questionnaire_bindings"}
}

// ProfileQuestionnaireBindingsOrErr returns the ProfileQuestionnaireBindings value or an error if the edge
// was not loaded in eager-loading.
func (e UxExecutionPlanEdges) ProfileQuestionnaireBindingsOrErr() ([]*UxPlanProfileQuestionnaireBinding, error) {
	if e.loadedTypes[6] {
		return e.ProfileQuestionnaireBindings, nil
	}
	return nil, &NotLoadedError{edge: "profile_questionnaire_bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UxExecutionPlan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uxexecutionplan.FieldPromptOverrideID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case uxexecutionplan.FieldMaxConcurrency, uxexecutionplan.FieldStepTimeoutSec, uxexecutionplan.FieldSessionTimeoutSec, uxexecutionplan.FieldRetryLimit:
			values[i] = new(sql.NullInt64)
		case uxexecutionplan.FieldPlanName, uxexecutionplan.FieldPlanType, uxexecutionplan.FieldHypothesis, uxexecutionplan.FieldStatus:
			values[i] = new(sql.NullString)
		case uxexecutionplan.FieldCreatedAt, uxexecutionplan.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case uxexecutionplan.FieldID, uxexecutionplan.FieldProjectID, uxexecutionplan.FieldCreatedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UxExecutionPlan fields.
func (_m *UxExecutionPlan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uxexecutionplan.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case uxexecutionplan.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case uxexecutionplan.FieldPlanName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_name", values[i])
			} else if value.Valid {
				_m.PlanName = value.String
			}
		case uxexecutionplan.FieldPlanType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_type", values[i])
			} else if value.Valid {
				_m.PlanType = uxexecutionplan.PlanType(value.String)
			}
		case uxexecutionplan.FieldMaxConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_concurrency", values[i])
			} else if value.Valid {
				_m.MaxConcurrency = int(value.Int64)
			}
		case uxexecutionplan.FieldStepTimeoutSec:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field step_timeout_sec", values[i])
			} else if value.Valid {
				_m.StepTimeoutSec = int(value.Int64)
			}
		case uxexecutionplan.FieldSessionTimeoutSec:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_timeout_sec", values[i])
			} else if value.Valid {
				_m.SessionTimeoutSec = int(value.Int64)
			}
		case uxexecutionplan.FieldRetryLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_limit", values[i])
			} else if value.Valid {
				_m.RetryLimit = int(value.Int64)
			}
		case uxexecutionplan.FieldPromptOverrideID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_override_id", values[i])
			} else if value.Valid {
				_m.PromptOverrideID = new(uuid.UUID)
				*_m.PromptOverrideID = *value.S.(*uuid.UUID)
			}
		case uxexecutionplan.FieldHypothesis:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hypothesis", values[i])
			} else if value.Valid {
				_m.Hypothesis = new(string)
				*_m.Hypothesis = value.String
			}
		case uxexecutionplan.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = uxexecutionplan.Status(value.String)
			}
		case uxexecutionplan.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				_m.CreatedBy = *value
			}
		case uxexecutionplan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case uxexecutionplan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UxExecutionPlan.
// This includes values selected through modifiers, order, etc.
func (_m *UxExecutionPlan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the UxExecutionPlan entity.
func (_m *UxExecutionPlan) QueryProject() *UxProjectQuery {
	return NewUxExecutionPlanClient(_m.config).QueryProject(_m)
}

// QueryCreator queries the "creator" edge of the UxExecutionPlan entity.
func (_m *UxExecutionPlan) QueryCreator() *SysUserQuery {
	return NewUxExecutionPlanClient(_m.config).QueryCreator(_m)
}

// QueryModelConfigs queries the "model_configs" edge of the UxExecutionPlan entity.
func (_m *UxExecutionPlan) QueryModelConfigs() *UxPlanModelConfigQuery {
	return NewUxExecutionPlanClient(_m.config).QueryModelConfigs(_m)
}

// QueryTaskBindings queries the "task_bindings" edge of the UxExecutionPlan entity.
func (_m *UxExecutionPlan) QueryTaskBindings() *UxPlanTaskBindingQuery {
	return NewUxExecutionPlanClient(_m.config).QueryTaskBindings(_m)
}

// QueryProfileBindings queries the "profile_bindings" edge of the UxExecutionPlan entity.
func (_m *UxExecutionPlan) QueryProfileBindings() *UxPlanProfileBindingQuery {
	return NewUxExecutionPlanClient(_m.config).QueryProfileBindings(_m)
}

// QueryTaskQuestionnaireBindings queries the "task_questionnaire_bindings" edge of the UxExecutionPlan entity.
func (_m *UxExecutionPlan) QueryTaskQuestionnaireBindings() *UxPlanTaskQuestionnaireBindingQuery {
	return NewUxExecutionPlanClient(_m.config).QueryTaskQuestionnaireBindings(_m)
}

// QueryProfileQuestionnaireBindings queries the "profile_questionnaire_bindings" edge of the UxExecutionPlan entity.
func (_m *UxExecutionPlan) QueryProfileQuestionnaireBindings() *UxPlanProfileQuestionnaireBindingQuery {
	return NewUxExecutionPlanClient(_m.config).QueryProfileQuestionnaireBindings(_m)
}

// Update returns a builder for updating this UxExecutionPlan.
// Note that you need to call UxExecutionPlan.Unwrap() before calling this method if this UxExecutionPlan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UxExecutionPlan) Update() *UxExecutionPlanUpdateOne {
	return NewUxExecutionPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UxExecutionPlan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UxExecutionPlan) Unwrap() *UxExecutionPlan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UxExecutionPlan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UxExecutionPlan) String() string {
	var builder strings.Builder
	builder.WriteString("UxExecutionPlan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("plan_name=")
	builder.WriteString(_m.PlanName)
	builder.WriteString(", ")
	builder.WriteString("plan_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanType))
	builder.WriteString(", ")
	builder.WriteString("max_concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxConcurrency))
	builder.WriteString(", ")
	builder.WriteString("step_timeout_sec=")
	builder.WriteString(fmt.Sprintf("%v", _m.StepTimeoutSec))
	builder.WriteString(", ")
	builder.WriteString("session_timeout_sec=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionTimeoutSec))
	builder.WriteString(", ")
	builder.WriteString("retry_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryLimit))
	builder.WriteString(", ")
	if v := _m.PromptOverrideID; v != nil {
		builder.WriteString("prompt_override_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Hypothesis; v != nil {
		builder.WriteString("hypothesis=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UxExecutionPlans is a parsable slice of UxExecutionPlan.
type UxExecutionPlans []*UxExecutionPlan
