// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"evalux-server/ent/uxexecutionsession"
	"evalux-server/ent/uxexecutionstep"
	"evalux-server/ent/uxmodeldecisionrecord"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UxModelDecisionRecordCreate is the builder for creating a UxModelDecisionRecord entity.
type UxModelDecisionRecordCreate struct {
	config
	mutation *UxModelDecisionRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSessionID sets the "session_id" field.
func (_c *UxModelDecisionRecordCreate) SetSessionID(v uuid.UUID) *UxModelDecisionRecordCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetStepID sets the "step_id" field.
func (_c *UxModelDecisionRecordCreate) SetStepID(v uuid.UUID) *UxModelDecisionRecordCreate {
	_c.mutation.SetStepID(v)
	return _c
}

// SetRequestPayload sets the "request_payload" field.
func (_c *UxModelDecisionRecordCreate) SetRequestPayload(v map[string]interface{}) *UxModelDecisionRecordCreate {
	_c.mutation.SetRequestPayload(v)
	return _c
}

// SetResponsePayload sets the "response_payload" field.
func (_c *UxModelDecisionRecordCreate) SetResponsePayload(v map[string]interface{}) *UxModelDecisionRecordCreate {
	_c.mutation.SetResponsePayload(v)
	return _c
}

// SetActionType sets the "action_type" field.
func (_c *UxModelDecisionRecordCreate) SetActionType(v string) *UxModelDecisionRecordCreate {
	_c.mutation.SetActionType(v)
	return _c
}

// SetTaskState sets the "task_state" field.
func (_c *UxModelDecisionRecordCreate) SetTaskState(v uxmodeldecisionrecord.TaskState) *UxModelDecisionRecordCreate {
	_c.mutation.SetTaskState(v)
	return _c
}

// SetNillableTaskState sets the "task_state" field if the given value is not nil.
func (_c *UxModelDecisionRecordCreate) SetNillableTaskState(v *uxmodeldecisionrecord.TaskState) *UxModelDecisionRecordCreate {
	if v != nil {
		_c.SetTaskState(*v)
	}
	return _c
}

// SetDecisionReason sets the "decision_reason" field.
func (_c *UxModelDecisionRecordCreate) SetDecisionReason(v string) *UxModelDecisionRecordCreate {
	_c.mutation.SetDecisionReason(v)
	return _c
}

// SetNillableDecisionReason sets the "decision_reason" field if the given value is not nil.
func (_c *UxModelDecisionRecordCreate) SetNillableDecisionReason(v *string) *UxModelDecisionRecordCreate {
	if v != nil {
		_c.SetDecisionReason(*v)
	}
	return _c
}

// SetNeedContinue sets the "need_continue" field.
func (_c *UxModelDecisionRecordCreate) SetNeedContinue(v bool) *UxModelDecisionRecordCreate {
	_c.mutation.SetNeedContinue(v)
	return _c
}

// SetNillableNeedContinue sets the "need_continue" field if the given value is not nil.
func (_c *UxModelDecisionRecordCreate) SetNillableNeedContinue(v *bool) *UxModelDecisionRecordCreate {
	if v != nil {
		_c.SetNeedContinue(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UxModelDecisionRecordCreate) SetCreatedAt(v time.Time) *UxModelDecisionRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UxModelDecisionRecordCreate) SetNillableCreatedAt(v *time.Time) *UxModelDecisionRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UxModelDecisionRecordCreate) SetID(v uuid.UUID) *UxModelDecisionRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UxModelDecisionRecordCreate) SetNillableID(v *uuid.UUID) *UxModelDecisionRecordCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSession sets the "session" edge to the UxExecutionSession entity.
func (_c *UxModelDecisionRecordCreate) SetSession(v *UxExecutionSession) *UxModelDecisionRecordCreate {
	return _c.SetSessionID(v.ID)
}

// SetStep sets the "step" edge to the UxExecutionStep entity.
func (_c *UxModelDecisionRecordCreate) SetStep(v *UxExecutionStep) *UxModelDecisionRecordCreate {
	return _c.SetStepID(v.ID)
}

// Mutation returns the UxModelDecisionRecordMutation object of the builder.
func (_c *UxModelDecisionRecordCreate) Mutation() *UxModelDecisionRecordMutation {
	return _c.mutation
}

// Save creates the UxModelDecisionRecord in the database.
func (_c *UxModelDecisionRecordCreate) Save(ctx context.Context) (*UxModelDecisionRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UxModelDecisionRecordCreate) SaveX(ctx context.Context) *UxModelDecisionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UxModelDecisionRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UxModelDecisionRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UxModelDecisionRecordCreate) defaults() {
	if _, ok := _c.mutation.TaskState(); !ok {
		v := uxmodeldecisionrecord.DefaultTaskState
		_c.mutation.SetTaskState(v)
	}
	if _, ok := _c.mutation.NeedContinue(); !ok {
		v := uxmodeldecisionrecord.DefaultNeedContinue
		_c.mutation.SetNeedContinue(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := uxmodeldecisionrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := uxmodeldecisionrecord.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UxModelDecisionRecordCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "UxModelDecisionRecord.session_id"`)}
	}
	if _, ok := _c.mutation.StepID(); !ok {
		return &ValidationError{Name: "step_id", err: errors.New(`ent: missing required field "UxModelDecisionRecord.step_id"`)}
	}
	if _, ok := _c.mutation.ActionType(); !ok {
		return &ValidationError{Name: "action_type", err: errors.New(`ent: missing required field "UxModelDecisionRecord.action_type"`)}
	}
	if v, ok := _c.mutation.ActionType(); ok {
		if err := uxmodeldecisionrecord.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "UxModelDecisionRecord.action_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaskState(); !ok {
		return &ValidationError{Name: "task_state", err: errors.New(`ent: missing required field "UxModelDecisionRecord.task_state"`)}
	}
	if v, ok := _c.mutation.TaskState(); ok {
		if err := uxmodeldecisionrecord.TaskStateValidator(v); err != nil {
			return &ValidationError{Name: "task_state", err: fmt.Errorf(`ent: validator failed for field "UxModelDecisionRecord.task_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NeedContinue(); !ok {
		return &ValidationError{Name: "need_continue", err: errors.New(`ent: missing required field "UxModelDecisionRecord.need_continue"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UxModelDecisionRecord.created_at"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "UxModelDecisionRecord.session"`)}
	}
	if len(_c.mutation.StepIDs()) == 0 {
		return &ValidationError{Name: "step", err: errors.New(`ent: missing required edge "UxModelDecisionRecord.step"`)}
	}
	return nil
}

func (_c *UxModelDecisionRecordCreate) sqlSave(ctx context.Context) (*UxModelDecisionRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UxModelDecisionRecordCreate) createSpec() (*UxModelDecisionRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &UxModelDecisionRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uxmodeldecisionrecord.Table, sqlgraph.NewFieldSpec(uxmodeldecisionrecord.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RequestPayload(); ok {
		_spec.SetField(uxmodeldecisionrecord.FieldRequestPayload, field.TypeJSON, value)
		_node.RequestPayload = value
	}
	if value, ok := _c.mutation.ResponsePayload(); ok {
		_spec.SetField(uxmodeldecisionrecord.FieldResponsePayload, field.TypeJSON, value)
		_node.ResponsePayload = value
	}
	if value, ok := _c.mutation.ActionType(); ok {
		_spec.SetField(uxmodeldecisionrecord.FieldActionType, field.TypeString, value)
		_node.ActionType = value
	}
	if value, ok := _c.mutation.TaskState(); ok {
		_spec.SetField(uxmodeldecisionrecord.FieldTaskState, field.TypeEnum, value)
		_node.TaskState = value
	}
	if value, ok := _c.mutation.DecisionReason(); ok {
		_spec.SetField(uxmodeldecisionrecord.FieldDecisionReason, field.TypeString, value)
		_node.DecisionReason = &value
	}
	if value, ok := _c.mutation.NeedContinue(); ok {
		_spec.SetField(uxmodeldecisionrecord.FieldNeedContinue, field.TypeBool, value)
		_node.NeedContinue = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(uxmodeldecisionrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uxmodeldecisionrecord.SessionTable,
			Columns: []string{uxmodeldecisionrecord.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxexecutionsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   uxmodeldecisionrecord.StepTable,
			Columns: []string{uxmodeldecisionrecord.StepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxexecutionstep.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StepID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UxModelDecisionRecord.Create().
//		SetSessionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UxModelDecisionRecordUpsert) {
//			SetSessionID(v+v).
//		}).
//		Exec(ctx)
func (_c *UxModelDecisionRecordCreate) OnConflict(opts ...sql.ConflictOption) *UxModelDecisionRecordUpsertOne {
	_c.conflict = opts
	return &UxModelDecisionRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UxModelDecisionRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UxModelDecisionRecordCreate) OnConflictColumns(columns ...string) *UxModelDecisionRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UxModelDecisionRecordUpsertOne{
		create: _c,
	}
}

type (
	// UxModelDecisionRecordUpsertOne is the builder for "upsert"-ing
	//  one UxModelDecisionRecord node.
	UxModelDecisionRecordUpsertOne struct {
		create *UxModelDecisionRecordCreate
	}

	// UxModelDecisionRecordUpsert is the "OnConflict" setter.
	UxModelDecisionRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetSessionID sets the "session_id" field.
func (u *UxModelDecisionRecordUpsert) SetSessionID(v uuid.UUID) *UxModelDecisionRecordUpsert {
	u.Set(uxmodeldecisionrecord.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsert) UpdateSessionID() *UxModelDecisionRecordUpsert {
	u.SetExcluded(uxmodeldecisionrecord.FieldSessionID)
	return u
}

// SetStepID sets the "step_id" field.
func (u *UxModelDecisionRecordUpsert) SetStepID(v uuid.UUID) *UxModelDecisionRecordUpsert {
	u.Set(uxmodeldecisionrecord.FieldStepID, v)
	return u
}

// UpdateStepID sets the "step_id" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsert) UpdateStepID() *UxModelDecisionRecordUpsert {
	u.SetExcluded(uxmodeldecisionrecord.FieldStepID)
	return u
}

// SetRequestPayload sets the "request_payload" field.
func (u *UxModelDecisionRecordUpsert) SetRequestPayload(v map[string]interface{}) *UxModelDecisionRecordUpsert {
	u.Set(uxmodeldecisionrecord.FieldRequestPayload, v)
	return u
}

// UpdateRequestPayload sets the "request_payload" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsert) UpdateRequestPayload() *UxModelDecisionRecordUpsert {
	u.SetExcluded(uxmodeldecisionrecord.FieldRequestPayload)
	return u
}

// ClearRequestPayload clears the value of the "request_payload" field.
func (u *UxModelDecisionRecordUpsert) ClearRequestPayload() *UxModelDecisionRecordUpsert {
	u.SetNull(uxmodeldecisionrecord.FieldRequestPayload)
	return u
}

// SetResponsePayload sets the "response_payload" field.
func (u *UxModelDecisionRecordUpsert) SetResponsePayload(v map[string]interface{}) *UxModelDecisionRecordUpsert {
	u.Set(uxmodeldecisionrecord.FieldResponsePayload, v)
	return u
}

// UpdateResponsePayload sets the "response_payload" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsert) UpdateResponsePayload() *UxModelDecisionRecordUpsert {
	u.SetExcluded(uxmodeldecisionrecord.FieldResponsePayload)
	return u
}

// ClearResponsePayload clears the value of the "response_payload" field.
func (u *UxModelDecisionRecordUpsert) ClearResponsePayload() *UxModelDecisionRecordUpsert {
	u.SetNull(uxmodeldecisionrecord.FieldResponsePayload)
	return u
}

// SetActionType sets the "action_type" field.
func (u *UxModelDecisionRecordUpsert) SetActionType(v string) *UxModelDecisionRecordUpsert {
	u.Set(uxmodeldecisionrecord.FieldActionType, v)
	return u
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsert) UpdateActionType() *UxModelDecisionRecordUpsert {
	u.SetExcluded(uxmodeldecisionrecord.FieldActionType)
	return u
}

// SetTaskState sets the "task_state" field.
func (u *UxModelDecisionRecordUpsert) SetTaskState(v uxmodeldecisionrecord.TaskState) *UxModelDecisionRecordUpsert {
	u.Set(uxmodeldecisionrecord.FieldTaskState, v)
	return u
}

// UpdateTaskState sets the "task_state" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsert) UpdateTaskState() *UxModelDecisionRecordUpsert {
	u.SetExcluded(uxmodeldecisionrecord.FieldTaskState)
	return u
}

// SetDecisionReason sets the "decision_reason" field.
func (u *UxModelDecisionRecordUpsert) SetDecisionReason(v string) *UxModelDecisionRecordUpsert {
	u.Set(uxmodeldecisionrecord.FieldDecisionReason, v)
	return u
}

// UpdateDecisionReason sets the "decision_reason" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsert) UpdateDecisionReason() *UxModelDecisionRecordUpsert {
	u.SetExcluded(uxmodeldecisionrecord.FieldDecisionReason)
	return u
}

// ClearDecisionReason clears the value of the "decision_reason" field.
func (u *UxModelDecisionRecordUpsert) ClearDecisionReason() *UxModelDecisionRecordUpsert {
	u.SetNull(uxmodeldecisionrecord.FieldDecisionReason)
	return u
}

// SetNeedContinue sets the "need_continue" field.
func (u *UxModelDecisionRecordUpsert) SetNeedContinue(v bool) *UxModelDecisionRecordUpsert {
	u.Set(uxmodeldecisionrecord.FieldNeedContinue, v)
	return u
}

// UpdateNeedContinue sets the "need_continue" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsert) UpdateNeedContinue() *UxModelDecisionRecordUpsert {
	u.SetExcluded(uxmodeldecisionrecord.FieldNeedContinue)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UxModelDecisionRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(uxmodeldecisionrecord.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UxModelDecisionRecordUpsertOne) UpdateNewValues() *UxModelDecisionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(uxmodeldecisionrecord.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(uxmodeldecisionrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UxModelDecisionRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UxModelDecisionRecordUpsertOne) Ignore() *UxModelDecisionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UxModelDecisionRecordUpsertOne) DoNothing() *UxModelDecisionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UxModelDecisionRecordCreate.OnConflict
// documentation for more info.
func (u *UxModelDecisionRecordUpsertOne) Update(set func(*UxModelDecisionRecordUpsert)) *UxModelDecisionRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UxModelDecisionRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetSessionID sets the "session_id" field.
func (u *UxModelDecisionRecordUpsertOne) SetSessionID(v uuid.UUID) *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertOne) UpdateSessionID() *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateSessionID()
	})
}

// SetStepID sets the "step_id" field.
func (u *UxModelDecisionRecordUpsertOne) SetStepID(v uuid.UUID) *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetStepID(v)
	})
}

// UpdateStepID sets the "step_id" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertOne) UpdateStepID() *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateStepID()
	})
}

// SetRequestPayload sets the "request_payload" field.
func (u *UxModelDecisionRecordUpsertOne) SetRequestPayload(v map[string]interface{}) *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetRequestPayload(v)
	})
}

// UpdateRequestPayload sets the "request_payload" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertOne) UpdateRequestPayload() *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateRequestPayload()
	})
}

// ClearRequestPayload clears the value of the "request_payload" field.
func (u *UxModelDecisionRecordUpsertOne) ClearRequestPayload() *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.ClearRequestPayload()
	})
}

// SetResponsePayload sets the "response_payload" field.
func (u *UxModelDecisionRecordUpsertOne) SetResponsePayload(v map[string]interface{}) *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetResponsePayload(v)
	})
}

// UpdateResponsePayload sets the "response_payload" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertOne) UpdateResponsePayload() *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateResponsePayload()
	})
}

// ClearResponsePayload clears the value of the "response_payload" field.
func (u *UxModelDecisionRecordUpsertOne) ClearResponsePayload() *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.ClearResponsePayload()
	})
}

// SetActionType sets the "action_type" field.
func (u *UxModelDecisionRecordUpsertOne) SetActionType(v string) *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetActionType(v)
	})
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertOne) UpdateActionType() *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateActionType()
	})
}

// SetTaskState sets the "task_state" field.
func (u *UxModelDecisionRecordUpsertOne) SetTaskState(v uxmodeldecisionrecord.TaskState) *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetTaskState(v)
	})
}

// UpdateTaskState sets the "task_state" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertOne) UpdateTaskState() *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateTaskState()
	})
}

// SetDecisionReason sets the "decision_reason" field.
func (u *UxModelDecisionRecordUpsertOne) SetDecisionReason(v string) *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetDecisionReason(v)
	})
}

// UpdateDecisionReason sets the "decision_reason" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertOne) UpdateDecisionReason() *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateDecisionReason()
	})
}

// ClearDecisionReason clears the value of the "decision_reason" field.
func (u *UxModelDecisionRecordUpsertOne) ClearDecisionReason() *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.ClearDecisionReason()
	})
}

// SetNeedContinue sets the "need_continue" field.
func (u *UxModelDecisionRecordUpsertOne) SetNeedContinue(v bool) *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetNeedContinue(v)
	})
}

// UpdateNeedContinue sets the "need_continue" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertOne) UpdateNeedContinue() *UxModelDecisionRecordUpsertOne {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateNeedContinue()
	})
}

// Exec executes the query.
func (u *UxModelDecisionRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UxModelDecisionRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UxModelDecisionRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UxModelDecisionRecordUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UxModelDecisionRecordUpsertOne.ID is not supported by MySQL driver. Use UxModelDecisionRecordUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UxModelDecisionRecordUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UxModelDecisionRecordCreateBulk is the builder for creating many UxModelDecisionRecord entities in bulk.
type UxModelDecisionRecordCreateBulk struct {
	config
	err      error
	builders []*UxModelDecisionRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the UxModelDecisionRecord entities in the database.
func (_c *UxModelDecisionRecordCreateBulk) Save(ctx context.Context) ([]*UxModelDecisionRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UxModelDecisionRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UxModelDecisionRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UxModelDecisionRecordCreateBulk) SaveX(ctx context.Context) []*UxModelDecisionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UxModelDecisionRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UxModelDecisionRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UxModelDecisionRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UxModelDecisionRecordUpsert) {
//			SetSessionID(v+v).
//		}).
//		Exec(ctx)
func (_c *UxModelDecisionRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *UxModelDecisionRecordUpsertBulk {
	_c.conflict = opts
	return &UxModelDecisionRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UxModelDecisionRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UxModelDecisionRecordCreateBulk) OnConflictColumns(columns ...string) *UxModelDecisionRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UxModelDecisionRecordUpsertBulk{
		create: _c,
	}
}

// UxModelDecisionRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of UxModelDecisionRecord nodes.
type UxModelDecisionRecordUpsertBulk struct {
	create *UxModelDecisionRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UxModelDecisionRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(uxmodeldecisionrecord.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UxModelDecisionRecordUpsertBulk) UpdateNewValues() *UxModelDecisionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(uxmodeldecisionrecord.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(uxmodeldecisionrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UxModelDecisionRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UxModelDecisionRecordUpsertBulk) Ignore() *UxModelDecisionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UxModelDecisionRecordUpsertBulk) DoNothing() *UxModelDecisionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UxModelDecisionRecordCreateBulk.OnConflict
// documentation for more info.
func (u *UxModelDecisionRecordUpsertBulk) Update(set func(*UxModelDecisionRecordUpsert)) *UxModelDecisionRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UxModelDecisionRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetSessionID sets the "session_id" field.
func (u *UxModelDecisionRecordUpsertBulk) SetSessionID(v uuid.UUID) *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertBulk) UpdateSessionID() *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateSessionID()
	})
}

// SetStepID sets the "step_id" field.
func (u *UxModelDecisionRecordUpsertBulk) SetStepID(v uuid.UUID) *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetStepID(v)
	})
}

// UpdateStepID sets the "step_id" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertBulk) UpdateStepID() *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateStepID()
	})
}

// SetRequestPayload sets the "request_payload" field.
func (u *UxModelDecisionRecordUpsertBulk) SetRequestPayload(v map[string]interface{}) *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetRequestPayload(v)
	})
}

// UpdateRequestPayload sets the "request_payload" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertBulk) UpdateRequestPayload() *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateRequestPayload()
	})
}

// ClearRequestPayload clears the value of the "request_payload" field.
func (u *UxModelDecisionRecordUpsertBulk) ClearRequestPayload() *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.ClearRequestPayload()
	})
}

// SetResponsePayload sets the "response_payload" field.
func (u *UxModelDecisionRecordUpsertBulk) SetResponsePayload(v map[string]interface{}) *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetResponsePayload(v)
	})
}

// UpdateResponsePayload sets the "response_payload" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertBulk) UpdateResponsePayload() *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateResponsePayload()
	})
}

// ClearResponsePayload clears the value of the "response_payload" field.
func (u *UxModelDecisionRecordUpsertBulk) ClearResponsePayload() *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.ClearResponsePayload()
	})
}

// SetActionType sets the "action_type" field.
func (u *UxModelDecisionRecordUpsertBulk) SetActionType(v string) *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetActionType(v)
	})
}

// UpdateActionType sets the "action_type" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertBulk) UpdateActionType() *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateActionType()
	})
}

// SetTaskState sets the "task_state" field.
func (u *UxModelDecisionRecordUpsertBulk) SetTaskState(v uxmodeldecisionrecord.TaskState) *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetTaskState(v)
	})
}

// UpdateTaskState sets the "task_state" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertBulk) UpdateTaskState() *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateTaskState()
	})
}

// SetDecisionReason sets the "decision_reason" field.
func (u *UxModelDecisionRecordUpsertBulk) SetDecisionReason(v string) *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetDecisionReason(v)
	})
}

// UpdateDecisionReason sets the "decision_reason" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertBulk) UpdateDecisionReason() *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateDecisionReason()
	})
}

// ClearDecisionReason clears the value of the "decision_reason" field.
func (u *UxModelDecisionRecordUpsertBulk) ClearDecisionReason() *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.ClearDecisionReason()
	})
}

// SetNeedContinue sets the "need_continue" field.
func (u *UxModelDecisionRecordUpsertBulk) SetNeedContinue(v bool) *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.SetNeedContinue(v)
	})
}

// UpdateNeedContinue sets the "need_continue" field to the value that was provided on create.
func (u *UxModelDecisionRecordUpsertBulk) UpdateNeedContinue() *UxModelDecisionRecordUpsertBulk {
	return u.Update(func(s *UxModelDecisionRecordUpsert) {
		s.UpdateNeedContinue()
	})
}

// Exec executes the query.
func (u *UxModelDecisionRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UxModelDecisionRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UxModelDecisionRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UxModelDecisionRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
