// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"evalux-server/ent/predicate"
	"evalux-server/ent/uxorgmember"
	"evalux-server/ent/uxorgrole"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UxOrgRoleUpdate is the builder for updating UxOrgRole entities.
type UxOrgRoleUpdate struct {
	config
	hooks    []Hook
	mutation *UxOrgRoleMutation
}

// Where appends a list predicates to the UxOrgRoleUpdate builder.
func (_u *UxOrgRoleUpdate) Where(ps ...predicate.UxOrgRole) *UxOrgRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoleCode sets the "role_code" field.
func (_u *UxOrgRoleUpdate) SetRoleCode(v string) *UxOrgRoleUpdate {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *UxOrgRoleUpdate) SetNillableRoleCode(v *string) *UxOrgRoleUpdate {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// SetRoleName sets the "role_name" field.
func (_u *UxOrgRoleUpdate) SetRoleName(v string) *UxOrgRoleUpdate {
	_u.mutation.SetRoleName(v)
	return _u
}

// SetNillableRoleName sets the "role_name" field if the given value is not nil.
func (_u *UxOrgRoleUpdate) SetNillableRoleName(v *string) *UxOrgRoleUpdate {
	if v != nil {
		_u.SetRoleName(*v)
	}
	return _u
}

// SetPermissionCodes sets the "permission_codes" field.
func (_u *UxOrgRoleUpdate) SetPermissionCodes(v []string) *UxOrgRoleUpdate {
	_u.mutation.SetPermissionCodes(v)
	return _u
}

// AppendPermissionCodes appends value to the "permission_codes" field.
func (_u *UxOrgRoleUpdate) AppendPermissionCodes(v []string) *UxOrgRoleUpdate {
	_u.mutation.AppendPermissionCodes(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *UxOrgRoleUpdate) SetDescription(v string) *UxOrgRoleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UxOrgRoleUpdate) SetNillableDescription(v *string) *UxOrgRoleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *UxOrgRoleUpdate) ClearDescription() *UxOrgRoleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// AddMemberIDs adds the "members" edge to the UxOrgMember entity by IDs.
func (_u *UxOrgRoleUpdate) AddMemberIDs(ids ...uuid.UUID) *UxOrgRoleUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the UxOrgMember entity.
func (_u *UxOrgRoleUpdate) AddMembers(v ...*UxOrgMember) *UxOrgRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the UxOrgRoleMutation object of the builder.
func (_u *UxOrgRoleUpdate) Mutation() *UxOrgRoleMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the UxOrgMember entity.
func (_u *UxOrgRoleUpdate) ClearMembers() *UxOrgRoleUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to UxOrgMember entities by IDs.
func (_u *UxOrgRoleUpdate) RemoveMemberIDs(ids ...uuid.UUID) *UxOrgRoleUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to UxOrgMember entities.
func (_u *UxOrgRoleUpdate) RemoveMembers(v ...*UxOrgMember) *UxOrgRoleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UxOrgRoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UxOrgRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UxOrgRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UxOrgRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UxOrgRoleUpdate) check() error {
	if v, ok := _u.mutation.RoleCode(); ok {
		if err := uxorgrole.RoleCodeValidator(v); err != nil {
			return &ValidationError{Name: "role_code", err: fmt.Errorf(`ent: validator failed for field "UxOrgRole.role_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleName(); ok {
		if err := uxorgrole.RoleNameValidator(v); err != nil {
			return &ValidationError{Name: "role_name", err: fmt.Errorf(`ent: validator failed for field "UxOrgRole.role_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UxOrgRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uxorgrole.Table, uxorgrole.Columns, sqlgraph.NewFieldSpec(uxorgrole.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(uxorgrole.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoleName(); ok {
		_spec.SetField(uxorgrole.FieldRoleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionCodes(); ok {
		_spec.SetField(uxorgrole.FieldPermissionCodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPermissionCodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, uxorgrole.FieldPermissionCodes, value)
		})
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(uxorgrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(uxorgrole.FieldDescription, field.TypeString)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   uxorgrole.MembersTable,
			Columns: []string{uxorgrole.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxorgmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   uxorgrole.MembersTable,
			Columns: []string{uxorgrole.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxorgmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   uxorgrole.MembersTable,
			Columns: []string{uxorgrole.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxorgmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uxorgrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UxOrgRoleUpdateOne is the builder for updating a single UxOrgRole entity.
type UxOrgRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UxOrgRoleMutation
}

// SetRoleCode sets the "role_code" field.
func (_u *UxOrgRoleUpdateOne) SetRoleCode(v string) *UxOrgRoleUpdateOne {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *UxOrgRoleUpdateOne) SetNillableRoleCode(v *string) *UxOrgRoleUpdateOne {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// SetRoleName sets the "role_name" field.
func (_u *UxOrgRoleUpdateOne) SetRoleName(v string) *UxOrgRoleUpdateOne {
	_u.mutation.SetRoleName(v)
	return _u
}

// SetNillableRoleName sets the "role_name" field if the given value is not nil.
func (_u *UxOrgRoleUpdateOne) SetNillableRoleName(v *string) *UxOrgRoleUpdateOne {
	if v != nil {
		_u.SetRoleName(*v)
	}
	return _u
}

// SetPermissionCodes sets the "permission_codes" field.
func (_u *UxOrgRoleUpdateOne) SetPermissionCodes(v []string) *UxOrgRoleUpdateOne {
	_u.mutation.SetPermissionCodes(v)
	return _u
}

// AppendPermissionCodes appends value to the "permission_codes" field.
func (_u *UxOrgRoleUpdateOne) AppendPermissionCodes(v []string) *UxOrgRoleUpdateOne {
	_u.mutation.AppendPermissionCodes(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *UxOrgRoleUpdateOne) SetDescription(v string) *UxOrgRoleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UxOrgRoleUpdateOne) SetNillableDescription(v *string) *UxOrgRoleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *UxOrgRoleUpdateOne) ClearDescription() *UxOrgRoleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// AddMemberIDs adds the "members" edge to the UxOrgMember entity by IDs.
func (_u *UxOrgRoleUpdateOne) AddMemberIDs(ids ...uuid.UUID) *UxOrgRoleUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the UxOrgMember entity.
func (_u *UxOrgRoleUpdateOne) AddMembers(v ...*UxOrgMember) *UxOrgRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the UxOrgRoleMutation object of the builder.
func (_u *UxOrgRoleUpdateOne) Mutation() *UxOrgRoleMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the UxOrgMember entity.
func (_u *UxOrgRoleUpdateOne) ClearMembers() *UxOrgRoleUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to UxOrgMember entities by IDs.
func (_u *UxOrgRoleUpdateOne) RemoveMemberIDs(ids ...uuid.UUID) *UxOrgRoleUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to UxOrgMember entities.
func (_u *UxOrgRoleUpdateOne) RemoveMembers(v ...*UxOrgMember) *UxOrgRoleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Where appends a list predicates to the UxOrgRoleUpdate builder.
func (_u *UxOrgRoleUpdateOne) Where(ps ...predicate.UxOrgRole) *UxOrgRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UxOrgRoleUpdateOne) Select(field string, fields ...string) *UxOrgRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UxOrgRole entity.
func (_u *UxOrgRoleUpdateOne) Save(ctx context.Context) (*UxOrgRole, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UxOrgRoleUpdateOne) SaveX(ctx context.Context) *UxOrgRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UxOrgRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UxOrgRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UxOrgRoleUpdateOne) check() error {
	if v, ok := _u.mutation.RoleCode(); ok {
		if err := uxorgrole.RoleCodeValidator(v); err != nil {
			return &ValidationError{Name: "role_code", err: fmt.Errorf(`ent: validator failed for field "UxOrgRole.role_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleName(); ok {
		if err := uxorgrole.RoleNameValidator(v); err != nil {
			return &ValidationError{Name: "role_name", err: fmt.Errorf(`ent: validator failed for field "UxOrgRole.role_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UxOrgRoleUpdateOne) sqlSave(ctx context.Context) (_node *UxOrgRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uxorgrole.Table, uxorgrole.Columns, sqlgraph.NewFieldSpec(uxorgrole.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UxOrgRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uxorgrole.FieldID)
		for _, f := range fields {
			if !uxorgrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != uxorgrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(uxorgrole.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoleName(); ok {
		_spec.SetField(uxorgrole.FieldRoleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionCodes(); ok {
		_spec.SetField(uxorgrole.FieldPermissionCodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPermissionCodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, uxorgrole.FieldPermissionCodes, value)
		})
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(uxorgrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(uxorgrole.FieldDescription, field.TypeString)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   uxorgrole.MembersTable,
			Columns: []string{uxorgrole.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxorgmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   uxorgrole.MembersTable,
			Columns: []string{uxorgrole.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxorgmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   uxorgrole.MembersTable,
			Columns: []string{uxorgrole.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxorgmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UxOrgRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uxorgrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
