// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"evalux-server/ent/sysuser"
	"evalux-server/ent/uxorg"
	"evalux-server/ent/uxorgmember"
	"evalux-server/ent/uxorgrole"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UxOrgMemberCreate is the builder for creating a UxOrgMember entity.
type UxOrgMemberCreate struct {
	config
	mutation *UxOrgMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrgID sets the "org_id" field.
func (_c *UxOrgMemberCreate) SetOrgID(v uuid.UUID) *UxOrgMemberCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UxOrgMemberCreate) SetUserID(v uuid.UUID) *UxOrgMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetOrgRoleID sets the "org_role_id" field.
func (_c *UxOrgMemberCreate) SetOrgRoleID(v uuid.UUID) *UxOrgMemberCreate {
	_c.mutation.SetOrgRoleID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UxOrgMemberCreate) SetCreatedAt(v time.Time) *UxOrgMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UxOrgMemberCreate) SetNillableCreatedAt(v *time.Time) *UxOrgMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UxOrgMemberCreate) SetID(v uuid.UUID) *UxOrgMemberCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UxOrgMemberCreate) SetNillableID(v *uuid.UUID) *UxOrgMemberCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrg sets the "org" edge to the UxOrg entity.
func (_c *UxOrgMemberCreate) SetOrg(v *UxOrg) *UxOrgMemberCreate {
	return _c.SetOrgID(v.ID)
}

// SetUser sets the "user" edge to the SysUser entity.
func (_c *UxOrgMemberCreate) SetUser(v *SysUser) *UxOrgMemberCreate {
	return _c.SetUserID(v.ID)
}

// SetRoleID sets the "role" edge to the UxOrgRole entity by ID.
func (_c *UxOrgMemberCreate) SetRoleID(id uuid.UUID) *UxOrgMemberCreate {
	_c.mutation.SetRoleID(id)
	return _c
}

// SetRole sets the "role" edge to the UxOrgRole entity.
func (_c *UxOrgMemberCreate) SetRole(v *UxOrgRole) *UxOrgMemberCreate {
	return _c.SetRoleID(v.ID)
}

// Mutation returns the UxOrgMemberMutation object of the builder.
func (_c *UxOrgMemberCreate) Mutation() *UxOrgMemberMutation {
	return _c.mutation
}

// Save creates the UxOrgMember in the database.
func (_c *UxOrgMemberCreate) Save(ctx context.Context) (*UxOrgMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UxOrgMemberCreate) SaveX(ctx context.Context) *UxOrgMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UxOrgMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UxOrgMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UxOrgMemberCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := uxorgmember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := uxorgmember.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UxOrgMemberCreate) check() error {
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`ent: missing required field "UxOrgMember.org_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UxOrgMember.user_id"`)}
	}
	if _, ok := _c.mutation.OrgRoleID(); !ok {
		return &ValidationError{Name: "org_role_id", err: errors.New(`ent: missing required field "UxOrgMember.org_role_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UxOrgMember.created_at"`)}
	}
	if len(_c.mutation.OrgIDs()) == 0 {
		return &ValidationError{Name: "org", err: errors.New(`ent: missing required edge "UxOrgMember.org"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UxOrgMember.user"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "UxOrgMember.role"`)}
	}
	return nil
}

func (_c *UxOrgMemberCreate) sqlSave(ctx context.Context) (*UxOrgMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UxOrgMemberCreate) createSpec() (*UxOrgMember, *sqlgraph.CreateSpec) {
	var (
		_node = &UxOrgMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uxorgmember.Table, sqlgraph.NewFieldSpec(uxorgmember.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(uxorgmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OrgIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uxorgmember.OrgTable,
			Columns: []string{uxorgmember.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxorg.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrgID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uxorgmember.UserTable,
			Columns: []string{uxorgmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uxorgmember.RoleTable,
			Columns: []string{uxorgmember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxorgrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrgRoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UxOrgMember.Create().
//		SetOrgID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UxOrgMemberUpsert) {
//			SetOrgID(v+v).
//		}).
//		Exec(ctx)
func (_c *UxOrgMemberCreate) OnConflict(opts ...sql.ConflictOption) *UxOrgMemberUpsertOne {
	_c.conflict = opts
	return &UxOrgMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UxOrgMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UxOrgMemberCreate) OnConflictColumns(columns ...string) *UxOrgMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UxOrgMemberUpsertOne{
		create: _c,
	}
}

type (
	// UxOrgMemberUpsertOne is the builder for "upsert"-ing
	//  one UxOrgMember node.
	UxOrgMemberUpsertOne struct {
		create *UxOrgMemberCreate
	}

	// UxOrgMemberUpsert is the "OnConflict" setter.
	UxOrgMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrgID sets the "org_id" field.
func (u *UxOrgMemberUpsert) SetOrgID(v uuid.UUID) *UxOrgMemberUpsert {
	u.Set(uxorgmember.FieldOrgID, v)
	return u
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *UxOrgMemberUpsert) UpdateOrgID() *UxOrgMemberUpsert {
	u.SetExcluded(uxorgmember.FieldOrgID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UxOrgMemberUpsert) SetUserID(v uuid.UUID) *UxOrgMemberUpsert {
	u.Set(uxorgmember.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UxOrgMemberUpsert) UpdateUserID() *UxOrgMemberUpsert {
	u.SetExcluded(uxorgmember.FieldUserID)
	return u
}

// SetOrgRoleID sets the "org_role_id" field.
func (u *UxOrgMemberUpsert) SetOrgRoleID(v uuid.UUID) *UxOrgMemberUpsert {
	u.Set(uxorgmember.FieldOrgRoleID, v)
	return u
}

// UpdateOrgRoleID sets the "org_role_id" field to the value that was provided on create.
func (u *UxOrgMemberUpsert) UpdateOrgRoleID() *UxOrgMemberUpsert {
	u.SetExcluded(uxorgmember.FieldOrgRoleID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UxOrgMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(uxorgmember.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UxOrgMemberUpsertOne) UpdateNewValues() *UxOrgMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(uxorgmember.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(uxorgmember.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UxOrgMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UxOrgMemberUpsertOne) Ignore() *UxOrgMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UxOrgMemberUpsertOne) DoNothing() *UxOrgMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UxOrgMemberCreate.OnConflict
// documentation for more info.
func (u *UxOrgMemberUpsertOne) Update(set func(*UxOrgMemberUpsert)) *UxOrgMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UxOrgMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrgID sets the "org_id" field.
func (u *UxOrgMemberUpsertOne) SetOrgID(v uuid.UUID) *UxOrgMemberUpsertOne {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.SetOrgID(v)
	})
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *UxOrgMemberUpsertOne) UpdateOrgID() *UxOrgMemberUpsertOne {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.UpdateOrgID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UxOrgMemberUpsertOne) SetUserID(v uuid.UUID) *UxOrgMemberUpsertOne {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UxOrgMemberUpsertOne) UpdateUserID() *UxOrgMemberUpsertOne {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetOrgRoleID sets the "org_role_id" field.
func (u *UxOrgMemberUpsertOne) SetOrgRoleID(v uuid.UUID) *UxOrgMemberUpsertOne {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.SetOrgRoleID(v)
	})
}

// UpdateOrgRoleID sets the "org_role_id" field to the value that was provided on create.
func (u *UxOrgMemberUpsertOne) UpdateOrgRoleID() *UxOrgMemberUpsertOne {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.UpdateOrgRoleID()
	})
}

// Exec executes the query.
func (u *UxOrgMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UxOrgMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UxOrgMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UxOrgMemberUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UxOrgMemberUpsertOne.ID is not supported by MySQL driver. Use UxOrgMemberUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UxOrgMemberUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UxOrgMemberCreateBulk is the builder for creating many UxOrgMember entities in bulk.
type UxOrgMemberCreateBulk struct {
	config
	err      error
	builders []*UxOrgMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the UxOrgMember entities in the database.
func (_c *UxOrgMemberCreateBulk) Save(ctx context.Context) ([]*UxOrgMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UxOrgMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UxOrgMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UxOrgMemberCreateBulk) SaveX(ctx context.Context) []*UxOrgMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UxOrgMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UxOrgMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UxOrgMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UxOrgMemberUpsert) {
//			SetOrgID(v+v).
//		}).
//		Exec(ctx)
func (_c *UxOrgMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *UxOrgMemberUpsertBulk {
	_c.conflict = opts
	return &UxOrgMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UxOrgMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UxOrgMemberCreateBulk) OnConflictColumns(columns ...string) *UxOrgMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UxOrgMemberUpsertBulk{
		create: _c,
	}
}

// UxOrgMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of UxOrgMember nodes.
type UxOrgMemberUpsertBulk struct {
	create *UxOrgMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UxOrgMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(uxorgmember.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UxOrgMemberUpsertBulk) UpdateNewValues() *UxOrgMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(uxorgmember.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(uxorgmember.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UxOrgMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UxOrgMemberUpsertBulk) Ignore() *UxOrgMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UxOrgMemberUpsertBulk) DoNothing() *UxOrgMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UxOrgMemberCreateBulk.OnConflict
// documentation for more info.
func (u *UxOrgMemberUpsertBulk) Update(set func(*UxOrgMemberUpsert)) *UxOrgMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UxOrgMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrgID sets the "org_id" field.
func (u *UxOrgMemberUpsertBulk) SetOrgID(v uuid.UUID) *UxOrgMemberUpsertBulk {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.SetOrgID(v)
	})
}

// UpdateOrgID sets the "org_id" field to the value that was provided on create.
func (u *UxOrgMemberUpsertBulk) UpdateOrgID() *UxOrgMemberUpsertBulk {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.UpdateOrgID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UxOrgMemberUpsertBulk) SetUserID(v uuid.UUID) *UxOrgMemberUpsertBulk {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UxOrgMemberUpsertBulk) UpdateUserID() *UxOrgMemberUpsertBulk {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetOrgRoleID sets the "org_role_id" field.
func (u *UxOrgMemberUpsertBulk) SetOrgRoleID(v uuid.UUID) *UxOrgMemberUpsertBulk {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.SetOrgRoleID(v)
	})
}

// UpdateOrgRoleID sets the "org_role_id" field to the value that was provided on create.
func (u *UxOrgMemberUpsertBulk) UpdateOrgRoleID() *UxOrgMemberUpsertBulk {
	return u.Update(func(s *UxOrgMemberUpsert) {
		s.UpdateOrgRoleID()
	})
}

// Exec executes the query.
func (u *UxOrgMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UxOrgMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UxOrgMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UxOrgMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
