// Code generated by ent, DO NOT EDIT.

package ent

import (
	"evalux-server/ent/uxexecutionplan"
	"evalux-server/ent/uxplanprofilebinding"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UxPlanProfileBinding is the model entity for the UxPlanProfileBinding schema.
type UxPlanProfileBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID uuid.UUID `json:"plan_id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID uuid.UUID `json:"profile_id,omitempty"`
	// ExecutionOrder holds the value of the "execution_order" field.
	ExecutionOrder int `json:"execution_order,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UxPlanProfileBindingQuery when eager-loading is set.
	Edges        UxPlanProfileBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UxPlanProfileBindingEdges holds the relations/edges for other nodes in the graph.
type UxPlanProfileBindingEdges struct {
	// Plan holds the value of the plan edge.
	Plan *UxExecutionPlan `json:"plan,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UxPlanProfileBindingEdges) PlanOrErr() (*UxExecutionPlan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: uxexecutionplan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UxPlanProfileBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uxplanprofilebinding.FieldEnabled:
			values[i] = new(sql.NullBool)
		case uxplanprofilebinding.FieldExecutionOrder:
			values[i] = new(sql.NullInt64)
		case uxplanprofilebinding.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case uxplanprofilebinding.FieldID, uxplanprofilebinding.FieldPlanID, uxplanprofilebinding.FieldProfileID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UxPlanProfileBinding fields.
func (_m *UxPlanProfileBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uxplanprofilebinding.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case uxplanprofilebinding.FieldPlanID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value != nil {
				_m.PlanID = *value
			}
		case uxplanprofilebinding.FieldProfileID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value != nil {
				_m.ProfileID = *value
			}
		case uxplanprofilebinding.FieldExecutionOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field execution_order", values[i])
			} else if value.Valid {
				_m.ExecutionOrder = int(value.Int64)
			}
		case uxplanprofilebinding.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case uxplanprofilebinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UxPlanProfileBinding.
// This includes values selected through modifiers, order, etc.
func (_m *UxPlanProfileBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlan queries the "plan" edge of the UxPlanProfileBinding entity.
func (_m *UxPlanProfileBinding) QueryPlan() *UxExecutionPlanQuery {
	return NewUxPlanProfileBindingClient(_m.config).QueryPlan(_m)
}

// Update returns a builder for updating this UxPlanProfileBinding.
// Note that you need to call UxPlanProfileBinding.Unwrap() before calling this method if this UxPlanProfileBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UxPlanProfileBinding) Update() *UxPlanProfileBindingUpdateOne {
	return NewUxPlanProfileBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UxPlanProfileBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UxPlanProfileBinding) Unwrap() *UxPlanProfileBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UxPlanProfileBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UxPlanProfileBinding) String() string {
	var builder strings.Builder
	builder.WriteString("UxPlanProfileBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanID))
	builder.WriteString(", ")
	builder.WriteString("profile_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProfileID))
	builder.WriteString(", ")
	builder.WriteString("execution_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExecutionOrder))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UxPlanProfileBindings is a parsable slice of UxPlanProfileBinding.
type UxPlanProfileBindings []*UxPlanProfileBinding
