// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"evalux-server/ent/uxexecutionplan"
	"evalux-server/ent/uxplanprofilequestionnairebinding"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UxPlanProfileQuestionnaireBindingCreate is the builder for creating a UxPlanProfileQuestionnaireBinding entity.
type UxPlanProfileQuestionnaireBindingCreate struct {
	config
	mutation *UxPlanProfileQuestionnaireBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlanID sets the "plan_id" field.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetPlanID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetProfileID sets the "profile_id" field.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetProfileID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetTemplateID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetQuestionOrder sets the "question_order" field.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetQuestionOrder(v int) *UxPlanProfileQuestionnaireBindingCreate {
	_c.mutation.SetQuestionOrder(v)
	return _c
}

// SetNillableQuestionOrder sets the "question_order" field if the given value is not nil.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetNillableQuestionOrder(v *int) *UxPlanProfileQuestionnaireBindingCreate {
	if v != nil {
		_c.SetQuestionOrder(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetEnabled(v bool) *UxPlanProfileQuestionnaireBindingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetNillableEnabled(v *bool) *UxPlanProfileQuestionnaireBindingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetCreatedAt(v time.Time) *UxPlanProfileQuestionnaireBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetNillableCreatedAt(v *time.Time) *UxPlanProfileQuestionnaireBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetNillableID(v *uuid.UUID) *UxPlanProfileQuestionnaireBindingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPlan sets the "plan" edge to the UxExecutionPlan entity.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SetPlan(v *UxExecutionPlan) *UxPlanProfileQuestionnaireBindingCreate {
	return _c.SetPlanID(v.ID)
}

// Mutation returns the UxPlanProfileQuestionnaireBindingMutation object of the builder.
func (_c *UxPlanProfileQuestionnaireBindingCreate) Mutation() *UxPlanProfileQuestionnaireBindingMutation {
	return _c.mutation
}

// Save creates the UxPlanProfileQuestionnaireBinding in the database.
func (_c *UxPlanProfileQuestionnaireBindingCreate) Save(ctx context.Context) (*UxPlanProfileQuestionnaireBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UxPlanProfileQuestionnaireBindingCreate) SaveX(ctx context.Context) *UxPlanProfileQuestionnaireBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UxPlanProfileQuestionnaireBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UxPlanProfileQuestionnaireBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UxPlanProfileQuestionnaireBindingCreate) defaults() {
	if _, ok := _c.mutation.QuestionOrder(); !ok {
		v := uxplanprofilequestionnairebinding.DefaultQuestionOrder
		_c.mutation.SetQuestionOrder(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := uxplanprofilequestionnairebinding.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := uxplanprofilequestionnairebinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := uxplanprofilequestionnairebinding.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UxPlanProfileQuestionnaireBindingCreate) check() error {
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "UxPlanProfileQuestionnaireBinding.plan_id"`)}
	}
	if _, ok := _c.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "UxPlanProfileQuestionnaireBinding.profile_id"`)}
	}
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "UxPlanProfileQuestionnaireBinding.template_id"`)}
	}
	if _, ok := _c.mutation.QuestionOrder(); !ok {
		return &ValidationError{Name: "question_order", err: errors.New(`ent: missing required field "UxPlanProfileQuestionnaireBinding.question_order"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UxPlanProfileQuestionnaireBinding.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UxPlanProfileQuestionnaireBinding.created_at"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "UxPlanProfileQuestionnaireBinding.plan"`)}
	}
	return nil
}

func (_c *UxPlanProfileQuestionnaireBindingCreate) sqlSave(ctx context.Context) (*UxPlanProfileQuestionnaireBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UxPlanProfileQuestionnaireBindingCreate) createSpec() (*UxPlanProfileQuestionnaireBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &UxPlanProfileQuestionnaireBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uxplanprofilequestionnairebinding.Table, sqlgraph.NewFieldSpec(uxplanprofilequestionnairebinding.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ProfileID(); ok {
		_spec.SetField(uxplanprofilequestionnairebinding.FieldProfileID, field.TypeUUID, value)
		_node.ProfileID = value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(uxplanprofilequestionnairebinding.FieldTemplateID, field.TypeUUID, value)
		_node.TemplateID = value
	}
	if value, ok := _c.mutation.QuestionOrder(); ok {
		_spec.SetField(uxplanprofilequestionnairebinding.FieldQuestionOrder, field.TypeInt, value)
		_node.QuestionOrder = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(uxplanprofilequestionnairebinding.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(uxplanprofilequestionnairebinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uxplanprofilequestionnairebinding.PlanTable,
			Columns: []string{uxplanprofilequestionnairebinding.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxexecutionplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UxPlanProfileQuestionnaireBinding.Create().
//		SetPlanID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UxPlanProfileQuestionnaireBindingUpsert) {
//			SetPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *UxPlanProfileQuestionnaireBindingCreate) OnConflict(opts ...sql.ConflictOption) *UxPlanProfileQuestionnaireBindingUpsertOne {
	_c.conflict = opts
	return &UxPlanProfileQuestionnaireBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UxPlanProfileQuestionnaireBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UxPlanProfileQuestionnaireBindingCreate) OnConflictColumns(columns ...string) *UxPlanProfileQuestionnaireBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UxPlanProfileQuestionnaireBindingUpsertOne{
		create: _c,
	}
}

type (
	// UxPlanProfileQuestionnaireBindingUpsertOne is the builder for "upsert"-ing
	//  one UxPlanProfileQuestionnaireBinding node.
	UxPlanProfileQuestionnaireBindingUpsertOne struct {
		create *UxPlanProfileQuestionnaireBindingCreate
	}

	// UxPlanProfileQuestionnaireBindingUpsert is the "OnConflict" setter.
	UxPlanProfileQuestionnaireBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlanID sets the "plan_id" field.
func (u *UxPlanProfileQuestionnaireBindingUpsert) SetPlanID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingUpsert {
	u.Set(uxplanprofilequestionnairebinding.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsert) UpdatePlanID() *UxPlanProfileQuestionnaireBindingUpsert {
	u.SetExcluded(uxplanprofilequestionnairebinding.FieldPlanID)
	return u
}

// SetProfileID sets the "profile_id" field.
func (u *UxPlanProfileQuestionnaireBindingUpsert) SetProfileID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingUpsert {
	u.Set(uxplanprofilequestionnairebinding.FieldProfileID, v)
	return u
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsert) UpdateProfileID() *UxPlanProfileQuestionnaireBindingUpsert {
	u.SetExcluded(uxplanprofilequestionnairebinding.FieldProfileID)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *UxPlanProfileQuestionnaireBindingUpsert) SetTemplateID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingUpsert {
	u.Set(uxplanprofilequestionnairebinding.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsert) UpdateTemplateID() *UxPlanProfileQuestionnaireBindingUpsert {
	u.SetExcluded(uxplanprofilequestionnairebinding.FieldTemplateID)
	return u
}

// SetQuestionOrder sets the "question_order" field.
func (u *UxPlanProfileQuestionnaireBindingUpsert) SetQuestionOrder(v int) *UxPlanProfileQuestionnaireBindingUpsert {
	u.Set(uxplanprofilequestionnairebinding.FieldQuestionOrder, v)
	return u
}

// UpdateQuestionOrder sets the "question_order" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsert) UpdateQuestionOrder() *UxPlanProfileQuestionnaireBindingUpsert {
	u.SetExcluded(uxplanprofilequestionnairebinding.FieldQuestionOrder)
	return u
}

// AddQuestionOrder adds v to the "question_order" field.
func (u *UxPlanProfileQuestionnaireBindingUpsert) AddQuestionOrder(v int) *UxPlanProfileQuestionnaireBindingUpsert {
	u.Add(uxplanprofilequestionnairebinding.FieldQuestionOrder, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *UxPlanProfileQuestionnaireBindingUpsert) SetEnabled(v bool) *UxPlanProfileQuestionnaireBindingUpsert {
	u.Set(uxplanprofilequestionnairebinding.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsert) UpdateEnabled() *UxPlanProfileQuestionnaireBindingUpsert {
	u.SetExcluded(uxplanprofilequestionnairebinding.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UxPlanProfileQuestionnaireBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(uxplanprofilequestionnairebinding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) UpdateNewValues() *UxPlanProfileQuestionnaireBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(uxplanprofilequestionnairebinding.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(uxplanprofilequestionnairebinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UxPlanProfileQuestionnaireBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) Ignore() *UxPlanProfileQuestionnaireBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) DoNothing() *UxPlanProfileQuestionnaireBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UxPlanProfileQuestionnaireBindingCreate.OnConflict
// documentation for more info.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) Update(set func(*UxPlanProfileQuestionnaireBindingUpsert)) *UxPlanProfileQuestionnaireBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UxPlanProfileQuestionnaireBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) SetPlanID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingUpsertOne {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) UpdatePlanID() *UxPlanProfileQuestionnaireBindingUpsertOne {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.UpdatePlanID()
	})
}

// SetProfileID sets the "profile_id" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) SetProfileID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingUpsertOne {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.SetProfileID(v)
	})
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) UpdateProfileID() *UxPlanProfileQuestionnaireBindingUpsertOne {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.UpdateProfileID()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) SetTemplateID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingUpsertOne {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) UpdateTemplateID() *UxPlanProfileQuestionnaireBindingUpsertOne {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.UpdateTemplateID()
	})
}

// SetQuestionOrder sets the "question_order" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) SetQuestionOrder(v int) *UxPlanProfileQuestionnaireBindingUpsertOne {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.SetQuestionOrder(v)
	})
}

// AddQuestionOrder adds v to the "question_order" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) AddQuestionOrder(v int) *UxPlanProfileQuestionnaireBindingUpsertOne {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.AddQuestionOrder(v)
	})
}

// UpdateQuestionOrder sets the "question_order" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) UpdateQuestionOrder() *UxPlanProfileQuestionnaireBindingUpsertOne {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.UpdateQuestionOrder()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) SetEnabled(v bool) *UxPlanProfileQuestionnaireBindingUpsertOne {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) UpdateEnabled() *UxPlanProfileQuestionnaireBindingUpsertOne {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UxPlanProfileQuestionnaireBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UxPlanProfileQuestionnaireBindingUpsertOne.ID is not supported by MySQL driver. Use UxPlanProfileQuestionnaireBindingUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UxPlanProfileQuestionnaireBindingUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UxPlanProfileQuestionnaireBindingCreateBulk is the builder for creating many UxPlanProfileQuestionnaireBinding entities in bulk.
type UxPlanProfileQuestionnaireBindingCreateBulk struct {
	config
	err      error
	builders []*UxPlanProfileQuestionnaireBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the UxPlanProfileQuestionnaireBinding entities in the database.
func (_c *UxPlanProfileQuestionnaireBindingCreateBulk) Save(ctx context.Context) ([]*UxPlanProfileQuestionnaireBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UxPlanProfileQuestionnaireBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UxPlanProfileQuestionnaireBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UxPlanProfileQuestionnaireBindingCreateBulk) SaveX(ctx context.Context) []*UxPlanProfileQuestionnaireBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UxPlanProfileQuestionnaireBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UxPlanProfileQuestionnaireBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UxPlanProfileQuestionnaireBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UxPlanProfileQuestionnaireBindingUpsert) {
//			SetPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *UxPlanProfileQuestionnaireBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *UxPlanProfileQuestionnaireBindingUpsertBulk {
	_c.conflict = opts
	return &UxPlanProfileQuestionnaireBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UxPlanProfileQuestionnaireBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UxPlanProfileQuestionnaireBindingCreateBulk) OnConflictColumns(columns ...string) *UxPlanProfileQuestionnaireBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UxPlanProfileQuestionnaireBindingUpsertBulk{
		create: _c,
	}
}

// UxPlanProfileQuestionnaireBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of UxPlanProfileQuestionnaireBinding nodes.
type UxPlanProfileQuestionnaireBindingUpsertBulk struct {
	create *UxPlanProfileQuestionnaireBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UxPlanProfileQuestionnaireBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(uxplanprofilequestionnairebinding.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) UpdateNewValues() *UxPlanProfileQuestionnaireBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(uxplanprofilequestionnairebinding.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(uxplanprofilequestionnairebinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UxPlanProfileQuestionnaireBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) Ignore() *UxPlanProfileQuestionnaireBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) DoNothing() *UxPlanProfileQuestionnaireBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UxPlanProfileQuestionnaireBindingCreateBulk.OnConflict
// documentation for more info.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) Update(set func(*UxPlanProfileQuestionnaireBindingUpsert)) *UxPlanProfileQuestionnaireBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UxPlanProfileQuestionnaireBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) SetPlanID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingUpsertBulk {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) UpdatePlanID() *UxPlanProfileQuestionnaireBindingUpsertBulk {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.UpdatePlanID()
	})
}

// SetProfileID sets the "profile_id" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) SetProfileID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingUpsertBulk {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.SetProfileID(v)
	})
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) UpdateProfileID() *UxPlanProfileQuestionnaireBindingUpsertBulk {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.UpdateProfileID()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) SetTemplateID(v uuid.UUID) *UxPlanProfileQuestionnaireBindingUpsertBulk {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) UpdateTemplateID() *UxPlanProfileQuestionnaireBindingUpsertBulk {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.UpdateTemplateID()
	})
}

// SetQuestionOrder sets the "question_order" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) SetQuestionOrder(v int) *UxPlanProfileQuestionnaireBindingUpsertBulk {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.SetQuestionOrder(v)
	})
}

// AddQuestionOrder adds v to the "question_order" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) AddQuestionOrder(v int) *UxPlanProfileQuestionnaireBindingUpsertBulk {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.AddQuestionOrder(v)
	})
}

// UpdateQuestionOrder sets the "question_order" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) UpdateQuestionOrder() *UxPlanProfileQuestionnaireBindingUpsertBulk {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.UpdateQuestionOrder()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) SetEnabled(v bool) *UxPlanProfileQuestionnaireBindingUpsertBulk {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) UpdateEnabled() *UxPlanProfileQuestionnaireBindingUpsertBulk {
	return u.Update(func(s *UxPlanProfileQuestionnaireBindingUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UxPlanProfileQuestionnaireBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UxPlanProfileQuestionnaireBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UxPlanProfileQuestionnaireBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
