// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"evalux-server/ent/uxprojectrole"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UxProjectRole is the model entity for the UxProjectRole schema.
type UxProjectRole struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RoleCode holds the value of the "role_code" field.
	RoleCode string `json:"role_code,omitempty"`
	// RoleName holds the value of the "role_name" field.
	RoleName string `json:"role_name,omitempty"`
	// 权限码列表: VIEW, EDIT, EXECUTE, DELETE, MANAGE_MEMBER
	PermissionCodes []string `json:"permission_codes,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UxProjectRoleQuery when eager-loading is set.
	Edges        UxProjectRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UxProjectRoleEdges holds the relations/edges for other nodes in the graph.
type UxProjectRoleEdges struct {
	// Members holds the value of the members edge.
	Members []*UxProjectMember `json:"members,omitempty"`
	// Invitations holds the value of the invitations edge.
	Invitations []*UxProjectInvitation `json:"invitations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e UxProjectRoleEdges) MembersOrErr() ([]*UxProjectMember, error) {
	if e.loadedTypes[0] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// InvitationsOrErr returns the Invitations value or an error if the edge
// was not loaded in eager-loading.
func (e UxProjectRoleEdges) InvitationsOrErr() ([]*UxProjectInvitation, error) {
	if e.loadedTypes[1] {
		return e.Invitations, nil
	}
	return nil, &NotLoadedError{edge: "invitations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UxProjectRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uxprojectrole.FieldPermissionCodes:
			values[i] = new([]byte)
		case uxprojectrole.FieldRoleCode, uxprojectrole.FieldRoleName, uxprojectrole.FieldDescription:
			values[i] = new(sql.NullString)
		case uxprojectrole.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UxProjectRole fields.
func (_m *UxProjectRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uxprojectrole.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case uxprojectrole.FieldRoleCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_code", values[i])
			} else if value.Valid {
				_m.RoleCode = value.String
			}
		case uxprojectrole.FieldRoleName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_name", values[i])
			} else if value.Valid {
				_m.RoleName = value.String
			}
		case uxprojectrole.FieldPermissionCodes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field permission_codes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PermissionCodes); err != nil {
					return fmt.Errorf("unmarshal field permission_codes: %w", err)
				}
			}
		case uxprojectrole.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UxProjectRole.
// This includes values selected through modifiers, order, etc.
func (_m *UxProjectRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMembers queries the "members" edge of the UxProjectRole entity.
func (_m *UxProjectRole) QueryMembers() *UxProjectMemberQuery {
	return NewUxProjectRoleClient(_m.config).QueryMembers(_m)
}

// QueryInvitations queries the "invitations" edge of the UxProjectRole entity.
func (_m *UxProjectRole) QueryInvitations() *UxProjectInvitationQuery {
	return NewUxProjectRoleClient(_m.config).QueryInvitations(_m)
}

// Update returns a builder for updating this UxProjectRole.
// Note that you need to call UxProjectRole.Unwrap() before calling this method if this UxProjectRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UxProjectRole) Update() *UxProjectRoleUpdateOne {
	return NewUxProjectRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UxProjectRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UxProjectRole) Unwrap() *UxProjectRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UxProjectRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UxProjectRole) String() string {
	var builder strings.Builder
	builder.WriteString("UxProjectRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("role_code=")
	builder.WriteString(_m.RoleCode)
	builder.WriteString(", ")
	builder.WriteString("role_name=")
	builder.WriteString(_m.RoleName)
	builder.WriteString(", ")
	builder.WriteString("permission_codes=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermissionCodes))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// UxProjectRoles is a parsable slice of UxProjectRole.
type UxProjectRoles []*UxProjectRole
