// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"evalux-server/ent/predicate"
	"evalux-server/ent/uxprojectinvitation"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UxProjectInvitationDelete is the builder for deleting a UxProjectInvitation entity.
type UxProjectInvitationDelete struct {
	config
	hooks    []Hook
	mutation *UxProjectInvitationMutation
}

// Where appends a list predicates to the UxProjectInvitationDelete builder.
func (_d *UxProjectInvitationDelete) Where(ps ...predicate.UxProjectInvitation) *UxProjectInvitationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UxProjectInvitationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UxProjectInvitationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UxProjectInvitationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(uxprojectinvitation.Table, sqlgraph.NewFieldSpec(uxprojectinvitation.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UxProjectInvitationDeleteOne is the builder for deleting a single UxProjectInvitation entity.
type UxProjectInvitationDeleteOne struct {
	_d *UxProjectInvitationDelete
}

// Where appends a list predicates to the UxProjectInvitationDelete builder.
func (_d *UxProjectInvitationDeleteOne) Where(ps ...predicate.UxProjectInvitation) *UxProjectInvitationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UxProjectInvitationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{uxprojectinvitation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UxProjectInvitationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
