// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"evalux-server/ent/sysuser"
	"evalux-server/ent/uxorg"
	"evalux-server/ent/uxproject"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UxProject is the model entity for the UxProject schema.
type UxProject struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// 所属组织，允许为空以支持个人项目
	OrgID *uuid.UUID `json:"org_id,omitempty"`
	// ProjectName holds the value of the "project_name" field.
	ProjectName string `json:"project_name,omitempty"`
	// AppName holds the value of the "app_name" field.
	AppName string `json:"app_name,omitempty"`
	// AppVersion holds the value of the "app_version" field.
	AppVersion *string `json:"app_version,omitempty"`
	// ResearchGoal holds the value of the "research_goal" field.
	ResearchGoal string `json:"research_goal,omitempty"`
	// ProjectDesc holds the value of the "project_desc" field.
	ProjectDesc *string `json:"project_desc,omitempty"`
	// ModelConfig holds the value of the "model_config" field.
	ModelConfig map[string]interface{} `json:"model_config,omitempty"`
	// Status holds the value of the "status" field.
	Status uxproject.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ArchivedAt holds the value of the "archived_at" field.
	ArchivedAt *time.Time `json:"archived_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UxProjectQuery when eager-loading is set.
	Edges        UxProjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UxProjectEdges holds the relations/edges for other nodes in the graph.
type UxProjectEdges struct {
	// Creator holds the value of the creator edge.
	Creator *SysUser `json:"creator,omitempty"`
	// Org holds the value of the org edge.
	Org *UxOrg `json:"org,omitempty"`
	// Profiles holds the value of the profiles edge.
	Profiles []*UxUserProfile `json:"profiles,omitempty"`
	// Tasks holds the value of the tasks edge.
	Tasks []*UxTask `json:"tasks,omitempty"`
	// QuestionnaireTemplates holds the value of the questionnaire_templates edge.
	QuestionnaireTemplates []*UxQuestionnaireTemplate `json:"questionnaire_templates,omitempty"`
	// Members holds the value of the members edge.
	Members []*UxProjectMember `json:"members,omitempty"`
	// Invitations holds the value of the invitations edge.
	Invitations []*UxProjectInvitation `json:"invitations,omitempty"`
	// ExecutionPlans holds the value of the execution_plans edge.
	ExecutionPlans []*UxExecutionPlan `json:"execution_plans,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UxProjectEdges) CreatorOrErr() (*SysUser, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// OrgOrErr returns the Org value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UxProjectEdges) OrgOrErr() (*UxOrg, error) {
	if e.Org != nil {
		return e.Org, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: uxorg.Label}
	}
	return nil, &NotLoadedError{edge: "org"}
}

// ProfilesOrErr returns the Profiles value or an error if the edge
// was not loaded in eager-loading.
func (e UxProjectEdges) ProfilesOrErr() ([]*UxUserProfile, error) {
	if e.loadedTypes[2] {
		return e.Profiles, nil
	}
	return nil, &NotLoadedError{edge: "profiles"}
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e UxProjectEdges) TasksOrErr() ([]*UxTask, error) {
	if e.loadedTypes[3] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// QuestionnaireTemplatesOrErr returns the QuestionnaireTemplates value or an error if the edge
// was not loaded in eager-loading.
func (e UxProjectEdges) QuestionnaireTemplatesOrErr() ([]*UxQuestionnaireTemplate, error) {
	if e.loadedTypes[4] {
		return e.QuestionnaireTemplates, nil
	}
	return nil, &NotLoadedError{edge: "questionnaire_templates"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e UxProjectEdges) MembersOrErr() ([]*UxProjectMember, error) {
	if e.loadedTypes[5] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// InvitationsOrErr returns the Invitations value or an error if the edge
// was not loaded in eager-loading.
func (e UxProjectEdges) InvitationsOrErr() ([]*UxProjectInvitation, error) {
	if e.loadedTypes[6] {
		return e.Invitations, nil
	}
	return nil, &NotLoadedError{edge: "invitations"}
}

// ExecutionPlansOrErr returns the ExecutionPlans value or an error if the edge
// was not loaded in eager-loading.
func (e UxProjectEdges) ExecutionPlansOrErr() ([]*UxExecutionPlan, error) {
	if e.loadedTypes[7] {
		return e.ExecutionPlans, nil
	}
	return nil, &NotLoadedError{edge: "execution_plans"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UxProject) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uxproject.FieldOrgID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case uxproject.FieldModelConfig:
			values[i] = new([]byte)
		case uxproject.FieldProjectName, uxproject.FieldAppName, uxproject.FieldAppVersion, uxproject.FieldResearchGoal, uxproject.FieldProjectDesc, uxproject.FieldStatus:
			values[i] = new(sql.NullString)
		case uxproject.FieldCreatedAt, uxproject.FieldArchivedAt:
			values[i] = new(sql.NullTime)
		case uxproject.FieldID, uxproject.FieldCreatedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UxProject fields.
func (_m *UxProject) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uxproject.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case uxproject.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				_m.CreatedBy = *value
			}
		case uxproject.FieldOrgID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field org_id", values[i])
			} else if value.Valid {
				_m.OrgID = new(uuid.UUID)
				*_m.OrgID = *value.S.(*uuid.UUID)
			}
		case uxproject.FieldProjectName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_name", values[i])
			} else if value.Valid {
				_m.ProjectName = value.String
			}
		case uxproject.FieldAppName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_name", values[i])
			} else if value.Valid {
				_m.AppName = value.String
			}
		case uxproject.FieldAppVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_version", values[i])
			} else if value.Valid {
				_m.AppVersion = new(string)
				*_m.AppVersion = value.String
			}
		case uxproject.FieldResearchGoal:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field research_goal", values[i])
			} else if value.Valid {
				_m.ResearchGoal = value.String
			}
		case uxproject.FieldProjectDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_desc", values[i])
			} else if value.Valid {
				_m.ProjectDesc = new(string)
				*_m.ProjectDesc = value.String
			}
		case uxproject.FieldModelConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field model_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ModelConfig); err != nil {
					return fmt.Errorf("unmarshal field model_config: %w", err)
				}
			}
		case uxproject.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = uxproject.Status(value.String)
			}
		case uxproject.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case uxproject.FieldArchivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field archived_at", values[i])
			} else if value.Valid {
				_m.ArchivedAt = new(time.Time)
				*_m.ArchivedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UxProject.
// This includes values selected through modifiers, order, etc.
func (_m *UxProject) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCreator queries the "creator" edge of the UxProject entity.
func (_m *UxProject) QueryCreator() *SysUserQuery {
	return NewUxProjectClient(_m.config).QueryCreator(_m)
}

// QueryOrg queries the "org" edge of the UxProject entity.
func (_m *UxProject) QueryOrg() *UxOrgQuery {
	return NewUxProjectClient(_m.config).QueryOrg(_m)
}

// QueryProfiles queries the "profiles" edge of the UxProject entity.
func (_m *UxProject) QueryProfiles() *UxUserProfileQuery {
	return NewUxProjectClient(_m.config).QueryProfiles(_m)
}

// QueryTasks queries the "tasks" edge of the UxProject entity.
func (_m *UxProject) QueryTasks() *UxTaskQuery {
	return NewUxProjectClient(_m.config).QueryTasks(_m)
}

// QueryQuestionnaireTemplates queries the "questionnaire_templates" edge of the UxProject entity.
func (_m *UxProject) QueryQuestionnaireTemplates() *UxQuestionnaireTemplateQuery {
	return NewUxProjectClient(_m.config).QueryQuestionnaireTemplates(_m)
}

// QueryMembers queries the "members" edge of the UxProject entity.
func (_m *UxProject) QueryMembers() *UxProjectMemberQuery {
	return NewUxProjectClient(_m.config).QueryMembers(_m)
}

// QueryInvitations queries the "invitations" edge of the UxProject entity.
func (_m *UxProject) QueryInvitations() *UxProjectInvitationQuery {
	return NewUxProjectClient(_m.config).QueryInvitations(_m)
}

// QueryExecutionPlans queries the "execution_plans" edge of the UxProject entity.
func (_m *UxProject) QueryExecutionPlans() *UxExecutionPlanQuery {
	return NewUxProjectClient(_m.config).QueryExecutionPlans(_m)
}

// Update returns a builder for updating this UxProject.
// Note that you need to call UxProject.Unwrap() before calling this method if this UxProject
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UxProject) Update() *UxProjectUpdateOne {
	return NewUxProjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UxProject entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UxProject) Unwrap() *UxProject {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UxProject is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UxProject) String() string {
	var builder strings.Builder
	builder.WriteString("UxProject(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	if v := _m.OrgID; v != nil {
		builder.WriteString("org_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("project_name=")
	builder.WriteString(_m.ProjectName)
	builder.WriteString(", ")
	builder.WriteString("app_name=")
	builder.WriteString(_m.AppName)
	builder.WriteString(", ")
	if v := _m.AppVersion; v != nil {
		builder.WriteString("app_version=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("research_goal=")
	builder.WriteString(_m.ResearchGoal)
	builder.WriteString(", ")
	if v := _m.ProjectDesc; v != nil {
		builder.WriteString("project_desc=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("model_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelConfig))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ArchivedAt; v != nil {
		builder.WriteString("archived_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UxProjects is a parsable slice of UxProject.
type UxProjects []*UxProject
