// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"evalux-server/ent/predicate"
	"evalux-server/ent/uxexecutionsession"
	"evalux-server/ent/uxrecordingrecord"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UxRecordingRecordUpdate is the builder for updating UxRecordingRecord entities.
type UxRecordingRecordUpdate struct {
	config
	hooks    []Hook
	mutation *UxRecordingRecordMutation
}

// Where appends a list predicates to the UxRecordingRecordUpdate builder.
func (_u *UxRecordingRecordUpdate) Where(ps ...predicate.UxRecordingRecord) *UxRecordingRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *UxRecordingRecordUpdate) SetSessionID(v uuid.UUID) *UxRecordingRecordUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *UxRecordingRecordUpdate) SetNillableSessionID(v *uuid.UUID) *UxRecordingRecordUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *UxRecordingRecordUpdate) SetFilePath(v string) *UxRecordingRecordUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *UxRecordingRecordUpdate) SetNillableFilePath(v *string) *UxRecordingRecordUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *UxRecordingRecordUpdate) SetStartedAt(v time.Time) *UxRecordingRecordUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *UxRecordingRecordUpdate) SetNillableStartedAt(v *time.Time) *UxRecordingRecordUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *UxRecordingRecordUpdate) SetEndedAt(v time.Time) *UxRecordingRecordUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *UxRecordingRecordUpdate) SetNillableEndedAt(v *time.Time) *UxRecordingRecordUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *UxRecordingRecordUpdate) ClearEndedAt() *UxRecordingRecordUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_u *UxRecordingRecordUpdate) SetFileSizeBytes(v int64) *UxRecordingRecordUpdate {
	_u.mutation.ResetFileSizeBytes()
	_u.mutation.SetFileSizeBytes(v)
	return _u
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_u *UxRecordingRecordUpdate) SetNillableFileSizeBytes(v *int64) *UxRecordingRecordUpdate {
	if v != nil {
		_u.SetFileSizeBytes(*v)
	}
	return _u
}

// AddFileSizeBytes adds value to the "file_size_bytes" field.
func (_u *UxRecordingRecordUpdate) AddFileSizeBytes(v int64) *UxRecordingRecordUpdate {
	_u.mutation.AddFileSizeBytes(v)
	return _u
}

// ClearFileSizeBytes clears the value of the "file_size_bytes" field.
func (_u *UxRecordingRecordUpdate) ClearFileSizeBytes() *UxRecordingRecordUpdate {
	_u.mutation.ClearFileSizeBytes()
	return _u
}

// SetStorageStatus sets the "storage_status" field.
func (_u *UxRecordingRecordUpdate) SetStorageStatus(v uxrecordingrecord.StorageStatus) *UxRecordingRecordUpdate {
	_u.mutation.SetStorageStatus(v)
	return _u
}

// SetNillableStorageStatus sets the "storage_status" field if the given value is not nil.
func (_u *UxRecordingRecordUpdate) SetNillableStorageStatus(v *uxrecordingrecord.StorageStatus) *UxRecordingRecordUpdate {
	if v != nil {
		_u.SetStorageStatus(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the UxExecutionSession entity.
func (_u *UxRecordingRecordUpdate) SetSession(v *UxExecutionSession) *UxRecordingRecordUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the UxRecordingRecordMutation object of the builder.
func (_u *UxRecordingRecordUpdate) Mutation() *UxRecordingRecordMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the UxExecutionSession entity.
func (_u *UxRecordingRecordUpdate) ClearSession() *UxRecordingRecordUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UxRecordingRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UxRecordingRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UxRecordingRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UxRecordingRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UxRecordingRecordUpdate) check() error {
	if v, ok := _u.mutation.FilePath(); ok {
		if err := uxrecordingrecord.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "UxRecordingRecord.file_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageStatus(); ok {
		if err := uxrecordingrecord.StorageStatusValidator(v); err != nil {
			return &ValidationError{Name: "storage_status", err: fmt.Errorf(`ent: validator failed for field "UxRecordingRecord.storage_status": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UxRecordingRecord.session"`)
	}
	return nil
}

func (_u *UxRecordingRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uxrecordingrecord.Table, uxrecordingrecord.Columns, sqlgraph.NewFieldSpec(uxrecordingrecord.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(uxrecordingrecord.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(uxrecordingrecord.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(uxrecordingrecord.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(uxrecordingrecord.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FileSizeBytes(); ok {
		_spec.SetField(uxrecordingrecord.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSizeBytes(); ok {
		_spec.AddField(uxrecordingrecord.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.FileSizeBytesCleared() {
		_spec.ClearField(uxrecordingrecord.FieldFileSizeBytes, field.TypeInt64)
	}
	if value, ok := _u.mutation.StorageStatus(); ok {
		_spec.SetField(uxrecordingrecord.FieldStorageStatus, field.TypeEnum, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   uxrecordingrecord.SessionTable,
			Columns: []string{uxrecordingrecord.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxexecutionsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   uxrecordingrecord.SessionTable,
			Columns: []string{uxrecordingrecord.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxexecutionsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uxrecordingrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UxRecordingRecordUpdateOne is the builder for updating a single UxRecordingRecord entity.
type UxRecordingRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UxRecordingRecordMutation
}

// SetSessionID sets the "session_id" field.
func (_u *UxRecordingRecordUpdateOne) SetSessionID(v uuid.UUID) *UxRecordingRecordUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *UxRecordingRecordUpdateOne) SetNillableSessionID(v *uuid.UUID) *UxRecordingRecordUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *UxRecordingRecordUpdateOne) SetFilePath(v string) *UxRecordingRecordUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *UxRecordingRecordUpdateOne) SetNillableFilePath(v *string) *UxRecordingRecordUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *UxRecordingRecordUpdateOne) SetStartedAt(v time.Time) *UxRecordingRecordUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *UxRecordingRecordUpdateOne) SetNillableStartedAt(v *time.Time) *UxRecordingRecordUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *UxRecordingRecordUpdateOne) SetEndedAt(v time.Time) *UxRecordingRecordUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *UxRecordingRecordUpdateOne) SetNillableEndedAt(v *time.Time) *UxRecordingRecordUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *UxRecordingRecordUpdateOne) ClearEndedAt() *UxRecordingRecordUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_u *UxRecordingRecordUpdateOne) SetFileSizeBytes(v int64) *UxRecordingRecordUpdateOne {
	_u.mutation.ResetFileSizeBytes()
	_u.mutation.SetFileSizeBytes(v)
	return _u
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_u *UxRecordingRecordUpdateOne) SetNillableFileSizeBytes(v *int64) *UxRecordingRecordUpdateOne {
	if v != nil {
		_u.SetFileSizeBytes(*v)
	}
	return _u
}

// AddFileSizeBytes adds value to the "file_size_bytes" field.
func (_u *UxRecordingRecordUpdateOne) AddFileSizeBytes(v int64) *UxRecordingRecordUpdateOne {
	_u.mutation.AddFileSizeBytes(v)
	return _u
}

// ClearFileSizeBytes clears the value of the "file_size_bytes" field.
func (_u *UxRecordingRecordUpdateOne) ClearFileSizeBytes() *UxRecordingRecordUpdateOne {
	_u.mutation.ClearFileSizeBytes()
	return _u
}

// SetStorageStatus sets the "storage_status" field.
func (_u *UxRecordingRecordUpdateOne) SetStorageStatus(v uxrecordingrecord.StorageStatus) *UxRecordingRecordUpdateOne {
	_u.mutation.SetStorageStatus(v)
	return _u
}

// SetNillableStorageStatus sets the "storage_status" field if the given value is not nil.
func (_u *UxRecordingRecordUpdateOne) SetNillableStorageStatus(v *uxrecordingrecord.StorageStatus) *UxRecordingRecordUpdateOne {
	if v != nil {
		_u.SetStorageStatus(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the UxExecutionSession entity.
func (_u *UxRecordingRecordUpdateOne) SetSession(v *UxExecutionSession) *UxRecordingRecordUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the UxRecordingRecordMutation object of the builder.
func (_u *UxRecordingRecordUpdateOne) Mutation() *UxRecordingRecordMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the UxExecutionSession entity.
func (_u *UxRecordingRecordUpdateOne) ClearSession() *UxRecordingRecordUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the UxRecordingRecordUpdate builder.
func (_u *UxRecordingRecordUpdateOne) Where(ps ...predicate.UxRecordingRecord) *UxRecordingRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UxRecordingRecordUpdateOne) Select(field string, fields ...string) *UxRecordingRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UxRecordingRecord entity.
func (_u *UxRecordingRecordUpdateOne) Save(ctx context.Context) (*UxRecordingRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UxRecordingRecordUpdateOne) SaveX(ctx context.Context) *UxRecordingRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UxRecordingRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UxRecordingRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UxRecordingRecordUpdateOne) check() error {
	if v, ok := _u.mutation.FilePath(); ok {
		if err := uxrecordingrecord.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "UxRecordingRecord.file_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StorageStatus(); ok {
		if err := uxrecordingrecord.StorageStatusValidator(v); err != nil {
			return &ValidationError{Name: "storage_status", err: fmt.Errorf(`ent: validator failed for field "UxRecordingRecord.storage_status": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UxRecordingRecord.session"`)
	}
	return nil
}

func (_u *UxRecordingRecordUpdateOne) sqlSave(ctx context.Context) (_node *UxRecordingRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uxrecordingrecord.Table, uxrecordingrecord.Columns, sqlgraph.NewFieldSpec(uxrecordingrecord.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UxRecordingRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uxrecordingrecord.FieldID)
		for _, f := range fields {
			if !uxrecordingrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != uxrecordingrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(uxrecordingrecord.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(uxrecordingrecord.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(uxrecordingrecord.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(uxrecordingrecord.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FileSizeBytes(); ok {
		_spec.SetField(uxrecordingrecord.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSizeBytes(); ok {
		_spec.AddField(uxrecordingrecord.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.FileSizeBytesCleared() {
		_spec.ClearField(uxrecordingrecord.FieldFileSizeBytes, field.TypeInt64)
	}
	if value, ok := _u.mutation.StorageStatus(); ok {
		_spec.SetField(uxrecordingrecord.FieldStorageStatus, field.TypeEnum, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   uxrecordingrecord.SessionTable,
			Columns: []string{uxrecordingrecord.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxexecutionsession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   uxrecordingrecord.SessionTable,
			Columns: []string{uxrecordingrecord.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxexecutionsession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UxRecordingRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uxrecordingrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
