// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"evalux-server/ent/uxexecutionrun"
	"evalux-server/ent/uxresultsnapshot"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UxResultSnapshotCreate is the builder for creating a UxResultSnapshot entity.
type UxResultSnapshotCreate struct {
	config
	mutation *UxResultSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRunID sets the "run_id" field.
func (_c *UxResultSnapshotCreate) SetRunID(v uuid.UUID) *UxResultSnapshotCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetBatchID sets the "batch_id" field.
func (_c *UxResultSnapshotCreate) SetBatchID(v string) *UxResultSnapshotCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetScopeType sets the "scope_type" field.
func (_c *UxResultSnapshotCreate) SetScopeType(v uxresultsnapshot.ScopeType) *UxResultSnapshotCreate {
	_c.mutation.SetScopeType(v)
	return _c
}

// SetScopeKey sets the "scope_key" field.
func (_c *UxResultSnapshotCreate) SetScopeKey(v uuid.UUID) *UxResultSnapshotCreate {
	_c.mutation.SetScopeKey(v)
	return _c
}

// SetNillableScopeKey sets the "scope_key" field if the given value is not nil.
func (_c *UxResultSnapshotCreate) SetNillableScopeKey(v *uuid.UUID) *UxResultSnapshotCreate {
	if v != nil {
		_c.SetScopeKey(*v)
	}
	return _c
}

// SetTotalSessions sets the "total_sessions" field.
func (_c *UxResultSnapshotCreate) SetTotalSessions(v int) *UxResultSnapshotCreate {
	_c.mutation.SetTotalSessions(v)
	return _c
}

// SetNillableTotalSessions sets the "total_sessions" field if the given value is not nil.
func (_c *UxResultSnapshotCreate) SetNillableTotalSessions(v *int) *UxResultSnapshotCreate {
	if v != nil {
		_c.SetTotalSessions(*v)
	}
	return _c
}

// SetCompletedSessions sets the "completed_sessions" field.
func (_c *UxResultSnapshotCreate) SetCompletedSessions(v int) *UxResultSnapshotCreate {
	_c.mutation.SetCompletedSessions(v)
	return _c
}

// SetNillableCompletedSessions sets the "completed_sessions" field if the given value is not nil.
func (_c *UxResultSnapshotCreate) SetNillableCompletedSessions(v *int) *UxResultSnapshotCreate {
	if v != nil {
		_c.SetCompletedSessions(*v)
	}
	return _c
}

// SetFailedSessions sets the "failed_sessions" field.
func (_c *UxResultSnapshotCreate) SetFailedSessions(v int) *UxResultSnapshotCreate {
	_c.mutation.SetFailedSessions(v)
	return _c
}

// SetNillableFailedSessions sets the "failed_sessions" field if the given value is not nil.
func (_c *UxResultSnapshotCreate) SetNillableFailedSessions(v *int) *UxResultSnapshotCreate {
	if v != nil {
		_c.SetFailedSessions(*v)
	}
	return _c
}

// SetCompletionRate sets the "completion_rate" field.
func (_c *UxResultSnapshotCreate) SetCompletionRate(v float64) *UxResultSnapshotCreate {
	_c.mutation.SetCompletionRate(v)
	return _c
}

// SetNillableCompletionRate sets the "completion_rate" field if the given value is not nil.
func (_c *UxResultSnapshotCreate) SetNillableCompletionRate(v *float64) *UxResultSnapshotCreate {
	if v != nil {
		_c.SetCompletionRate(*v)
	}
	return _c
}

// SetAvgDurationMs sets the "avg_duration_ms" field.
func (_c *UxResultSnapshotCreate) SetAvgDurationMs(v int64) *UxResultSnapshotCreate {
	_c.mutation.SetAvgDurationMs(v)
	return _c
}

// SetNillableAvgDurationMs sets the "avg_duration_ms" field if the given value is not nil.
func (_c *UxResultSnapshotCreate) SetNillableAvgDurationMs(v *int64) *UxResultSnapshotCreate {
	if v != nil {
		_c.SetAvgDurationMs(*v)
	}
	return _c
}

// SetAvgErrorCount sets the "avg_error_count" field.
func (_c *UxResultSnapshotCreate) SetAvgErrorCount(v float64) *UxResultSnapshotCreate {
	_c.mutation.SetAvgErrorCount(v)
	return _c
}

// SetNillableAvgErrorCount sets the "avg_error_count" field if the given value is not nil.
func (_c *UxResultSnapshotCreate) SetNillableAvgErrorCount(v *float64) *UxResultSnapshotCreate {
	if v != nil {
		_c.SetAvgErrorCount(*v)
	}
	return _c
}

// SetAvgScore sets the "avg_score" field.
func (_c *UxResultSnapshotCreate) SetAvgScore(v float64) *UxResultSnapshotCreate {
	_c.mutation.SetAvgScore(v)
	return _c
}

// SetNillableAvgScore sets the "avg_score" field if the given value is not nil.
func (_c *UxResultSnapshotCreate) SetNillableAvgScore(v *float64) *UxResultSnapshotCreate {
	if v != nil {
		_c.SetAvgScore(*v)
	}
	return _c
}

// SetMetricPayload sets the "metric_payload" field.
func (_c *UxResultSnapshotCreate) SetMetricPayload(v map[string]interface{}) *UxResultSnapshotCreate {
	_c.mutation.SetMetricPayload(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UxResultSnapshotCreate) SetCreatedAt(v time.Time) *UxResultSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UxResultSnapshotCreate) SetNillableCreatedAt(v *time.Time) *UxResultSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UxResultSnapshotCreate) SetID(v uuid.UUID) *UxResultSnapshotCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UxResultSnapshotCreate) SetNillableID(v *uuid.UUID) *UxResultSnapshotCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRun sets the "run" edge to the UxExecutionRun entity.
func (_c *UxResultSnapshotCreate) SetRun(v *UxExecutionRun) *UxResultSnapshotCreate {
	return _c.SetRunID(v.ID)
}

// Mutation returns the UxResultSnapshotMutation object of the builder.
func (_c *UxResultSnapshotCreate) Mutation() *UxResultSnapshotMutation {
	return _c.mutation
}

// Save creates the UxResultSnapshot in the database.
func (_c *UxResultSnapshotCreate) Save(ctx context.Context) (*UxResultSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UxResultSnapshotCreate) SaveX(ctx context.Context) *UxResultSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UxResultSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UxResultSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UxResultSnapshotCreate) defaults() {
	if _, ok := _c.mutation.TotalSessions(); !ok {
		v := uxresultsnapshot.DefaultTotalSessions
		_c.mutation.SetTotalSessions(v)
	}
	if _, ok := _c.mutation.CompletedSessions(); !ok {
		v := uxresultsnapshot.DefaultCompletedSessions
		_c.mutation.SetCompletedSessions(v)
	}
	if _, ok := _c.mutation.FailedSessions(); !ok {
		v := uxresultsnapshot.DefaultFailedSessions
		_c.mutation.SetFailedSessions(v)
	}
	if _, ok := _c.mutation.CompletionRate(); !ok {
		v := uxresultsnapshot.DefaultCompletionRate
		_c.mutation.SetCompletionRate(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := uxresultsnapshot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := uxresultsnapshot.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UxResultSnapshotCreate) check() error {
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "UxResultSnapshot.run_id"`)}
	}
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "UxResultSnapshot.batch_id"`)}
	}
	if v, ok := _c.mutation.BatchID(); ok {
		if err := uxresultsnapshot.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "UxResultSnapshot.batch_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeType(); !ok {
		return &ValidationError{Name: "scope_type", err: errors.New(`ent: missing required field "UxResultSnapshot.scope_type"`)}
	}
	if v, ok := _c.mutation.ScopeType(); ok {
		if err := uxresultsnapshot.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "UxResultSnapshot.scope_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalSessions(); !ok {
		return &ValidationError{Name: "total_sessions", err: errors.New(`ent: missing required field "UxResultSnapshot.total_sessions"`)}
	}
	if _, ok := _c.mutation.CompletedSessions(); !ok {
		return &ValidationError{Name: "completed_sessions", err: errors.New(`ent: missing required field "UxResultSnapshot.completed_sessions"`)}
	}
	if _, ok := _c.mutation.FailedSessions(); !ok {
		return &ValidationError{Name: "failed_sessions", err: errors.New(`ent: missing required field "UxResultSnapshot.failed_sessions"`)}
	}
	if _, ok := _c.mutation.CompletionRate(); !ok {
		return &ValidationError{Name: "completion_rate", err: errors.New(`ent: missing required field "UxResultSnapshot.completion_rate"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UxResultSnapshot.created_at"`)}
	}
	if len(_c.mutation.RunIDs()) == 0 {
		return &ValidationError{Name: "run", err: errors.New(`ent: missing required edge "UxResultSnapshot.run"`)}
	}
	return nil
}

func (_c *UxResultSnapshotCreate) sqlSave(ctx context.Context) (*UxResultSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UxResultSnapshotCreate) createSpec() (*UxResultSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &UxResultSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uxresultsnapshot.Table, sqlgraph.NewFieldSpec(uxresultsnapshot.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.BatchID(); ok {
		_spec.SetField(uxresultsnapshot.FieldBatchID, field.TypeString, value)
		_node.BatchID = value
	}
	if value, ok := _c.mutation.ScopeType(); ok {
		_spec.SetField(uxresultsnapshot.FieldScopeType, field.TypeEnum, value)
		_node.ScopeType = value
	}
	if value, ok := _c.mutation.ScopeKey(); ok {
		_spec.SetField(uxresultsnapshot.FieldScopeKey, field.TypeUUID, value)
		_node.ScopeKey = &value
	}
	if value, ok := _c.mutation.TotalSessions(); ok {
		_spec.SetField(uxresultsnapshot.FieldTotalSessions, field.TypeInt, value)
		_node.TotalSessions = value
	}
	if value, ok := _c.mutation.CompletedSessions(); ok {
		_spec.SetField(uxresultsnapshot.FieldCompletedSessions, field.TypeInt, value)
		_node.CompletedSessions = value
	}
	if value, ok := _c.mutation.FailedSessions(); ok {
		_spec.SetField(uxresultsnapshot.FieldFailedSessions, field.TypeInt, value)
		_node.FailedSessions = value
	}
	if value, ok := _c.mutation.CompletionRate(); ok {
		_spec.SetField(uxresultsnapshot.FieldCompletionRate, field.TypeFloat64, value)
		_node.CompletionRate = value
	}
	if value, ok := _c.mutation.AvgDurationMs(); ok {
		_spec.SetField(uxresultsnapshot.FieldAvgDurationMs, field.TypeInt64, value)
		_node.AvgDurationMs = &value
	}
	if value, ok := _c.mutation.AvgErrorCount(); ok {
		_spec.SetField(uxresultsnapshot.FieldAvgErrorCount, field.TypeFloat64, value)
		_node.AvgErrorCount = &value
	}
	if value, ok := _c.mutation.AvgScore(); ok {
		_spec.SetField(uxresultsnapshot.FieldAvgScore, field.TypeFloat64, value)
		_node.AvgScore = &value
	}
	if value, ok := _c.mutation.MetricPayload(); ok {
		_spec.SetField(uxresultsnapshot.FieldMetricPayload, field.TypeJSON, value)
		_node.MetricPayload = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(uxresultsnapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uxresultsnapshot.RunTable,
			Columns: []string{uxresultsnapshot.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxexecutionrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RunID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UxResultSnapshot.Create().
//		SetRunID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UxResultSnapshotUpsert) {
//			SetRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *UxResultSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *UxResultSnapshotUpsertOne {
	_c.conflict = opts
	return &UxResultSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UxResultSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UxResultSnapshotCreate) OnConflictColumns(columns ...string) *UxResultSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UxResultSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// UxResultSnapshotUpsertOne is the builder for "upsert"-ing
	//  one UxResultSnapshot node.
	UxResultSnapshotUpsertOne struct {
		create *UxResultSnapshotCreate
	}

	// UxResultSnapshotUpsert is the "OnConflict" setter.
	UxResultSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetRunID sets the "run_id" field.
func (u *UxResultSnapshotUpsert) SetRunID(v uuid.UUID) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldRunID, v)
	return u
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateRunID() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldRunID)
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *UxResultSnapshotUpsert) SetBatchID(v string) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldBatchID, v)
	return u
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateBatchID() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldBatchID)
	return u
}

// SetScopeType sets the "scope_type" field.
func (u *UxResultSnapshotUpsert) SetScopeType(v uxresultsnapshot.ScopeType) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldScopeType, v)
	return u
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateScopeType() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldScopeType)
	return u
}

// SetScopeKey sets the "scope_key" field.
func (u *UxResultSnapshotUpsert) SetScopeKey(v uuid.UUID) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldScopeKey, v)
	return u
}

// UpdateScopeKey sets the "scope_key" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateScopeKey() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldScopeKey)
	return u
}

// ClearScopeKey clears the value of the "scope_key" field.
func (u *UxResultSnapshotUpsert) ClearScopeKey() *UxResultSnapshotUpsert {
	u.SetNull(uxresultsnapshot.FieldScopeKey)
	return u
}

// SetTotalSessions sets the "total_sessions" field.
func (u *UxResultSnapshotUpsert) SetTotalSessions(v int) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldTotalSessions, v)
	return u
}

// UpdateTotalSessions sets the "total_sessions" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateTotalSessions() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldTotalSessions)
	return u
}

// AddTotalSessions adds v to the "total_sessions" field.
func (u *UxResultSnapshotUpsert) AddTotalSessions(v int) *UxResultSnapshotUpsert {
	u.Add(uxresultsnapshot.FieldTotalSessions, v)
	return u
}

// SetCompletedSessions sets the "completed_sessions" field.
func (u *UxResultSnapshotUpsert) SetCompletedSessions(v int) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldCompletedSessions, v)
	return u
}

// UpdateCompletedSessions sets the "completed_sessions" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateCompletedSessions() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldCompletedSessions)
	return u
}

// AddCompletedSessions adds v to the "completed_sessions" field.
func (u *UxResultSnapshotUpsert) AddCompletedSessions(v int) *UxResultSnapshotUpsert {
	u.Add(uxresultsnapshot.FieldCompletedSessions, v)
	return u
}

// SetFailedSessions sets the "failed_sessions" field.
func (u *UxResultSnapshotUpsert) SetFailedSessions(v int) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldFailedSessions, v)
	return u
}

// UpdateFailedSessions sets the "failed_sessions" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateFailedSessions() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldFailedSessions)
	return u
}

// AddFailedSessions adds v to the "failed_sessions" field.
func (u *UxResultSnapshotUpsert) AddFailedSessions(v int) *UxResultSnapshotUpsert {
	u.Add(uxresultsnapshot.FieldFailedSessions, v)
	return u
}

// SetCompletionRate sets the "completion_rate" field.
func (u *UxResultSnapshotUpsert) SetCompletionRate(v float64) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldCompletionRate, v)
	return u
}

// UpdateCompletionRate sets the "completion_rate" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateCompletionRate() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldCompletionRate)
	return u
}

// AddCompletionRate adds v to the "completion_rate" field.
func (u *UxResultSnapshotUpsert) AddCompletionRate(v float64) *UxResultSnapshotUpsert {
	u.Add(uxresultsnapshot.FieldCompletionRate, v)
	return u
}

// SetAvgDurationMs sets the "avg_duration_ms" field.
func (u *UxResultSnapshotUpsert) SetAvgDurationMs(v int64) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldAvgDurationMs, v)
	return u
}

// UpdateAvgDurationMs sets the "avg_duration_ms" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateAvgDurationMs() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldAvgDurationMs)
	return u
}

// AddAvgDurationMs adds v to the "avg_duration_ms" field.
func (u *UxResultSnapshotUpsert) AddAvgDurationMs(v int64) *UxResultSnapshotUpsert {
	u.Add(uxresultsnapshot.FieldAvgDurationMs, v)
	return u
}

// ClearAvgDurationMs clears the value of the "avg_duration_ms" field.
func (u *UxResultSnapshotUpsert) ClearAvgDurationMs() *UxResultSnapshotUpsert {
	u.SetNull(uxresultsnapshot.FieldAvgDurationMs)
	return u
}

// SetAvgErrorCount sets the "avg_error_count" field.
func (u *UxResultSnapshotUpsert) SetAvgErrorCount(v float64) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldAvgErrorCount, v)
	return u
}

// UpdateAvgErrorCount sets the "avg_error_count" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateAvgErrorCount() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldAvgErrorCount)
	return u
}

// AddAvgErrorCount adds v to the "avg_error_count" field.
func (u *UxResultSnapshotUpsert) AddAvgErrorCount(v float64) *UxResultSnapshotUpsert {
	u.Add(uxresultsnapshot.FieldAvgErrorCount, v)
	return u
}

// ClearAvgErrorCount clears the value of the "avg_error_count" field.
func (u *UxResultSnapshotUpsert) ClearAvgErrorCount() *UxResultSnapshotUpsert {
	u.SetNull(uxresultsnapshot.FieldAvgErrorCount)
	return u
}

// SetAvgScore sets the "avg_score" field.
func (u *UxResultSnapshotUpsert) SetAvgScore(v float64) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldAvgScore, v)
	return u
}

// UpdateAvgScore sets the "avg_score" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateAvgScore() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldAvgScore)
	return u
}

// AddAvgScore adds v to the "avg_score" field.
func (u *UxResultSnapshotUpsert) AddAvgScore(v float64) *UxResultSnapshotUpsert {
	u.Add(uxresultsnapshot.FieldAvgScore, v)
	return u
}

// ClearAvgScore clears the value of the "avg_score" field.
func (u *UxResultSnapshotUpsert) ClearAvgScore() *UxResultSnapshotUpsert {
	u.SetNull(uxresultsnapshot.FieldAvgScore)
	return u
}

// SetMetricPayload sets the "metric_payload" field.
func (u *UxResultSnapshotUpsert) SetMetricPayload(v map[string]interface{}) *UxResultSnapshotUpsert {
	u.Set(uxresultsnapshot.FieldMetricPayload, v)
	return u
}

// UpdateMetricPayload sets the "metric_payload" field to the value that was provided on create.
func (u *UxResultSnapshotUpsert) UpdateMetricPayload() *UxResultSnapshotUpsert {
	u.SetExcluded(uxresultsnapshot.FieldMetricPayload)
	return u
}

// ClearMetricPayload clears the value of the "metric_payload" field.
func (u *UxResultSnapshotUpsert) ClearMetricPayload() *UxResultSnapshotUpsert {
	u.SetNull(uxresultsnapshot.FieldMetricPayload)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UxResultSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(uxresultsnapshot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UxResultSnapshotUpsertOne) UpdateNewValues() *UxResultSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(uxresultsnapshot.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(uxresultsnapshot.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UxResultSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UxResultSnapshotUpsertOne) Ignore() *UxResultSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UxResultSnapshotUpsertOne) DoNothing() *UxResultSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UxResultSnapshotCreate.OnConflict
// documentation for more info.
func (u *UxResultSnapshotUpsertOne) Update(set func(*UxResultSnapshotUpsert)) *UxResultSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UxResultSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunID sets the "run_id" field.
func (u *UxResultSnapshotUpsertOne) SetRunID(v uuid.UUID) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateRunID() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateRunID()
	})
}

// SetBatchID sets the "batch_id" field.
func (u *UxResultSnapshotUpsertOne) SetBatchID(v string) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateBatchID() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateBatchID()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *UxResultSnapshotUpsertOne) SetScopeType(v uxresultsnapshot.ScopeType) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateScopeType() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateScopeType()
	})
}

// SetScopeKey sets the "scope_key" field.
func (u *UxResultSnapshotUpsertOne) SetScopeKey(v uuid.UUID) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetScopeKey(v)
	})
}

// UpdateScopeKey sets the "scope_key" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateScopeKey() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateScopeKey()
	})
}

// ClearScopeKey clears the value of the "scope_key" field.
func (u *UxResultSnapshotUpsertOne) ClearScopeKey() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.ClearScopeKey()
	})
}

// SetTotalSessions sets the "total_sessions" field.
func (u *UxResultSnapshotUpsertOne) SetTotalSessions(v int) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetTotalSessions(v)
	})
}

// AddTotalSessions adds v to the "total_sessions" field.
func (u *UxResultSnapshotUpsertOne) AddTotalSessions(v int) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddTotalSessions(v)
	})
}

// UpdateTotalSessions sets the "total_sessions" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateTotalSessions() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateTotalSessions()
	})
}

// SetCompletedSessions sets the "completed_sessions" field.
func (u *UxResultSnapshotUpsertOne) SetCompletedSessions(v int) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetCompletedSessions(v)
	})
}

// AddCompletedSessions adds v to the "completed_sessions" field.
func (u *UxResultSnapshotUpsertOne) AddCompletedSessions(v int) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddCompletedSessions(v)
	})
}

// UpdateCompletedSessions sets the "completed_sessions" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateCompletedSessions() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateCompletedSessions()
	})
}

// SetFailedSessions sets the "failed_sessions" field.
func (u *UxResultSnapshotUpsertOne) SetFailedSessions(v int) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetFailedSessions(v)
	})
}

// AddFailedSessions adds v to the "failed_sessions" field.
func (u *UxResultSnapshotUpsertOne) AddFailedSessions(v int) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddFailedSessions(v)
	})
}

// UpdateFailedSessions sets the "failed_sessions" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateFailedSessions() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateFailedSessions()
	})
}

// SetCompletionRate sets the "completion_rate" field.
func (u *UxResultSnapshotUpsertOne) SetCompletionRate(v float64) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetCompletionRate(v)
	})
}

// AddCompletionRate adds v to the "completion_rate" field.
func (u *UxResultSnapshotUpsertOne) AddCompletionRate(v float64) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddCompletionRate(v)
	})
}

// UpdateCompletionRate sets the "completion_rate" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateCompletionRate() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateCompletionRate()
	})
}

// SetAvgDurationMs sets the "avg_duration_ms" field.
func (u *UxResultSnapshotUpsertOne) SetAvgDurationMs(v int64) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetAvgDurationMs(v)
	})
}

// AddAvgDurationMs adds v to the "avg_duration_ms" field.
func (u *UxResultSnapshotUpsertOne) AddAvgDurationMs(v int64) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddAvgDurationMs(v)
	})
}

// UpdateAvgDurationMs sets the "avg_duration_ms" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateAvgDurationMs() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateAvgDurationMs()
	})
}

// ClearAvgDurationMs clears the value of the "avg_duration_ms" field.
func (u *UxResultSnapshotUpsertOne) ClearAvgDurationMs() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.ClearAvgDurationMs()
	})
}

// SetAvgErrorCount sets the "avg_error_count" field.
func (u *UxResultSnapshotUpsertOne) SetAvgErrorCount(v float64) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetAvgErrorCount(v)
	})
}

// AddAvgErrorCount adds v to the "avg_error_count" field.
func (u *UxResultSnapshotUpsertOne) AddAvgErrorCount(v float64) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddAvgErrorCount(v)
	})
}

// UpdateAvgErrorCount sets the "avg_error_count" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateAvgErrorCount() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateAvgErrorCount()
	})
}

// ClearAvgErrorCount clears the value of the "avg_error_count" field.
func (u *UxResultSnapshotUpsertOne) ClearAvgErrorCount() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.ClearAvgErrorCount()
	})
}

// SetAvgScore sets the "avg_score" field.
func (u *UxResultSnapshotUpsertOne) SetAvgScore(v float64) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetAvgScore(v)
	})
}

// AddAvgScore adds v to the "avg_score" field.
func (u *UxResultSnapshotUpsertOne) AddAvgScore(v float64) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddAvgScore(v)
	})
}

// UpdateAvgScore sets the "avg_score" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateAvgScore() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateAvgScore()
	})
}

// ClearAvgScore clears the value of the "avg_score" field.
func (u *UxResultSnapshotUpsertOne) ClearAvgScore() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.ClearAvgScore()
	})
}

// SetMetricPayload sets the "metric_payload" field.
func (u *UxResultSnapshotUpsertOne) SetMetricPayload(v map[string]interface{}) *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetMetricPayload(v)
	})
}

// UpdateMetricPayload sets the "metric_payload" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertOne) UpdateMetricPayload() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateMetricPayload()
	})
}

// ClearMetricPayload clears the value of the "metric_payload" field.
func (u *UxResultSnapshotUpsertOne) ClearMetricPayload() *UxResultSnapshotUpsertOne {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.ClearMetricPayload()
	})
}

// Exec executes the query.
func (u *UxResultSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UxResultSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UxResultSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UxResultSnapshotUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UxResultSnapshotUpsertOne.ID is not supported by MySQL driver. Use UxResultSnapshotUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UxResultSnapshotUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UxResultSnapshotCreateBulk is the builder for creating many UxResultSnapshot entities in bulk.
type UxResultSnapshotCreateBulk struct {
	config
	err      error
	builders []*UxResultSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the UxResultSnapshot entities in the database.
func (_c *UxResultSnapshotCreateBulk) Save(ctx context.Context) ([]*UxResultSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UxResultSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UxResultSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UxResultSnapshotCreateBulk) SaveX(ctx context.Context) []*UxResultSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UxResultSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UxResultSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UxResultSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UxResultSnapshotUpsert) {
//			SetRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *UxResultSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *UxResultSnapshotUpsertBulk {
	_c.conflict = opts
	return &UxResultSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UxResultSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UxResultSnapshotCreateBulk) OnConflictColumns(columns ...string) *UxResultSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UxResultSnapshotUpsertBulk{
		create: _c,
	}
}

// UxResultSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of UxResultSnapshot nodes.
type UxResultSnapshotUpsertBulk struct {
	create *UxResultSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UxResultSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(uxresultsnapshot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UxResultSnapshotUpsertBulk) UpdateNewValues() *UxResultSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(uxresultsnapshot.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(uxresultsnapshot.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UxResultSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UxResultSnapshotUpsertBulk) Ignore() *UxResultSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UxResultSnapshotUpsertBulk) DoNothing() *UxResultSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UxResultSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *UxResultSnapshotUpsertBulk) Update(set func(*UxResultSnapshotUpsert)) *UxResultSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UxResultSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunID sets the "run_id" field.
func (u *UxResultSnapshotUpsertBulk) SetRunID(v uuid.UUID) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetRunID(v)
	})
}

// UpdateRunID sets the "run_id" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateRunID() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateRunID()
	})
}

// SetBatchID sets the "batch_id" field.
func (u *UxResultSnapshotUpsertBulk) SetBatchID(v string) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateBatchID() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateBatchID()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *UxResultSnapshotUpsertBulk) SetScopeType(v uxresultsnapshot.ScopeType) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateScopeType() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateScopeType()
	})
}

// SetScopeKey sets the "scope_key" field.
func (u *UxResultSnapshotUpsertBulk) SetScopeKey(v uuid.UUID) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetScopeKey(v)
	})
}

// UpdateScopeKey sets the "scope_key" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateScopeKey() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateScopeKey()
	})
}

// ClearScopeKey clears the value of the "scope_key" field.
func (u *UxResultSnapshotUpsertBulk) ClearScopeKey() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.ClearScopeKey()
	})
}

// SetTotalSessions sets the "total_sessions" field.
func (u *UxResultSnapshotUpsertBulk) SetTotalSessions(v int) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetTotalSessions(v)
	})
}

// AddTotalSessions adds v to the "total_sessions" field.
func (u *UxResultSnapshotUpsertBulk) AddTotalSessions(v int) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddTotalSessions(v)
	})
}

// UpdateTotalSessions sets the "total_sessions" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateTotalSessions() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateTotalSessions()
	})
}

// SetCompletedSessions sets the "completed_sessions" field.
func (u *UxResultSnapshotUpsertBulk) SetCompletedSessions(v int) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetCompletedSessions(v)
	})
}

// AddCompletedSessions adds v to the "completed_sessions" field.
func (u *UxResultSnapshotUpsertBulk) AddCompletedSessions(v int) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddCompletedSessions(v)
	})
}

// UpdateCompletedSessions sets the "completed_sessions" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateCompletedSessions() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateCompletedSessions()
	})
}

// SetFailedSessions sets the "failed_sessions" field.
func (u *UxResultSnapshotUpsertBulk) SetFailedSessions(v int) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetFailedSessions(v)
	})
}

// AddFailedSessions adds v to the "failed_sessions" field.
func (u *UxResultSnapshotUpsertBulk) AddFailedSessions(v int) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddFailedSessions(v)
	})
}

// UpdateFailedSessions sets the "failed_sessions" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateFailedSessions() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateFailedSessions()
	})
}

// SetCompletionRate sets the "completion_rate" field.
func (u *UxResultSnapshotUpsertBulk) SetCompletionRate(v float64) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetCompletionRate(v)
	})
}

// AddCompletionRate adds v to the "completion_rate" field.
func (u *UxResultSnapshotUpsertBulk) AddCompletionRate(v float64) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddCompletionRate(v)
	})
}

// UpdateCompletionRate sets the "completion_rate" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateCompletionRate() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateCompletionRate()
	})
}

// SetAvgDurationMs sets the "avg_duration_ms" field.
func (u *UxResultSnapshotUpsertBulk) SetAvgDurationMs(v int64) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetAvgDurationMs(v)
	})
}

// AddAvgDurationMs adds v to the "avg_duration_ms" field.
func (u *UxResultSnapshotUpsertBulk) AddAvgDurationMs(v int64) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddAvgDurationMs(v)
	})
}

// UpdateAvgDurationMs sets the "avg_duration_ms" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateAvgDurationMs() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateAvgDurationMs()
	})
}

// ClearAvgDurationMs clears the value of the "avg_duration_ms" field.
func (u *UxResultSnapshotUpsertBulk) ClearAvgDurationMs() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.ClearAvgDurationMs()
	})
}

// SetAvgErrorCount sets the "avg_error_count" field.
func (u *UxResultSnapshotUpsertBulk) SetAvgErrorCount(v float64) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetAvgErrorCount(v)
	})
}

// AddAvgErrorCount adds v to the "avg_error_count" field.
func (u *UxResultSnapshotUpsertBulk) AddAvgErrorCount(v float64) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddAvgErrorCount(v)
	})
}

// UpdateAvgErrorCount sets the "avg_error_count" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateAvgErrorCount() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateAvgErrorCount()
	})
}

// ClearAvgErrorCount clears the value of the "avg_error_count" field.
func (u *UxResultSnapshotUpsertBulk) ClearAvgErrorCount() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.ClearAvgErrorCount()
	})
}

// SetAvgScore sets the "avg_score" field.
func (u *UxResultSnapshotUpsertBulk) SetAvgScore(v float64) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetAvgScore(v)
	})
}

// AddAvgScore adds v to the "avg_score" field.
func (u *UxResultSnapshotUpsertBulk) AddAvgScore(v float64) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.AddAvgScore(v)
	})
}

// UpdateAvgScore sets the "avg_score" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateAvgScore() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateAvgScore()
	})
}

// ClearAvgScore clears the value of the "avg_score" field.
func (u *UxResultSnapshotUpsertBulk) ClearAvgScore() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.ClearAvgScore()
	})
}

// SetMetricPayload sets the "metric_payload" field.
func (u *UxResultSnapshotUpsertBulk) SetMetricPayload(v map[string]interface{}) *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.SetMetricPayload(v)
	})
}

// UpdateMetricPayload sets the "metric_payload" field to the value that was provided on create.
func (u *UxResultSnapshotUpsertBulk) UpdateMetricPayload() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.UpdateMetricPayload()
	})
}

// ClearMetricPayload clears the value of the "metric_payload" field.
func (u *UxResultSnapshotUpsertBulk) ClearMetricPayload() *UxResultSnapshotUpsertBulk {
	return u.Update(func(s *UxResultSnapshotUpsert) {
		s.ClearMetricPayload()
	})
}

// Exec executes the query.
func (u *UxResultSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UxResultSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UxResultSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UxResultSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
