// Code generated by ent, DO NOT EDIT.

package ent

import (
	"evalux-server/ent/uxexecutionrun"
	"evalux-server/ent/uxruntaskquestionnairesnapshot"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UxRunTaskQuestionnaireSnapshot is the model entity for the UxRunTaskQuestionnaireSnapshot schema.
type UxRunTaskQuestionnaireSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID uuid.UUID `json:"run_id,omitempty"`
	// SourceBindingID holds the value of the "source_binding_id" field.
	SourceBindingID *uuid.UUID `json:"source_binding_id,omitempty"`
	// TaskIDRef holds the value of the "task_id_ref" field.
	TaskIDRef uuid.UUID `json:"task_id_ref,omitempty"`
	// TemplateIDRef holds the value of the "template_id_ref" field.
	TemplateIDRef uuid.UUID `json:"template_id_ref,omitempty"`
	// TemplateNameSnapshot holds the value of the "template_name_snapshot" field.
	TemplateNameSnapshot string `json:"template_name_snapshot,omitempty"`
	// QuestionOrder holds the value of the "question_order" field.
	QuestionOrder int `json:"question_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UxRunTaskQuestionnaireSnapshotQuery when eager-loading is set.
	Edges        UxRunTaskQuestionnaireSnapshotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UxRunTaskQuestionnaireSnapshotEdges holds the relations/edges for other nodes in the graph.
type UxRunTaskQuestionnaireSnapshotEdges struct {
	// Run holds the value of the run edge.
	Run *UxExecutionRun `json:"run,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RunOrErr returns the Run value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UxRunTaskQuestionnaireSnapshotEdges) RunOrErr() (*UxExecutionRun, error) {
	if e.Run != nil {
		return e.Run, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: uxexecutionrun.Label}
	}
	return nil, &NotLoadedError{edge: "run"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UxRunTaskQuestionnaireSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uxruntaskquestionnairesnapshot.FieldSourceBindingID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case uxruntaskquestionnairesnapshot.FieldQuestionOrder:
			values[i] = new(sql.NullInt64)
		case uxruntaskquestionnairesnapshot.FieldTemplateNameSnapshot:
			values[i] = new(sql.NullString)
		case uxruntaskquestionnairesnapshot.FieldID, uxruntaskquestionnairesnapshot.FieldRunID, uxruntaskquestionnairesnapshot.FieldTaskIDRef, uxruntaskquestionnairesnapshot.FieldTemplateIDRef:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UxRunTaskQuestionnaireSnapshot fields.
func (_m *UxRunTaskQuestionnaireSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uxruntaskquestionnairesnapshot.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case uxruntaskquestionnairesnapshot.FieldRunID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value != nil {
				_m.RunID = *value
			}
		case uxruntaskquestionnairesnapshot.FieldSourceBindingID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field source_binding_id", values[i])
			} else if value.Valid {
				_m.SourceBindingID = new(uuid.UUID)
				*_m.SourceBindingID = *value.S.(*uuid.UUID)
			}
		case uxruntaskquestionnairesnapshot.FieldTaskIDRef:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id_ref", values[i])
			} else if value != nil {
				_m.TaskIDRef = *value
			}
		case uxruntaskquestionnairesnapshot.FieldTemplateIDRef:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field template_id_ref", values[i])
			} else if value != nil {
				_m.TemplateIDRef = *value
			}
		case uxruntaskquestionnairesnapshot.FieldTemplateNameSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_name_snapshot", values[i])
			} else if value.Valid {
				_m.TemplateNameSnapshot = value.String
			}
		case uxruntaskquestionnairesnapshot.FieldQuestionOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field question_order", values[i])
			} else if value.Valid {
				_m.QuestionOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UxRunTaskQuestionnaireSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *UxRunTaskQuestionnaireSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRun queries the "run" edge of the UxRunTaskQuestionnaireSnapshot entity.
func (_m *UxRunTaskQuestionnaireSnapshot) QueryRun() *UxExecutionRunQuery {
	return NewUxRunTaskQuestionnaireSnapshotClient(_m.config).QueryRun(_m)
}

// Update returns a builder for updating this UxRunTaskQuestionnaireSnapshot.
// Note that you need to call UxRunTaskQuestionnaireSnapshot.Unwrap() before calling this method if this UxRunTaskQuestionnaireSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UxRunTaskQuestionnaireSnapshot) Update() *UxRunTaskQuestionnaireSnapshotUpdateOne {
	return NewUxRunTaskQuestionnaireSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UxRunTaskQuestionnaireSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UxRunTaskQuestionnaireSnapshot) Unwrap() *UxRunTaskQuestionnaireSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UxRunTaskQuestionnaireSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UxRunTaskQuestionnaireSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("UxRunTaskQuestionnaireSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("run_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RunID))
	builder.WriteString(", ")
	if v := _m.SourceBindingID; v != nil {
		builder.WriteString("source_binding_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("task_id_ref=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskIDRef))
	builder.WriteString(", ")
	builder.WriteString("template_id_ref=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateIDRef))
	builder.WriteString(", ")
	builder.WriteString("template_name_snapshot=")
	builder.WriteString(_m.TemplateNameSnapshot)
	builder.WriteString(", ")
	builder.WriteString("question_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuestionOrder))
	builder.WriteByte(')')
	return builder.String()
}

// UxRunTaskQuestionnaireSnapshots is a parsable slice of UxRunTaskQuestionnaireSnapshot.
type UxRunTaskQuestionnaireSnapshots []*UxRunTaskQuestionnaireSnapshot
