// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"evalux-server/ent/predicate"
	"evalux-server/ent/uxrunquestionnaireoptionsnapshot"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UxRunQuestionnaireOptionSnapshotDelete is the builder for deleting a UxRunQuestionnaireOptionSnapshot entity.
type UxRunQuestionnaireOptionSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *UxRunQuestionnaireOptionSnapshotMutation
}

// Where appends a list predicates to the UxRunQuestionnaireOptionSnapshotDelete builder.
func (_d *UxRunQuestionnaireOptionSnapshotDelete) Where(ps ...predicate.UxRunQuestionnaireOptionSnapshot) *UxRunQuestionnaireOptionSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UxRunQuestionnaireOptionSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UxRunQuestionnaireOptionSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UxRunQuestionnaireOptionSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(uxrunquestionnaireoptionsnapshot.Table, sqlgraph.NewFieldSpec(uxrunquestionnaireoptionsnapshot.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UxRunQuestionnaireOptionSnapshotDeleteOne is the builder for deleting a single UxRunQuestionnaireOptionSnapshot entity.
type UxRunQuestionnaireOptionSnapshotDeleteOne struct {
	_d *UxRunQuestionnaireOptionSnapshotDelete
}

// Where appends a list predicates to the UxRunQuestionnaireOptionSnapshotDelete builder.
func (_d *UxRunQuestionnaireOptionSnapshotDeleteOne) Where(ps ...predicate.UxRunQuestionnaireOptionSnapshot) *UxRunQuestionnaireOptionSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UxRunQuestionnaireOptionSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{uxrunquestionnaireoptionsnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UxRunQuestionnaireOptionSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
