// Code generated by ent, DO NOT EDIT.

package ent

import (
	"evalux-server/ent/uxexecutionrun"
	"evalux-server/ent/uxrunmodelconfig"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UxRunModelConfig is the model entity for the UxRunModelConfig schema.
type UxRunModelConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID uuid.UUID `json:"run_id,omitempty"`
	// ModelRole holds the value of the "model_role" field.
	ModelRole uxrunmodelconfig.ModelRole `json:"model_role,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel string `json:"channel,omitempty"`
	// ModelType holds the value of the "model_type" field.
	ModelType uxrunmodelconfig.ModelType `json:"model_type,omitempty"`
	// ModelName holds the value of the "model_name" field.
	ModelName string `json:"model_name,omitempty"`
	// APIBaseURL holds the value of the "api_base_url" field.
	APIBaseURL *string `json:"api_base_url,omitempty"`
	// APIKeyCipher holds the value of the "api_key_cipher" field.
	APIKeyCipher *string `json:"api_key_cipher,omitempty"`
	// Temperature holds the value of the "temperature" field.
	Temperature *float64 `json:"temperature,omitempty"`
	// TopP holds the value of the "top_p" field.
	TopP *float64 `json:"top_p,omitempty"`
	// MaxTokens holds the value of the "max_tokens" field.
	MaxTokens *int `json:"max_tokens,omitempty"`
	// ReasoningEffort holds the value of the "reasoning_effort" field.
	ReasoningEffort *string `json:"reasoning_effort,omitempty"`
	// ExtraParams holds the value of the "extra_params" field.
	ExtraParams *string `json:"extra_params,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UxRunModelConfigQuery when eager-loading is set.
	Edges        UxRunModelConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UxRunModelConfigEdges holds the relations/edges for other nodes in the graph.
type UxRunModelConfigEdges struct {
	// Run holds the value of the run edge.
	Run *UxExecutionRun `json:"run,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RunOrErr returns the Run value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UxRunModelConfigEdges) RunOrErr() (*UxExecutionRun, error) {
	if e.Run != nil {
		return e.Run, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: uxexecutionrun.Label}
	}
	return nil, &NotLoadedError{edge: "run"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UxRunModelConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uxrunmodelconfig.FieldTemperature, uxrunmodelconfig.FieldTopP:
			values[i] = new(sql.NullFloat64)
		case uxrunmodelconfig.FieldMaxTokens:
			values[i] = new(sql.NullInt64)
		case uxrunmodelconfig.FieldModelRole, uxrunmodelconfig.FieldChannel, uxrunmodelconfig.FieldModelType, uxrunmodelconfig.FieldModelName, uxrunmodelconfig.FieldAPIBaseURL, uxrunmodelconfig.FieldAPIKeyCipher, uxrunmodelconfig.FieldReasoningEffort, uxrunmodelconfig.FieldExtraParams:
			values[i] = new(sql.NullString)
		case uxrunmodelconfig.FieldID, uxrunmodelconfig.FieldRunID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UxRunModelConfig fields.
func (_m *UxRunModelConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uxrunmodelconfig.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case uxrunmodelconfig.FieldRunID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value != nil {
				_m.RunID = *value
			}
		case uxrunmodelconfig.FieldModelRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_role", values[i])
			} else if value.Valid {
				_m.ModelRole = uxrunmodelconfig.ModelRole(value.String)
			}
		case uxrunmodelconfig.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = value.String
			}
		case uxrunmodelconfig.FieldModelType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_type", values[i])
			} else if value.Valid {
				_m.ModelType = uxrunmodelconfig.ModelType(value.String)
			}
		case uxrunmodelconfig.FieldModelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_name", values[i])
			} else if value.Valid {
				_m.ModelName = value.String
			}
		case uxrunmodelconfig.FieldAPIBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_base_url", values[i])
			} else if value.Valid {
				_m.APIBaseURL = new(string)
				*_m.APIBaseURL = value.String
			}
		case uxrunmodelconfig.FieldAPIKeyCipher:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_cipher", values[i])
			} else if value.Valid {
				_m.APIKeyCipher = new(string)
				*_m.APIKeyCipher = value.String
			}
		case uxrunmodelconfig.FieldTemperature:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field temperature", values[i])
			} else if value.Valid {
				_m.Temperature = new(float64)
				*_m.Temperature = value.Float64
			}
		case uxrunmodelconfig.FieldTopP:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field top_p", values[i])
			} else if value.Valid {
				_m.TopP = new(float64)
				*_m.TopP = value.Float64
			}
		case uxrunmodelconfig.FieldMaxTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_tokens", values[i])
			} else if value.Valid {
				_m.MaxTokens = new(int)
				*_m.MaxTokens = int(value.Int64)
			}
		case uxrunmodelconfig.FieldReasoningEffort:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_effort", values[i])
			} else if value.Valid {
				_m.ReasoningEffort = new(string)
				*_m.ReasoningEffort = value.String
			}
		case uxrunmodelconfig.FieldExtraParams:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extra_params", values[i])
			} else if value.Valid {
				_m.ExtraParams = new(string)
				*_m.ExtraParams = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UxRunModelConfig.
// This includes values selected through modifiers, order, etc.
func (_m *UxRunModelConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRun queries the "run" edge of the UxRunModelConfig entity.
func (_m *UxRunModelConfig) QueryRun() *UxExecutionRunQuery {
	return NewUxRunModelConfigClient(_m.config).QueryRun(_m)
}

// Update returns a builder for updating this UxRunModelConfig.
// Note that you need to call UxRunModelConfig.Unwrap() before calling this method if this UxRunModelConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UxRunModelConfig) Update() *UxRunModelConfigUpdateOne {
	return NewUxRunModelConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UxRunModelConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UxRunModelConfig) Unwrap() *UxRunModelConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UxRunModelConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UxRunModelConfig) String() string {
	var builder strings.Builder
	builder.WriteString("UxRunModelConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("run_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RunID))
	builder.WriteString(", ")
	builder.WriteString("model_role=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelRole))
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(_m.Channel)
	builder.WriteString(", ")
	builder.WriteString("model_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelType))
	builder.WriteString(", ")
	builder.WriteString("model_name=")
	builder.WriteString(_m.ModelName)
	builder.WriteString(", ")
	if v := _m.APIBaseURL; v != nil {
		builder.WriteString("api_base_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.APIKeyCipher; v != nil {
		builder.WriteString("api_key_cipher=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Temperature; v != nil {
		builder.WriteString("temperature=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TopP; v != nil {
		builder.WriteString("top_p=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MaxTokens; v != nil {
		builder.WriteString("max_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReasoningEffort; v != nil {
		builder.WriteString("reasoning_effort=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExtraParams; v != nil {
		builder.WriteString("extra_params=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// UxRunModelConfigs is a parsable slice of UxRunModelConfig.
type UxRunModelConfigs []*UxRunModelConfig
