// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"evalux-server/ent/predicate"
	"evalux-server/ent/uxproject"
	"evalux-server/ent/uxtask"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UxTaskUpdate is the builder for updating UxTask entities.
type UxTaskUpdate struct {
	config
	hooks    []Hook
	mutation *UxTaskMutation
}

// Where appends a list predicates to the UxTaskUpdate builder.
func (_u *UxTaskUpdate) Where(ps ...predicate.UxTask) *UxTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *UxTaskUpdate) SetProjectID(v uuid.UUID) *UxTaskUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillableProjectID(v *uuid.UUID) *UxTaskUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTaskName sets the "task_name" field.
func (_u *UxTaskUpdate) SetTaskName(v string) *UxTaskUpdate {
	_u.mutation.SetTaskName(v)
	return _u
}

// SetNillableTaskName sets the "task_name" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillableTaskName(v *string) *UxTaskUpdate {
	if v != nil {
		_u.SetTaskName(*v)
	}
	return _u
}

// SetTaskGoal sets the "task_goal" field.
func (_u *UxTaskUpdate) SetTaskGoal(v string) *UxTaskUpdate {
	_u.mutation.SetTaskGoal(v)
	return _u
}

// SetNillableTaskGoal sets the "task_goal" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillableTaskGoal(v *string) *UxTaskUpdate {
	if v != nil {
		_u.SetTaskGoal(*v)
	}
	return _u
}

// SetPrecondition sets the "precondition" field.
func (_u *UxTaskUpdate) SetPrecondition(v string) *UxTaskUpdate {
	_u.mutation.SetPrecondition(v)
	return _u
}

// SetNillablePrecondition sets the "precondition" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillablePrecondition(v *string) *UxTaskUpdate {
	if v != nil {
		_u.SetPrecondition(*v)
	}
	return _u
}

// ClearPrecondition clears the value of the "precondition" field.
func (_u *UxTaskUpdate) ClearPrecondition() *UxTaskUpdate {
	_u.mutation.ClearPrecondition()
	return _u
}

// SetExecutionGuide sets the "execution_guide" field.
func (_u *UxTaskUpdate) SetExecutionGuide(v string) *UxTaskUpdate {
	_u.mutation.SetExecutionGuide(v)
	return _u
}

// SetNillableExecutionGuide sets the "execution_guide" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillableExecutionGuide(v *string) *UxTaskUpdate {
	if v != nil {
		_u.SetExecutionGuide(*v)
	}
	return _u
}

// ClearExecutionGuide clears the value of the "execution_guide" field.
func (_u *UxTaskUpdate) ClearExecutionGuide() *UxTaskUpdate {
	_u.mutation.ClearExecutionGuide()
	return _u
}

// SetStepConstraints sets the "step_constraints" field.
func (_u *UxTaskUpdate) SetStepConstraints(v []map[string]interface{}) *UxTaskUpdate {
	_u.mutation.SetStepConstraints(v)
	return _u
}

// AppendStepConstraints appends value to the "step_constraints" field.
func (_u *UxTaskUpdate) AppendStepConstraints(v []map[string]interface{}) *UxTaskUpdate {
	_u.mutation.AppendStepConstraints(v)
	return _u
}

// ClearStepConstraints clears the value of the "step_constraints" field.
func (_u *UxTaskUpdate) ClearStepConstraints() *UxTaskUpdate {
	_u.mutation.ClearStepConstraints()
	return _u
}

// SetSuccessCriteria sets the "success_criteria" field.
func (_u *UxTaskUpdate) SetSuccessCriteria(v string) *UxTaskUpdate {
	_u.mutation.SetSuccessCriteria(v)
	return _u
}

// SetNillableSuccessCriteria sets the "success_criteria" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillableSuccessCriteria(v *string) *UxTaskUpdate {
	if v != nil {
		_u.SetSuccessCriteria(*v)
	}
	return _u
}

// SetFailureRule sets the "failure_rule" field.
func (_u *UxTaskUpdate) SetFailureRule(v string) *UxTaskUpdate {
	_u.mutation.SetFailureRule(v)
	return _u
}

// SetNillableFailureRule sets the "failure_rule" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillableFailureRule(v *string) *UxTaskUpdate {
	if v != nil {
		_u.SetFailureRule(*v)
	}
	return _u
}

// ClearFailureRule clears the value of the "failure_rule" field.
func (_u *UxTaskUpdate) ClearFailureRule() *UxTaskUpdate {
	_u.mutation.ClearFailureRule()
	return _u
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_u *UxTaskUpdate) SetTimeoutSeconds(v int) *UxTaskUpdate {
	_u.mutation.ResetTimeoutSeconds()
	_u.mutation.SetTimeoutSeconds(v)
	return _u
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillableTimeoutSeconds(v *int) *UxTaskUpdate {
	if v != nil {
		_u.SetTimeoutSeconds(*v)
	}
	return _u
}

// AddTimeoutSeconds adds value to the "timeout_seconds" field.
func (_u *UxTaskUpdate) AddTimeoutSeconds(v int) *UxTaskUpdate {
	_u.mutation.AddTimeoutSeconds(v)
	return _u
}

// SetMinSteps sets the "min_steps" field.
func (_u *UxTaskUpdate) SetMinSteps(v int) *UxTaskUpdate {
	_u.mutation.ResetMinSteps()
	_u.mutation.SetMinSteps(v)
	return _u
}

// SetNillableMinSteps sets the "min_steps" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillableMinSteps(v *int) *UxTaskUpdate {
	if v != nil {
		_u.SetMinSteps(*v)
	}
	return _u
}

// AddMinSteps adds value to the "min_steps" field.
func (_u *UxTaskUpdate) AddMinSteps(v int) *UxTaskUpdate {
	_u.mutation.AddMinSteps(v)
	return _u
}

// ClearMinSteps clears the value of the "min_steps" field.
func (_u *UxTaskUpdate) ClearMinSteps() *UxTaskUpdate {
	_u.mutation.ClearMinSteps()
	return _u
}

// SetMaxSteps sets the "max_steps" field.
func (_u *UxTaskUpdate) SetMaxSteps(v int) *UxTaskUpdate {
	_u.mutation.ResetMaxSteps()
	_u.mutation.SetMaxSteps(v)
	return _u
}

// SetNillableMaxSteps sets the "max_steps" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillableMaxSteps(v *int) *UxTaskUpdate {
	if v != nil {
		_u.SetMaxSteps(*v)
	}
	return _u
}

// AddMaxSteps adds value to the "max_steps" field.
func (_u *UxTaskUpdate) AddMaxSteps(v int) *UxTaskUpdate {
	_u.mutation.AddMaxSteps(v)
	return _u
}

// ClearMaxSteps clears the value of the "max_steps" field.
func (_u *UxTaskUpdate) ClearMaxSteps() *UxTaskUpdate {
	_u.mutation.ClearMaxSteps()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *UxTaskUpdate) SetSortOrder(v int) *UxTaskUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillableSortOrder(v *int) *UxTaskUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *UxTaskUpdate) AddSortOrder(v int) *UxTaskUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UxTaskUpdate) SetStatus(v uxtask.Status) *UxTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UxTaskUpdate) SetNillableStatus(v *uxtask.Status) *UxTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the UxProject entity.
func (_u *UxTaskUpdate) SetProject(v *UxProject) *UxTaskUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the UxTaskMutation object of the builder.
func (_u *UxTaskUpdate) Mutation() *UxTaskMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the UxProject entity.
func (_u *UxTaskUpdate) ClearProject() *UxTaskUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UxTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UxTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UxTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UxTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UxTaskUpdate) check() error {
	if v, ok := _u.mutation.TaskName(); ok {
		if err := uxtask.TaskNameValidator(v); err != nil {
			return &ValidationError{Name: "task_name", err: fmt.Errorf(`ent: validator failed for field "UxTask.task_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskGoal(); ok {
		if err := uxtask.TaskGoalValidator(v); err != nil {
			return &ValidationError{Name: "task_goal", err: fmt.Errorf(`ent: validator failed for field "UxTask.task_goal": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SuccessCriteria(); ok {
		if err := uxtask.SuccessCriteriaValidator(v); err != nil {
			return &ValidationError{Name: "success_criteria", err: fmt.Errorf(`ent: validator failed for field "UxTask.success_criteria": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := uxtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UxTask.status": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UxTask.project"`)
	}
	return nil
}

func (_u *UxTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uxtask.Table, uxtask.Columns, sqlgraph.NewFieldSpec(uxtask.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskName(); ok {
		_spec.SetField(uxtask.FieldTaskName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskGoal(); ok {
		_spec.SetField(uxtask.FieldTaskGoal, field.TypeString, value)
	}
	if value, ok := _u.mutation.Precondition(); ok {
		_spec.SetField(uxtask.FieldPrecondition, field.TypeString, value)
	}
	if _u.mutation.PreconditionCleared() {
		_spec.ClearField(uxtask.FieldPrecondition, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutionGuide(); ok {
		_spec.SetField(uxtask.FieldExecutionGuide, field.TypeString, value)
	}
	if _u.mutation.ExecutionGuideCleared() {
		_spec.ClearField(uxtask.FieldExecutionGuide, field.TypeString)
	}
	if value, ok := _u.mutation.StepConstraints(); ok {
		_spec.SetField(uxtask.FieldStepConstraints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedStepConstraints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, uxtask.FieldStepConstraints, value)
		})
	}
	if _u.mutation.StepConstraintsCleared() {
		_spec.ClearField(uxtask.FieldStepConstraints, field.TypeJSON)
	}
	if value, ok := _u.mutation.SuccessCriteria(); ok {
		_spec.SetField(uxtask.FieldSuccessCriteria, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureRule(); ok {
		_spec.SetField(uxtask.FieldFailureRule, field.TypeString, value)
	}
	if _u.mutation.FailureRuleCleared() {
		_spec.ClearField(uxtask.FieldFailureRule, field.TypeString)
	}
	if value, ok := _u.mutation.TimeoutSeconds(); ok {
		_spec.SetField(uxtask.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutSeconds(); ok {
		_spec.AddField(uxtask.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinSteps(); ok {
		_spec.SetField(uxtask.FieldMinSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinSteps(); ok {
		_spec.AddField(uxtask.FieldMinSteps, field.TypeInt, value)
	}
	if _u.mutation.MinStepsCleared() {
		_spec.ClearField(uxtask.FieldMinSteps, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxSteps(); ok {
		_spec.SetField(uxtask.FieldMaxSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxSteps(); ok {
		_spec.AddField(uxtask.FieldMaxSteps, field.TypeInt, value)
	}
	if _u.mutation.MaxStepsCleared() {
		_spec.ClearField(uxtask.FieldMaxSteps, field.TypeInt)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(uxtask.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(uxtask.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(uxtask.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uxtask.ProjectTable,
			Columns: []string{uxtask.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxproject.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uxtask.ProjectTable,
			Columns: []string{uxtask.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxproject.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uxtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UxTaskUpdateOne is the builder for updating a single UxTask entity.
type UxTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UxTaskMutation
}

// SetProjectID sets the "project_id" field.
func (_u *UxTaskUpdateOne) SetProjectID(v uuid.UUID) *UxTaskUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillableProjectID(v *uuid.UUID) *UxTaskUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTaskName sets the "task_name" field.
func (_u *UxTaskUpdateOne) SetTaskName(v string) *UxTaskUpdateOne {
	_u.mutation.SetTaskName(v)
	return _u
}

// SetNillableTaskName sets the "task_name" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillableTaskName(v *string) *UxTaskUpdateOne {
	if v != nil {
		_u.SetTaskName(*v)
	}
	return _u
}

// SetTaskGoal sets the "task_goal" field.
func (_u *UxTaskUpdateOne) SetTaskGoal(v string) *UxTaskUpdateOne {
	_u.mutation.SetTaskGoal(v)
	return _u
}

// SetNillableTaskGoal sets the "task_goal" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillableTaskGoal(v *string) *UxTaskUpdateOne {
	if v != nil {
		_u.SetTaskGoal(*v)
	}
	return _u
}

// SetPrecondition sets the "precondition" field.
func (_u *UxTaskUpdateOne) SetPrecondition(v string) *UxTaskUpdateOne {
	_u.mutation.SetPrecondition(v)
	return _u
}

// SetNillablePrecondition sets the "precondition" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillablePrecondition(v *string) *UxTaskUpdateOne {
	if v != nil {
		_u.SetPrecondition(*v)
	}
	return _u
}

// ClearPrecondition clears the value of the "precondition" field.
func (_u *UxTaskUpdateOne) ClearPrecondition() *UxTaskUpdateOne {
	_u.mutation.ClearPrecondition()
	return _u
}

// SetExecutionGuide sets the "execution_guide" field.
func (_u *UxTaskUpdateOne) SetExecutionGuide(v string) *UxTaskUpdateOne {
	_u.mutation.SetExecutionGuide(v)
	return _u
}

// SetNillableExecutionGuide sets the "execution_guide" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillableExecutionGuide(v *string) *UxTaskUpdateOne {
	if v != nil {
		_u.SetExecutionGuide(*v)
	}
	return _u
}

// ClearExecutionGuide clears the value of the "execution_guide" field.
func (_u *UxTaskUpdateOne) ClearExecutionGuide() *UxTaskUpdateOne {
	_u.mutation.ClearExecutionGuide()
	return _u
}

// SetStepConstraints sets the "step_constraints" field.
func (_u *UxTaskUpdateOne) SetStepConstraints(v []map[string]interface{}) *UxTaskUpdateOne {
	_u.mutation.SetStepConstraints(v)
	return _u
}

// AppendStepConstraints appends value to the "step_constraints" field.
func (_u *UxTaskUpdateOne) AppendStepConstraints(v []map[string]interface{}) *UxTaskUpdateOne {
	_u.mutation.AppendStepConstraints(v)
	return _u
}

// ClearStepConstraints clears the value of the "step_constraints" field.
func (_u *UxTaskUpdateOne) ClearStepConstraints() *UxTaskUpdateOne {
	_u.mutation.ClearStepConstraints()
	return _u
}

// SetSuccessCriteria sets the "success_criteria" field.
func (_u *UxTaskUpdateOne) SetSuccessCriteria(v string) *UxTaskUpdateOne {
	_u.mutation.SetSuccessCriteria(v)
	return _u
}

// SetNillableSuccessCriteria sets the "success_criteria" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillableSuccessCriteria(v *string) *UxTaskUpdateOne {
	if v != nil {
		_u.SetSuccessCriteria(*v)
	}
	return _u
}

// SetFailureRule sets the "failure_rule" field.
func (_u *UxTaskUpdateOne) SetFailureRule(v string) *UxTaskUpdateOne {
	_u.mutation.SetFailureRule(v)
	return _u
}

// SetNillableFailureRule sets the "failure_rule" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillableFailureRule(v *string) *UxTaskUpdateOne {
	if v != nil {
		_u.SetFailureRule(*v)
	}
	return _u
}

// ClearFailureRule clears the value of the "failure_rule" field.
func (_u *UxTaskUpdateOne) ClearFailureRule() *UxTaskUpdateOne {
	_u.mutation.ClearFailureRule()
	return _u
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (_u *UxTaskUpdateOne) SetTimeoutSeconds(v int) *UxTaskUpdateOne {
	_u.mutation.ResetTimeoutSeconds()
	_u.mutation.SetTimeoutSeconds(v)
	return _u
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillableTimeoutSeconds(v *int) *UxTaskUpdateOne {
	if v != nil {
		_u.SetTimeoutSeconds(*v)
	}
	return _u
}

// AddTimeoutSeconds adds value to the "timeout_seconds" field.
func (_u *UxTaskUpdateOne) AddTimeoutSeconds(v int) *UxTaskUpdateOne {
	_u.mutation.AddTimeoutSeconds(v)
	return _u
}

// SetMinSteps sets the "min_steps" field.
func (_u *UxTaskUpdateOne) SetMinSteps(v int) *UxTaskUpdateOne {
	_u.mutation.ResetMinSteps()
	_u.mutation.SetMinSteps(v)
	return _u
}

// SetNillableMinSteps sets the "min_steps" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillableMinSteps(v *int) *UxTaskUpdateOne {
	if v != nil {
		_u.SetMinSteps(*v)
	}
	return _u
}

// AddMinSteps adds value to the "min_steps" field.
func (_u *UxTaskUpdateOne) AddMinSteps(v int) *UxTaskUpdateOne {
	_u.mutation.AddMinSteps(v)
	return _u
}

// ClearMinSteps clears the value of the "min_steps" field.
func (_u *UxTaskUpdateOne) ClearMinSteps() *UxTaskUpdateOne {
	_u.mutation.ClearMinSteps()
	return _u
}

// SetMaxSteps sets the "max_steps" field.
func (_u *UxTaskUpdateOne) SetMaxSteps(v int) *UxTaskUpdateOne {
	_u.mutation.ResetMaxSteps()
	_u.mutation.SetMaxSteps(v)
	return _u
}

// SetNillableMaxSteps sets the "max_steps" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillableMaxSteps(v *int) *UxTaskUpdateOne {
	if v != nil {
		_u.SetMaxSteps(*v)
	}
	return _u
}

// AddMaxSteps adds value to the "max_steps" field.
func (_u *UxTaskUpdateOne) AddMaxSteps(v int) *UxTaskUpdateOne {
	_u.mutation.AddMaxSteps(v)
	return _u
}

// ClearMaxSteps clears the value of the "max_steps" field.
func (_u *UxTaskUpdateOne) ClearMaxSteps() *UxTaskUpdateOne {
	_u.mutation.ClearMaxSteps()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *UxTaskUpdateOne) SetSortOrder(v int) *UxTaskUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillableSortOrder(v *int) *UxTaskUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *UxTaskUpdateOne) AddSortOrder(v int) *UxTaskUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UxTaskUpdateOne) SetStatus(v uxtask.Status) *UxTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UxTaskUpdateOne) SetNillableStatus(v *uxtask.Status) *UxTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the UxProject entity.
func (_u *UxTaskUpdateOne) SetProject(v *UxProject) *UxTaskUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the UxTaskMutation object of the builder.
func (_u *UxTaskUpdateOne) Mutation() *UxTaskMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the UxProject entity.
func (_u *UxTaskUpdateOne) ClearProject() *UxTaskUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the UxTaskUpdate builder.
func (_u *UxTaskUpdateOne) Where(ps ...predicate.UxTask) *UxTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UxTaskUpdateOne) Select(field string, fields ...string) *UxTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UxTask entity.
func (_u *UxTaskUpdateOne) Save(ctx context.Context) (*UxTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UxTaskUpdateOne) SaveX(ctx context.Context) *UxTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UxTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UxTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UxTaskUpdateOne) check() error {
	if v, ok := _u.mutation.TaskName(); ok {
		if err := uxtask.TaskNameValidator(v); err != nil {
			return &ValidationError{Name: "task_name", err: fmt.Errorf(`ent: validator failed for field "UxTask.task_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskGoal(); ok {
		if err := uxtask.TaskGoalValidator(v); err != nil {
			return &ValidationError{Name: "task_goal", err: fmt.Errorf(`ent: validator failed for field "UxTask.task_goal": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SuccessCriteria(); ok {
		if err := uxtask.SuccessCriteriaValidator(v); err != nil {
			return &ValidationError{Name: "success_criteria", err: fmt.Errorf(`ent: validator failed for field "UxTask.success_criteria": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := uxtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UxTask.status": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UxTask.project"`)
	}
	return nil
}

func (_u *UxTaskUpdateOne) sqlSave(ctx context.Context) (_node *UxTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uxtask.Table, uxtask.Columns, sqlgraph.NewFieldSpec(uxtask.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UxTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uxtask.FieldID)
		for _, f := range fields {
			if !uxtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != uxtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskName(); ok {
		_spec.SetField(uxtask.FieldTaskName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskGoal(); ok {
		_spec.SetField(uxtask.FieldTaskGoal, field.TypeString, value)
	}
	if value, ok := _u.mutation.Precondition(); ok {
		_spec.SetField(uxtask.FieldPrecondition, field.TypeString, value)
	}
	if _u.mutation.PreconditionCleared() {
		_spec.ClearField(uxtask.FieldPrecondition, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutionGuide(); ok {
		_spec.SetField(uxtask.FieldExecutionGuide, field.TypeString, value)
	}
	if _u.mutation.ExecutionGuideCleared() {
		_spec.ClearField(uxtask.FieldExecutionGuide, field.TypeString)
	}
	if value, ok := _u.mutation.StepConstraints(); ok {
		_spec.SetField(uxtask.FieldStepConstraints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedStepConstraints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, uxtask.FieldStepConstraints, value)
		})
	}
	if _u.mutation.StepConstraintsCleared() {
		_spec.ClearField(uxtask.FieldStepConstraints, field.TypeJSON)
	}
	if value, ok := _u.mutation.SuccessCriteria(); ok {
		_spec.SetField(uxtask.FieldSuccessCriteria, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureRule(); ok {
		_spec.SetField(uxtask.FieldFailureRule, field.TypeString, value)
	}
	if _u.mutation.FailureRuleCleared() {
		_spec.ClearField(uxtask.FieldFailureRule, field.TypeString)
	}
	if value, ok := _u.mutation.TimeoutSeconds(); ok {
		_spec.SetField(uxtask.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutSeconds(); ok {
		_spec.AddField(uxtask.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MinSteps(); ok {
		_spec.SetField(uxtask.FieldMinSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinSteps(); ok {
		_spec.AddField(uxtask.FieldMinSteps, field.TypeInt, value)
	}
	if _u.mutation.MinStepsCleared() {
		_spec.ClearField(uxtask.FieldMinSteps, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxSteps(); ok {
		_spec.SetField(uxtask.FieldMaxSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxSteps(); ok {
		_spec.AddField(uxtask.FieldMaxSteps, field.TypeInt, value)
	}
	if _u.mutation.MaxStepsCleared() {
		_spec.ClearField(uxtask.FieldMaxSteps, field.TypeInt)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(uxtask.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(uxtask.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(uxtask.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uxtask.ProjectTable,
			Columns: []string{uxtask.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxproject.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uxtask.ProjectTable,
			Columns: []string{uxtask.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uxproject.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UxTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uxtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
