// Code generated by ent, DO NOT EDIT.

package uxrunmodelconfig

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the uxrunmodelconfig type in the database.
	Label = "ux_run_model_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "config_id"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldModelRole holds the string denoting the model_role field in the database.
	FieldModelRole = "model_role"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldModelType holds the string denoting the model_type field in the database.
	FieldModelType = "model_type"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldAPIBaseURL holds the string denoting the api_base_url field in the database.
	FieldAPIBaseURL = "api_base_url"
	// FieldAPIKeyCipher holds the string denoting the api_key_cipher field in the database.
	FieldAPIKeyCipher = "api_key_cipher"
	// FieldTemperature holds the string denoting the temperature field in the database.
	FieldTemperature = "temperature"
	// FieldTopP holds the string denoting the top_p field in the database.
	FieldTopP = "top_p"
	// FieldMaxTokens holds the string denoting the max_tokens field in the database.
	FieldMaxTokens = "max_tokens"
	// FieldReasoningEffort holds the string denoting the reasoning_effort field in the database.
	FieldReasoningEffort = "reasoning_effort"
	// FieldExtraParams holds the string denoting the extra_params field in the database.
	FieldExtraParams = "extra_params"
	// EdgeRun holds the string denoting the run edge name in mutations.
	EdgeRun = "run"
	// UxExecutionRunFieldID holds the string denoting the ID field of the UxExecutionRun.
	UxExecutionRunFieldID = "run_id"
	// Table holds the table name of the uxrunmodelconfig in the database.
	Table = "ux_run_model_config"
	// RunTable is the table that holds the run relation/edge.
	RunTable = "ux_run_model_config"
	// RunInverseTable is the table name for the UxExecutionRun entity.
	// It exists in this package in order to avoid circular dependency with the "uxexecutionrun" package.
	RunInverseTable = "ux_execution_run"
	// RunColumn is the table column denoting the run relation/edge.
	RunColumn = "run_id"
)

// Columns holds all SQL columns for uxrunmodelconfig fields.
var Columns = []string{
	FieldID,
	FieldRunID,
	FieldModelRole,
	FieldChannel,
	FieldModelType,
	FieldModelName,
	FieldAPIBaseURL,
	FieldAPIKeyCipher,
	FieldTemperature,
	FieldTopP,
	FieldMaxTokens,
	FieldReasoningEffort,
	FieldExtraParams,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	ChannelValidator func(string) error
	// ModelNameValidator is a validator for the "model_name" field. It is called by the builders before save.
	ModelNameValidator func(string) error
	// APIBaseURLValidator is a validator for the "api_base_url" field. It is called by the builders before save.
	APIBaseURLValidator func(string) error
	// APIKeyCipherValidator is a validator for the "api_key_cipher" field. It is called by the builders before save.
	APIKeyCipherValidator func(string) error
	// ReasoningEffortValidator is a validator for the "reasoning_effort" field. It is called by the builders before save.
	ReasoningEffortValidator func(string) error
	// ExtraParamsValidator is a validator for the "extra_params" field. It is called by the builders before save.
	ExtraParamsValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ModelRole defines the type for the "model_role" enum field.
type ModelRole string

// ModelRoleCONTROL is the default value of the ModelRole enum.
const DefaultModelRole = ModelRoleCONTROL

// ModelRole values.
const (
	ModelRoleCONTROL   ModelRole = "CONTROL"
	ModelRoleTREATMENT ModelRole = "TREATMENT"
)

func (mr ModelRole) String() string {
	return string(mr)
}

// ModelRoleValidator is a validator for the "model_role" field enum values. It is called by the builders before save.
func ModelRoleValidator(mr ModelRole) error {
	switch mr {
	case ModelRoleCONTROL, ModelRoleTREATMENT:
		return nil
	default:
		return fmt.Errorf("uxrunmodelconfig: invalid enum value for model_role field: %q", mr)
	}
}

// ModelType defines the type for the "model_type" enum field.
type ModelType string

// ModelTypeMultimodal is the default value of the ModelType enum.
const DefaultModelType = ModelTypeMultimodal

// ModelType values.
const (
	ModelTypeMultimodal ModelType = "multimodal"
	ModelTypeText       ModelType = "text"
)

func (mt ModelType) String() string {
	return string(mt)
}

// ModelTypeValidator is a validator for the "model_type" field enum values. It is called by the builders before save.
func ModelTypeValidator(mt ModelType) error {
	switch mt {
	case ModelTypeMultimodal, ModelTypeText:
		return nil
	default:
		return fmt.Errorf("uxrunmodelconfig: invalid enum value for model_type field: %q", mt)
	}
}

// OrderOption defines the ordering options for the UxRunModelConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByModelRole orders the results by the model_role field.
func ByModelRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelRole, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByModelType orders the results by the model_type field.
func ByModelType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelType, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByAPIBaseURL orders the results by the api_base_url field.
func ByAPIBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIBaseURL, opts...).ToFunc()
}

// ByAPIKeyCipher orders the results by the api_key_cipher field.
func ByAPIKeyCipher(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyCipher, opts...).ToFunc()
}

// ByTemperature orders the results by the temperature field.
func ByTemperature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemperature, opts...).ToFunc()
}

// ByTopP orders the results by the top_p field.
func ByTopP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopP, opts...).ToFunc()
}

// ByMaxTokens orders the results by the max_tokens field.
func ByMaxTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxTokens, opts...).ToFunc()
}

// ByReasoningEffort orders the results by the reasoning_effort field.
func ByReasoningEffort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoningEffort, opts...).ToFunc()
}

// ByExtraParams orders the results by the extra_params field.
func ByExtraParams(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtraParams, opts...).ToFunc()
}

// ByRunField orders the results by run field.
func ByRunField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRunStep(), sql.OrderByField(field, opts...))
	}
}
func newRunStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RunInverseTable, UxExecutionRunFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RunTable, RunColumn),
	)
}
