// Code generated by ent, DO NOT EDIT.

package uxrunmodelconfig

import (
	"evalux-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLTE(FieldID, id))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldRunID, v))
}

// Channel applies equality check predicate on the "channel" field. It's identical to ChannelEQ.
func Channel(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldChannel, v))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldModelName, v))
}

// APIBaseURL applies equality check predicate on the "api_base_url" field. It's identical to APIBaseURLEQ.
func APIBaseURL(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldAPIBaseURL, v))
}

// APIKeyCipher applies equality check predicate on the "api_key_cipher" field. It's identical to APIKeyCipherEQ.
func APIKeyCipher(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldAPIKeyCipher, v))
}

// Temperature applies equality check predicate on the "temperature" field. It's identical to TemperatureEQ.
func Temperature(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldTemperature, v))
}

// TopP applies equality check predicate on the "top_p" field. It's identical to TopPEQ.
func TopP(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldTopP, v))
}

// MaxTokens applies equality check predicate on the "max_tokens" field. It's identical to MaxTokensEQ.
func MaxTokens(v int) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldMaxTokens, v))
}

// ReasoningEffort applies equality check predicate on the "reasoning_effort" field. It's identical to ReasoningEffortEQ.
func ReasoningEffort(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldReasoningEffort, v))
}

// ExtraParams applies equality check predicate on the "extra_params" field. It's identical to ExtraParamsEQ.
func ExtraParams(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldExtraParams, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...uuid.UUID) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldRunID, vs...))
}

// ModelRoleEQ applies the EQ predicate on the "model_role" field.
func ModelRoleEQ(v ModelRole) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldModelRole, v))
}

// ModelRoleNEQ applies the NEQ predicate on the "model_role" field.
func ModelRoleNEQ(v ModelRole) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldModelRole, v))
}

// ModelRoleIn applies the In predicate on the "model_role" field.
func ModelRoleIn(vs ...ModelRole) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldModelRole, vs...))
}

// ModelRoleNotIn applies the NotIn predicate on the "model_role" field.
func ModelRoleNotIn(vs ...ModelRole) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldModelRole, vs...))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldChannel, vs...))
}

// ChannelGT applies the GT predicate on the "channel" field.
func ChannelGT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGT(FieldChannel, v))
}

// ChannelGTE applies the GTE predicate on the "channel" field.
func ChannelGTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGTE(FieldChannel, v))
}

// ChannelLT applies the LT predicate on the "channel" field.
func ChannelLT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLT(FieldChannel, v))
}

// ChannelLTE applies the LTE predicate on the "channel" field.
func ChannelLTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLTE(FieldChannel, v))
}

// ChannelContains applies the Contains predicate on the "channel" field.
func ChannelContains(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContains(FieldChannel, v))
}

// ChannelHasPrefix applies the HasPrefix predicate on the "channel" field.
func ChannelHasPrefix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasPrefix(FieldChannel, v))
}

// ChannelHasSuffix applies the HasSuffix predicate on the "channel" field.
func ChannelHasSuffix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasSuffix(FieldChannel, v))
}

// ChannelEqualFold applies the EqualFold predicate on the "channel" field.
func ChannelEqualFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEqualFold(FieldChannel, v))
}

// ChannelContainsFold applies the ContainsFold predicate on the "channel" field.
func ChannelContainsFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContainsFold(FieldChannel, v))
}

// ModelTypeEQ applies the EQ predicate on the "model_type" field.
func ModelTypeEQ(v ModelType) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldModelType, v))
}

// ModelTypeNEQ applies the NEQ predicate on the "model_type" field.
func ModelTypeNEQ(v ModelType) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldModelType, v))
}

// ModelTypeIn applies the In predicate on the "model_type" field.
func ModelTypeIn(vs ...ModelType) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldModelType, vs...))
}

// ModelTypeNotIn applies the NotIn predicate on the "model_type" field.
func ModelTypeNotIn(vs ...ModelType) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldModelType, vs...))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContainsFold(FieldModelName, v))
}

// APIBaseURLEQ applies the EQ predicate on the "api_base_url" field.
func APIBaseURLEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldAPIBaseURL, v))
}

// APIBaseURLNEQ applies the NEQ predicate on the "api_base_url" field.
func APIBaseURLNEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldAPIBaseURL, v))
}

// APIBaseURLIn applies the In predicate on the "api_base_url" field.
func APIBaseURLIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldAPIBaseURL, vs...))
}

// APIBaseURLNotIn applies the NotIn predicate on the "api_base_url" field.
func APIBaseURLNotIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldAPIBaseURL, vs...))
}

// APIBaseURLGT applies the GT predicate on the "api_base_url" field.
func APIBaseURLGT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGT(FieldAPIBaseURL, v))
}

// APIBaseURLGTE applies the GTE predicate on the "api_base_url" field.
func APIBaseURLGTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGTE(FieldAPIBaseURL, v))
}

// APIBaseURLLT applies the LT predicate on the "api_base_url" field.
func APIBaseURLLT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLT(FieldAPIBaseURL, v))
}

// APIBaseURLLTE applies the LTE predicate on the "api_base_url" field.
func APIBaseURLLTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLTE(FieldAPIBaseURL, v))
}

// APIBaseURLContains applies the Contains predicate on the "api_base_url" field.
func APIBaseURLContains(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContains(FieldAPIBaseURL, v))
}

// APIBaseURLHasPrefix applies the HasPrefix predicate on the "api_base_url" field.
func APIBaseURLHasPrefix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasPrefix(FieldAPIBaseURL, v))
}

// APIBaseURLHasSuffix applies the HasSuffix predicate on the "api_base_url" field.
func APIBaseURLHasSuffix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasSuffix(FieldAPIBaseURL, v))
}

// APIBaseURLIsNil applies the IsNil predicate on the "api_base_url" field.
func APIBaseURLIsNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIsNull(FieldAPIBaseURL))
}

// APIBaseURLNotNil applies the NotNil predicate on the "api_base_url" field.
func APIBaseURLNotNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotNull(FieldAPIBaseURL))
}

// APIBaseURLEqualFold applies the EqualFold predicate on the "api_base_url" field.
func APIBaseURLEqualFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEqualFold(FieldAPIBaseURL, v))
}

// APIBaseURLContainsFold applies the ContainsFold predicate on the "api_base_url" field.
func APIBaseURLContainsFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContainsFold(FieldAPIBaseURL, v))
}

// APIKeyCipherEQ applies the EQ predicate on the "api_key_cipher" field.
func APIKeyCipherEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldAPIKeyCipher, v))
}

// APIKeyCipherNEQ applies the NEQ predicate on the "api_key_cipher" field.
func APIKeyCipherNEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldAPIKeyCipher, v))
}

// APIKeyCipherIn applies the In predicate on the "api_key_cipher" field.
func APIKeyCipherIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldAPIKeyCipher, vs...))
}

// APIKeyCipherNotIn applies the NotIn predicate on the "api_key_cipher" field.
func APIKeyCipherNotIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldAPIKeyCipher, vs...))
}

// APIKeyCipherGT applies the GT predicate on the "api_key_cipher" field.
func APIKeyCipherGT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGT(FieldAPIKeyCipher, v))
}

// APIKeyCipherGTE applies the GTE predicate on the "api_key_cipher" field.
func APIKeyCipherGTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGTE(FieldAPIKeyCipher, v))
}

// APIKeyCipherLT applies the LT predicate on the "api_key_cipher" field.
func APIKeyCipherLT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLT(FieldAPIKeyCipher, v))
}

// APIKeyCipherLTE applies the LTE predicate on the "api_key_cipher" field.
func APIKeyCipherLTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLTE(FieldAPIKeyCipher, v))
}

// APIKeyCipherContains applies the Contains predicate on the "api_key_cipher" field.
func APIKeyCipherContains(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContains(FieldAPIKeyCipher, v))
}

// APIKeyCipherHasPrefix applies the HasPrefix predicate on the "api_key_cipher" field.
func APIKeyCipherHasPrefix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasPrefix(FieldAPIKeyCipher, v))
}

// APIKeyCipherHasSuffix applies the HasSuffix predicate on the "api_key_cipher" field.
func APIKeyCipherHasSuffix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasSuffix(FieldAPIKeyCipher, v))
}

// APIKeyCipherIsNil applies the IsNil predicate on the "api_key_cipher" field.
func APIKeyCipherIsNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIsNull(FieldAPIKeyCipher))
}

// APIKeyCipherNotNil applies the NotNil predicate on the "api_key_cipher" field.
func APIKeyCipherNotNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotNull(FieldAPIKeyCipher))
}

// APIKeyCipherEqualFold applies the EqualFold predicate on the "api_key_cipher" field.
func APIKeyCipherEqualFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEqualFold(FieldAPIKeyCipher, v))
}

// APIKeyCipherContainsFold applies the ContainsFold predicate on the "api_key_cipher" field.
func APIKeyCipherContainsFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContainsFold(FieldAPIKeyCipher, v))
}

// TemperatureEQ applies the EQ predicate on the "temperature" field.
func TemperatureEQ(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldTemperature, v))
}

// TemperatureNEQ applies the NEQ predicate on the "temperature" field.
func TemperatureNEQ(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldTemperature, v))
}

// TemperatureIn applies the In predicate on the "temperature" field.
func TemperatureIn(vs ...float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldTemperature, vs...))
}

// TemperatureNotIn applies the NotIn predicate on the "temperature" field.
func TemperatureNotIn(vs ...float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldTemperature, vs...))
}

// TemperatureGT applies the GT predicate on the "temperature" field.
func TemperatureGT(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGT(FieldTemperature, v))
}

// TemperatureGTE applies the GTE predicate on the "temperature" field.
func TemperatureGTE(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGTE(FieldTemperature, v))
}

// TemperatureLT applies the LT predicate on the "temperature" field.
func TemperatureLT(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLT(FieldTemperature, v))
}

// TemperatureLTE applies the LTE predicate on the "temperature" field.
func TemperatureLTE(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLTE(FieldTemperature, v))
}

// TemperatureIsNil applies the IsNil predicate on the "temperature" field.
func TemperatureIsNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIsNull(FieldTemperature))
}

// TemperatureNotNil applies the NotNil predicate on the "temperature" field.
func TemperatureNotNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotNull(FieldTemperature))
}

// TopPEQ applies the EQ predicate on the "top_p" field.
func TopPEQ(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldTopP, v))
}

// TopPNEQ applies the NEQ predicate on the "top_p" field.
func TopPNEQ(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldTopP, v))
}

// TopPIn applies the In predicate on the "top_p" field.
func TopPIn(vs ...float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldTopP, vs...))
}

// TopPNotIn applies the NotIn predicate on the "top_p" field.
func TopPNotIn(vs ...float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldTopP, vs...))
}

// TopPGT applies the GT predicate on the "top_p" field.
func TopPGT(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGT(FieldTopP, v))
}

// TopPGTE applies the GTE predicate on the "top_p" field.
func TopPGTE(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGTE(FieldTopP, v))
}

// TopPLT applies the LT predicate on the "top_p" field.
func TopPLT(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLT(FieldTopP, v))
}

// TopPLTE applies the LTE predicate on the "top_p" field.
func TopPLTE(v float64) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLTE(FieldTopP, v))
}

// TopPIsNil applies the IsNil predicate on the "top_p" field.
func TopPIsNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIsNull(FieldTopP))
}

// TopPNotNil applies the NotNil predicate on the "top_p" field.
func TopPNotNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotNull(FieldTopP))
}

// MaxTokensEQ applies the EQ predicate on the "max_tokens" field.
func MaxTokensEQ(v int) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldMaxTokens, v))
}

// MaxTokensNEQ applies the NEQ predicate on the "max_tokens" field.
func MaxTokensNEQ(v int) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldMaxTokens, v))
}

// MaxTokensIn applies the In predicate on the "max_tokens" field.
func MaxTokensIn(vs ...int) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldMaxTokens, vs...))
}

// MaxTokensNotIn applies the NotIn predicate on the "max_tokens" field.
func MaxTokensNotIn(vs ...int) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldMaxTokens, vs...))
}

// MaxTokensGT applies the GT predicate on the "max_tokens" field.
func MaxTokensGT(v int) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGT(FieldMaxTokens, v))
}

// MaxTokensGTE applies the GTE predicate on the "max_tokens" field.
func MaxTokensGTE(v int) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGTE(FieldMaxTokens, v))
}

// MaxTokensLT applies the LT predicate on the "max_tokens" field.
func MaxTokensLT(v int) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLT(FieldMaxTokens, v))
}

// MaxTokensLTE applies the LTE predicate on the "max_tokens" field.
func MaxTokensLTE(v int) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLTE(FieldMaxTokens, v))
}

// MaxTokensIsNil applies the IsNil predicate on the "max_tokens" field.
func MaxTokensIsNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIsNull(FieldMaxTokens))
}

// MaxTokensNotNil applies the NotNil predicate on the "max_tokens" field.
func MaxTokensNotNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotNull(FieldMaxTokens))
}

// ReasoningEffortEQ applies the EQ predicate on the "reasoning_effort" field.
func ReasoningEffortEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldReasoningEffort, v))
}

// ReasoningEffortNEQ applies the NEQ predicate on the "reasoning_effort" field.
func ReasoningEffortNEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldReasoningEffort, v))
}

// ReasoningEffortIn applies the In predicate on the "reasoning_effort" field.
func ReasoningEffortIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldReasoningEffort, vs...))
}

// ReasoningEffortNotIn applies the NotIn predicate on the "reasoning_effort" field.
func ReasoningEffortNotIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldReasoningEffort, vs...))
}

// ReasoningEffortGT applies the GT predicate on the "reasoning_effort" field.
func ReasoningEffortGT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGT(FieldReasoningEffort, v))
}

// ReasoningEffortGTE applies the GTE predicate on the "reasoning_effort" field.
func ReasoningEffortGTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGTE(FieldReasoningEffort, v))
}

// ReasoningEffortLT applies the LT predicate on the "reasoning_effort" field.
func ReasoningEffortLT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLT(FieldReasoningEffort, v))
}

// ReasoningEffortLTE applies the LTE predicate on the "reasoning_effort" field.
func ReasoningEffortLTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLTE(FieldReasoningEffort, v))
}

// ReasoningEffortContains applies the Contains predicate on the "reasoning_effort" field.
func ReasoningEffortContains(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContains(FieldReasoningEffort, v))
}

// ReasoningEffortHasPrefix applies the HasPrefix predicate on the "reasoning_effort" field.
func ReasoningEffortHasPrefix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasPrefix(FieldReasoningEffort, v))
}

// ReasoningEffortHasSuffix applies the HasSuffix predicate on the "reasoning_effort" field.
func ReasoningEffortHasSuffix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasSuffix(FieldReasoningEffort, v))
}

// ReasoningEffortIsNil applies the IsNil predicate on the "reasoning_effort" field.
func ReasoningEffortIsNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIsNull(FieldReasoningEffort))
}

// ReasoningEffortNotNil applies the NotNil predicate on the "reasoning_effort" field.
func ReasoningEffortNotNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotNull(FieldReasoningEffort))
}

// ReasoningEffortEqualFold applies the EqualFold predicate on the "reasoning_effort" field.
func ReasoningEffortEqualFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEqualFold(FieldReasoningEffort, v))
}

// ReasoningEffortContainsFold applies the ContainsFold predicate on the "reasoning_effort" field.
func ReasoningEffortContainsFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContainsFold(FieldReasoningEffort, v))
}

// ExtraParamsEQ applies the EQ predicate on the "extra_params" field.
func ExtraParamsEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEQ(FieldExtraParams, v))
}

// ExtraParamsNEQ applies the NEQ predicate on the "extra_params" field.
func ExtraParamsNEQ(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNEQ(FieldExtraParams, v))
}

// ExtraParamsIn applies the In predicate on the "extra_params" field.
func ExtraParamsIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIn(FieldExtraParams, vs...))
}

// ExtraParamsNotIn applies the NotIn predicate on the "extra_params" field.
func ExtraParamsNotIn(vs ...string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotIn(FieldExtraParams, vs...))
}

// ExtraParamsGT applies the GT predicate on the "extra_params" field.
func ExtraParamsGT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGT(FieldExtraParams, v))
}

// ExtraParamsGTE applies the GTE predicate on the "extra_params" field.
func ExtraParamsGTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldGTE(FieldExtraParams, v))
}

// ExtraParamsLT applies the LT predicate on the "extra_params" field.
func ExtraParamsLT(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLT(FieldExtraParams, v))
}

// ExtraParamsLTE applies the LTE predicate on the "extra_params" field.
func ExtraParamsLTE(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldLTE(FieldExtraParams, v))
}

// ExtraParamsContains applies the Contains predicate on the "extra_params" field.
func ExtraParamsContains(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContains(FieldExtraParams, v))
}

// ExtraParamsHasPrefix applies the HasPrefix predicate on the "extra_params" field.
func ExtraParamsHasPrefix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasPrefix(FieldExtraParams, v))
}

// ExtraParamsHasSuffix applies the HasSuffix predicate on the "extra_params" field.
func ExtraParamsHasSuffix(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldHasSuffix(FieldExtraParams, v))
}

// ExtraParamsIsNil applies the IsNil predicate on the "extra_params" field.
func ExtraParamsIsNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldIsNull(FieldExtraParams))
}

// ExtraParamsNotNil applies the NotNil predicate on the "extra_params" field.
func ExtraParamsNotNil() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldNotNull(FieldExtraParams))
}

// ExtraParamsEqualFold applies the EqualFold predicate on the "extra_params" field.
func ExtraParamsEqualFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldEqualFold(FieldExtraParams, v))
}

// ExtraParamsContainsFold applies the ContainsFold predicate on the "extra_params" field.
func ExtraParamsContainsFold(v string) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.FieldContainsFold(FieldExtraParams, v))
}

// HasRun applies the HasEdge predicate on the "run" edge.
func HasRun() predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RunTable, RunColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRunWith applies the HasEdge predicate on the "run" edge with a given conditions (other predicates).
func HasRunWith(preds ...predicate.UxExecutionRun) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(func(s *sql.Selector) {
		step := newRunStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UxRunModelConfig) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UxRunModelConfig) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UxRunModelConfig) predicate.UxRunModelConfig {
	return predicate.UxRunModelConfig(sql.NotPredicates(p))
}
