// Code generated by ent, DO NOT EDIT.

package uxprojectaireport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the uxprojectaireport type in the database.
	Label = "ux_project_ai_report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "report_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldAiSummary holds the string denoting the ai_summary field in the database.
	FieldAiSummary = "ai_summary"
	// FieldAiStrengths holds the string denoting the ai_strengths field in the database.
	FieldAiStrengths = "ai_strengths"
	// FieldAiWeaknesses holds the string denoting the ai_weaknesses field in the database.
	FieldAiWeaknesses = "ai_weaknesses"
	// FieldAiRecommendations holds the string denoting the ai_recommendations field in the database.
	FieldAiRecommendations = "ai_recommendations"
	// FieldModelChannel holds the string denoting the model_channel field in the database.
	FieldModelChannel = "model_channel"
	// FieldSessionIds holds the string denoting the session_ids field in the database.
	FieldSessionIds = "session_ids"
	// FieldHTMLContent holds the string denoting the html_content field in the database.
	FieldHTMLContent = "html_content"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the uxprojectaireport in the database.
	Table = "ux_project_ai_report"
)

// Columns holds all SQL columns for uxprojectaireport fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldAiSummary,
	FieldAiStrengths,
	FieldAiWeaknesses,
	FieldAiRecommendations,
	FieldModelChannel,
	FieldSessionIds,
	FieldHTMLContent,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultModelChannel holds the default value on creation for the "model_channel" field.
	DefaultModelChannel string
	// ModelChannelValidator is a validator for the "model_channel" field. It is called by the builders before save.
	ModelChannelValidator func(string) error
	// DefaultHTMLContent holds the default value on creation for the "html_content" field.
	DefaultHTMLContent string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the UxProjectAiReport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByAiSummary orders the results by the ai_summary field.
func ByAiSummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAiSummary, opts...).ToFunc()
}

// ByModelChannel orders the results by the model_channel field.
func ByModelChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelChannel, opts...).ToFunc()
}

// ByHTMLContent orders the results by the html_content field.
func ByHTMLContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTMLContent, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
