// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SysModule is the predicate function for sysmodule builders.
type SysModule func(*sql.Selector)

// SysPermission is the predicate function for syspermission builders.
type SysPermission func(*sql.Selector)

// SysRole is the predicate function for sysrole builders.
type SysRole func(*sql.Selector)

// SysRolePermission is the predicate function for sysrolepermission builders.
type SysRolePermission func(*sql.Selector)

// SysUser is the predicate function for sysuser builders.
type SysUser func(*sql.Selector)

// SysUserModulePermission is the predicate function for sysusermodulepermission builders.
type SysUserModulePermission func(*sql.Selector)

// SysUserRole is the predicate function for sysuserrole builders.
type SysUserRole func(*sql.Selector)

// UxErrorRecord is the predicate function for uxerrorrecord builders.
type UxErrorRecord func(*sql.Selector)

// UxExecutionBatch is the predicate function for uxexecutionbatch builders.
type UxExecutionBatch func(*sql.Selector)

// UxExecutionPlan is the predicate function for uxexecutionplan builders.
type UxExecutionPlan func(*sql.Selector)

// UxExecutionRun is the predicate function for uxexecutionrun builders.
type UxExecutionRun func(*sql.Selector)

// UxExecutionSession is the predicate function for uxexecutionsession builders.
type UxExecutionSession func(*sql.Selector)

// UxExecutionStep is the predicate function for uxexecutionstep builders.
type UxExecutionStep func(*sql.Selector)

// UxImprovementSuggestion is the predicate function for uximprovementsuggestion builders.
type UxImprovementSuggestion func(*sql.Selector)

// UxModelDecisionRecord is the predicate function for uxmodeldecisionrecord builders.
type UxModelDecisionRecord func(*sql.Selector)

// UxOrg is the predicate function for uxorg builders.
type UxOrg func(*sql.Selector)

// UxOrgMember is the predicate function for uxorgmember builders.
type UxOrgMember func(*sql.Selector)

// UxOrgRole is the predicate function for uxorgrole builders.
type UxOrgRole func(*sql.Selector)

// UxPlanModelConfig is the predicate function for uxplanmodelconfig builders.
type UxPlanModelConfig func(*sql.Selector)

// UxPlanProfileBinding is the predicate function for uxplanprofilebinding builders.
type UxPlanProfileBinding func(*sql.Selector)

// UxPlanProfileQuestionnaireBinding is the predicate function for uxplanprofilequestionnairebinding builders.
type UxPlanProfileQuestionnaireBinding func(*sql.Selector)

// UxPlanTaskBinding is the predicate function for uxplantaskbinding builders.
type UxPlanTaskBinding func(*sql.Selector)

// UxPlanTaskQuestionnaireBinding is the predicate function for uxplantaskquestionnairebinding builders.
type UxPlanTaskQuestionnaireBinding func(*sql.Selector)

// UxProject is the predicate function for uxproject builders.
type UxProject func(*sql.Selector)

// UxProjectAiReport is the predicate function for uxprojectaireport builders.
type UxProjectAiReport func(*sql.Selector)

// UxProjectInvitation is the predicate function for uxprojectinvitation builders.
type UxProjectInvitation func(*sql.Selector)

// UxProjectMember is the predicate function for uxprojectmember builders.
type UxProjectMember func(*sql.Selector)

// UxProjectPrompt is the predicate function for uxprojectprompt builders.
type UxProjectPrompt func(*sql.Selector)

// UxProjectRole is the predicate function for uxprojectrole builders.
type UxProjectRole func(*sql.Selector)

// UxQuestionnaireAnswer is the predicate function for uxquestionnaireanswer builders.
type UxQuestionnaireAnswer func(*sql.Selector)

// UxQuestionnaireQuestion is the predicate function for uxquestionnairequestion builders.
type UxQuestionnaireQuestion func(*sql.Selector)

// UxQuestionnaireTemplate is the predicate function for uxquestionnairetemplate builders.
type UxQuestionnaireTemplate func(*sql.Selector)

// UxRecordingRecord is the predicate function for uxrecordingrecord builders.
type UxRecordingRecord func(*sql.Selector)

// UxResultSnapshot is the predicate function for uxresultsnapshot builders.
type UxResultSnapshot func(*sql.Selector)

// UxRunModelConfig is the predicate function for uxrunmodelconfig builders.
type UxRunModelConfig func(*sql.Selector)

// UxRunProfileQuestionnaireSnapshot is the predicate function for uxrunprofilequestionnairesnapshot builders.
type UxRunProfileQuestionnaireSnapshot func(*sql.Selector)

// UxRunProfileSnapshot is the predicate function for uxrunprofilesnapshot builders.
type UxRunProfileSnapshot func(*sql.Selector)

// UxRunQuestionnaireOptionSnapshot is the predicate function for uxrunquestionnaireoptionsnapshot builders.
type UxRunQuestionnaireOptionSnapshot func(*sql.Selector)

// UxRunQuestionnaireQuestionSnapshot is the predicate function for uxrunquestionnairequestionsnapshot builders.
type UxRunQuestionnaireQuestionSnapshot func(*sql.Selector)

// UxRunQuestionnaireTemplateSnapshot is the predicate function for uxrunquestionnairetemplatesnapshot builders.
type UxRunQuestionnaireTemplateSnapshot func(*sql.Selector)

// UxRunTaskQuestionnaireSnapshot is the predicate function for uxruntaskquestionnairesnapshot builders.
type UxRunTaskQuestionnaireSnapshot func(*sql.Selector)

// UxRunTaskSnapshot is the predicate function for uxruntasksnapshot builders.
type UxRunTaskSnapshot func(*sql.Selector)

// UxScreenshotRecord is the predicate function for uxscreenshotrecord builders.
type UxScreenshotRecord func(*sql.Selector)

// UxSubjectiveEvaluation is the predicate function for uxsubjectiveevaluation builders.
type UxSubjectiveEvaluation func(*sql.Selector)

// UxTask is the predicate function for uxtask builders.
type UxTask func(*sql.Selector)

// UxUserProfile is the predicate function for uxuserprofile builders.
type UxUserProfile func(*sql.Selector)
